### ISSUE TITLE
/usr/lib/os-release of a mix should have information about the Mix itself

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/mixer-tools#113]
The /usr/lib/os-release is a file with various lines KEY=VALUE that has some well-known keys (like NAME, VERSION_ID). When creating a mix, only the VERSION_ID is updated, all other information remains like in Clear Linux, so we get a confusing output.

There are some useful things to do here:

- Fix other fields to make sure it is a mix
- Create a section in builder.conf that would allow the user to provide its own fields (e.g. NAME could be something more specific than "A mix of Clear Linux")
- Create a couple of new fields to reference the upstream version and upstream URL from where this mix was made

**Comment by cmarcelo** [comment]
We are in a good position to implement this now. One idea I had was allow the user provide a os-release file and process it with the template syntax. If file isn't available, we just use a default template that has a generic NAME "Mix of clearlinux" and fills in the version id.

Also: would be nice to add a couple of fields with "UPSTREAM_VERSION=" and "UPSTREAM_URL=".

**Comment by cmarcelo** [comment]
For debugging libarchive, some starting points:

<thiago> if anyone wnats to debug this, put a breakpoint in archive_entry.c line 1301 with condition r != 0
<thiago> the debug fuse doesn't work for me (container)

**Comment by matthewrsj** [comment]
@cmarcelo wrong issue?

**Comment by cmarcelo** [comment]
Yes! Sorry for the noise.

**Comment by reaganlo** [comment]
@tmarcu @phmccarty 
Based on the Issue desc and 'man os-release', these are the changes that I recommend. Please let me know.

For a clear linux mix, the os-release file should be updated as follows:
- NAME=_"\<builder.conf ==>swupd ==> NAME>"_
E.g. **NAME="Clear Linux Mix"**
This value will be read from a new builder.conf [swupd] field called NAME and can be edited by the user. 
- ID=_\<based on above NAME field>_
E.g. **ID=clear-linux-mix**
- VERSION=_"\<mix-ver> (\<upstream-ver>)"_
E.g. **VERSION="10 (24750)"**
- PRETTY_NAME=_"\<NAME> \<mix-ver> (\<upstream-ver)"_
E.g. **PRETTY_NAME="Clear Linux Mix 10 (24750)"**
- VERSION_ID=_\<mix-ver>_
E.g. **VERSION_ID=10**
- BUILD_ID=_\<upstream-ver>_
E.g. **BUILD_ID=24750**
- UPSTREAM_URL=_"upstream-url"_
This will be a new field in os-release.
E.g.  **UPSTREAM_URL="https://download.clearlinux.org"**


**Summary:**
NAME="Clear Linux Mix"
ID=clear-linux-mix
VERSION="10 (24750)"
PRETTY_NAME="Clear Linux Mix 10 (24750)"
VERSION_ID=10
BUILD_ID=24750
UPSTREAM_URL="https://download.clearlinux.org"

**Comment by gtkramer** [comment]
I think we need to be careful here because mixer is used by both upstreams and downstreams.  If I'm understanding this right, as this is, it creates a default assumption of downstream usage?  This would require something of a `mixer set config` command to make this work for upstreams, which feels a little icky...

**Comment by rchiossi** [comment]
Mixer now supports custom os-release files.
