### ISSUE TITLE
mixer-pack-maker: add option for building packs for N versions back

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/mixer-tools#12]
Support building of packs for N versions back from the `--to` version, as an alternative to passing one or more `--from` options. Proposed option name: `--back`.

**Comment by phmccarty** [comment]
Note that the semantics would be different than the old pack maker, which built N versions back *per bundle*. The new behavior would strictly build N versions back, based on the linear sequence of VER/Manifest.MoM files generated, going back in time.

**Comment by tmarcu** [comment]
@phmccarty is this something that could be tackled with the pack-maker rewrite as well?

**Comment by phmccarty** [comment]
Yes
