### ISSUE TITLE
Add "file format" information to Manifest files (which is different than the OS content format)

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/mixer-tools#122]
To make life easier when we ever evolve the manifest files, would be good to have a way to describe the version of the file format we are using.

I think in the past this was conflated with the "format" for the OS (as it implied what version of swupd was used and so on). But as we create mixes, this correspondence is gone.

See also the description https://github.com/clearlinux/swupd-server/wiki/Manifest-structure
```
Each line in the header has 2 fields; the first is a keyword, and the second is a value. Accepted keywords are:

    MANIFEST: The first line of manifest (the "magic"). Second field indicates the format number used to create the manifest.
```

Note we also probably need to fix our manifest parsing to treat MANIFEST (or whatever we come up) like the description above.

**Comment by cmarcelo** [comment]
@icarus-sparry do you have thoughts on this?

**Comment by icarus-sparry** [comment]
Yes, I think the idea is very sound.

I would implement it as a list of fields that the "body" of the manifest has, rather than as a magic version number. This makes the data essentially self describing, and so allows us to add new fields without breaking older readers of the data (they should be programmed to ignore unknown fields). This list of fields would go in the header.

I would also allow additional header lines, again unknown ones are ignored (or probably better generate warnings).

**Comment by tmarcu** [comment]
@icarus-sparry @cmarcelo can you please describe this a bit more, do you suggest chaning MANIFEST: to FORMAT: ? Or adding more fields? I'm closing irrelevant issues and trying to add more detail for ones we can complete in Q3.

**Comment by icarus-sparry** [comment]
The basic suggestion is that the header of a MANIFEST should look something like
```
MANIFEST
version:	10
previous:	0
filecount:	1
timestamp:	1451936779
contentsize:	17929151
fields: flags hash version filename
```

then we have a blank line, and then we have 4 tab delimited fields per line. If we decide to add the size of the compressed file and the size of the uncompressed file to avoid the DOS that we are currently vulnerable to, then the `fields` line would become `fields: flags dsize size hash version filename".

Parsing code can just zip through the lines which make up the body. If an older version of swupd doesn't support the dsize field it can just ignore the dsize field.

One thing that needs to be checked carefully is that new fields are added in a compatible manner.

**Comment by matthewrsj** [comment]
That's a good idea

**Comment by cmarcelo** [comment]
CC: @otaviobp 

@phmccarty could you give us your take on this one. Seems to me that we are embedding two different meanings into the format. Restating the problem, the "format" is using for two things:

- (a) "Descriptor" of the meaning of the bytes in the manifest files. Or "the protocol". Relevant for swupd-client to know how to read the update files.
- (b) Continuous stream of OS content. Used to force a specific versions to be installed during updates (and their hooks executed). Also use a different "channel" of updates, e.g. "formatstaging".

While the issue title leans towards adding something else to cover (a), I think it also would be fine to solve the problem by finding a better mechanism for handling (b).

**Comment by rchiossi** [comment]
Are you a psychic or something? We were talking about this just a few hours ago! :)

**Comment by phmccarty** [comment]
@cmarcelo I like the idea of separating (a) from (b). But keep in mind that the (a) format is meant to encapsulate the format of update content as a whole, not just manifests -- deltas, fullfiles, and packs also must be accounted for if need be.

**Comment by cmarcelo** [comment]
> But keep in mind that the (a) format is meant to encapsulate the format of update content as a whole, not just manifests -- deltas, fullfiles, and packs also must be accounted for if need be.

Sure!
