### ISSUE TITLE
Provide better defaults to "mixer init"

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/mixer-tools#123]
At the moment, calling mix init with no arguments I get:

```
$ mixer init
Error: Required flag(s) "clear-version", "mix-version" have/has not been set
Usage:
  mixer init [flags]

Flags:
      --all                   Initialize mix with all upstream bundles automatically included
      --clear-version int     Supply the Clear version to compose the mix from (default 1)
      --config string         Supply a specific builder.conf to use for mixing
  -h, --help                  help for init
      --local-rpms            Create and configure local RPMs directories
      --mix-version int       Supply the Mix version to build
      --upstream-url string   Supply an upstream URL to use for mixing (default "https://download.clearlinux.org")

Global Flags:
      --new-swupd   EXPERIMENTAL: Use new implementation of swupd-server when possible
```

Things that could be improved:

- There is a "default 1" for --clear-version, which is not possible because it is a required argument. The version "1" also is not good when passed to mixer itself (it would fail).
- We could default the clear-version to be the latest published release at the moment (or the current version of Clear Linux the user is running).
- We could default the mix-version to be just 10 (or even 1).

Note that one side effect is that "mixer init" would just work without arguments, so the other facilities it provides should be easy to get some other way.

**Comment by cmarcelo** [comment]
> Note that one side effect is that "mixer init" would just work without arguments, so the other facilities it provides should be easy to get some other way.

E.g. of this: might make sense to add the lines in builder.conf about RPM commented, so it is easy for the user to bump (if there's no other straightforward way).

**Comment by cmarcelo** [comment]
Also a small thing: the clearversion and mixversion files could have a newline added to them (we probably already handle that when reading them).

**Comment by rchiossi** [comment]
> Note that one side effect is that "mixer init" would just work without arguments, so the other facilities it provides should be easy to get some other way.

What is the problem with also accepting arguments in mixer init?

> E.g. of this: might make sense to add the lines in builder.conf about RPM commented, so it is easy for the user to bump (if there's no other straightforward way).

This use case has showed up quite often. Maybe we could have a `mixer bump` command just to handle that.

**Comment by cmarcelo** [comment]
> What is the problem with also accepting arguments in mixer init?

That is not a problem at all. I was just pointing that if all the suggestions there are implemented / accepted, mixer init would work without any arguments.

**Comment by kevincwells** [comment]
> We could default the clear-version to be the latest published release at the moment (or the current version of Clear Linux the user is running).

My personal take is that mixer defaults should never be tied to the current version the build server is running. This one may seem innocuous, but it's a bad precedent to set. There is no conceptual link between the version a build server is at (which could be locked to a specific version by a user or dev-ops for any number of reasons) and what version a mix is made from, so having pragmatic links ('cause it's easy to pull from `/user/share/defaults/swupd/version`) create a lot of opportunities for confusion.

_Latest published release_, on the other hand, is a great default value, and I have code sitting on a long-since-forgotten branch that pulls the latest upstream CLR version:

```go
// Get latest CLR version
func GetLatestCLRVersion() (string, error) {
	resp, err := http.Get("https://download.clearlinux.org/latest")
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	body, err := ioutil.ReadAll(resp.Body)
	ver = strings.TrimSpace(string(body))
	return ver, nil
}
```

**Comment by kevincwells** [comment]
> Note that one side effect is that "mixer init" would just work without arguments, so the other facilities it provides should be easy to get some other way.

> E.g. of this: might make sense to add the lines in builder.conf about RPM commented, so it is easy for the user to bump (if there's no other straightforward way).

I don't follow this. What other facilities are you talking about, and why would not _needing_ params mean you'd need a different way of getting at that other functionality? (I realize you just provided an example of what other facilities, but I'm not understanding your example yet.)

**Comment by cmarcelo** [comment]
> I don't follow this. What other facilities are you talking about, and why would not needing params mean you'd need a different way of getting at that other functionality? (I realize you just provided an example of what other facilities, but I'm not understanding your example yet.)

Note that this comment was made with the mindset of init being called only once in a working directory.

There is the --local-rpms option in init, I've called that a facility. If I don't pick it, how do I get to use local RPMs? Would be nice if there was an easy way to get that. If what --local-rpms does is to add a section to the configuration, could we make it so that the section is there, but commented. That way my path to use RPMs is slightly better.

I see now how "mixer init would just work without arguments" got interpreted as "mixer should not have flags", but I meant something like "mixer should not have _required_ flags".

**Comment by kevincwells** [comment]
>>Latest published release, on the other hand, is a great default value, and I have code sitting on a long-since-forgotten branch that pulls the latest upstream CLR version:

>Sounds good, could you cook a patch to use it for init?

See #153
