### ISSUE TITLE
Should we remove --config from "mixer init"?

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/mixer-tools#124]
Since init is about creating the config file, what does the "--config" is used for. It seems wrong, should be removed or the documentation of it clarified.

**Comment by cmarcelo** [comment]
@rchiossi ^

**Comment by tmarcu** [comment]
We can consider it. The people who are supplying their own configs are generally not calling init anyway, and the current code checks if a config exists already.

**Comment by rchiossi** [comment]
Originally you could use `--config` to specify the directory where builder.conf would be created, but this was dropped along the way.
Now, for people with a builder.conf in a remote directory, it is needed to run InitMix() on that config. It is responsible for creating `.clearversion`, `.mixversion` and `.clearurl` files and setup the bundles directory and the RPMs directories.
Unless those people really like creating this stuff by hand, I don't think we can drop this option.

**Comment by tmarcu** [comment]
I think taking this out would add more work to deal with configs and output dirs being stored in remote locations.

**Comment by cmarcelo** [comment]
I probably have a wrong understanding about what we want 'mixer init' to do. I thought the goal was to use it only to create a new config, so passing a config to be opened seems wrong. If that is not the case, this issue should be closed.
