### ISSUE TITLE
mixer init output could be more useful

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/mixer-tools#127]
See #126 for how the output looks like. The first line (which tells the user about builder.conf) which I think is an important one gets scrolled with pages of output (even when using a lot of lines in my terminal).

Ideas:
- Do not output one line per bundle when adding them. Maybe list them in one long line instead.
- Omit the Git output in case of success and just tell me you created a git repository for me.
- Consider if it is valuable to add one our two helpful indications about the next steps: "To create a build do this, to bump version do that".

**Comment by rchiossi** [comment]
> Do not output one line per bundle when adding them. Maybe list them in one long line instead.
I don't feel like this is a good idea. The info will likely get so clogged that will just be a blob of information popping on your screen.

> Omit the Git output in case of success and just tell me you created a git repository for me.
agree

> Consider if it is valuable to add one our two helpful indications about the next steps: "To create a build do this, to bump version do that".
agree, but I think it should be better to introduce a `silent` option before, so we don't have to worry too much about the verbosity of those outputs.

**Comment by rchiossi** [comment]
I'll draft a PR to handle those issues, then we can iterate over it if it is still not clean enough.

**Comment by kevincwells** [comment]
@rchiossi  If it's not a big deal, can you hold off on this for a few days? The way init adds things to the mix and initializes the git repo is all changed in my #107 that i'm refactoring.  I like these changes, it'll just involve less rework if it's done after.

**Comment by kevincwells** [comment]
:+1: to cutting the git output. I already pass `-q` in `AddBundles` for this same reason.

As for outputing bundles line-by-line or all-on-one, I think it'd be nice if it only printed the output for a small number of bundles. It only really becomes an issue if it's `--all`. The bundles are added using `AddBundles`, so we could either drop the print-out from that command  altogether, or pass in a quiet option.

**Comment by rchiossi** [comment]
> @rchiossi If it's not a big deal, can you hold off on this for a few days? The way init adds things to the mix and initializes the git repo is all changed in my #107 that i'm refactoring. I like these changes, it'll just involve less rework if it's done after.

@kevincwells No problem. I'll wait for your PR then.

**Comment by tmarcu** [comment]
bumps?

**Comment by tmarcu** [comment]
N/A
