### ISSUE TITLE
When generating chroots, get the list of packages in a better way

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/mixer-tools#133]
The current approach is to call 'yum list' and parse the results with a lot of workarounds.

See the whole story in this function https://github.com/clearlinux/mixer-tools/blob/64e3c26c1dc1bc813dc765c73ed0acf3949af6b7/builder/chroots.go#L357.

**Comment by cmarcelo** [comment]
George suggested the following

<gtkramer> I was wondering what might be able to be done to ensure that plugins for either dnf or yum could be used during chroot creation?  I was wondering if this might be a good opportunity to use repoquery --plugins -qa -qf '<some format>' to gather the list of packages from a repo.  This would suppress all the extra output and just get a list of packages, and would largely remove the need for banned words

**Comment by cmarcelo** [comment]
CC: @matthewrsj 

This may or may not be useful to you. I think the list of packages we are holding in a text file could maybe also be something in the JSON file (or not since is not essential). Maybe some "optional" field(s) to store this kind of information about the bundle. I say optional so we don't enforce bundles to come from packages necessarily.

That way the JSON will be the "one file" we need to keep around per bundle.

**Comment by matthewrsj** [comment]
Ah, the work I have extends the bundle struct in builder/bundleset.go with a list of file paths. All that info is in the JSON for whoever wants to use it. My work also removes the packages files and the includes files.
