### ISSUE TITLE
Import swupd-server functional tests

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/mixer-tools#138]
Using this issue to keep of imported tests

Original test | New test *(comments)*
---- | ----
basic | N/A *(checks help output for commands)*
contentsize-across-versions-includes | `TestContentSizeAcrossVerionsIncludes`
delete-no-version-bump | `TestCreateManifestDeleteNoVerBump`
file-name-blacklisted | `TestManifestIllegalChar`
file-name-debuginfo | `TestManifestDebuginfo`
format-bump | N/A *(actions deprecated per #140)*
format-no-decrement | `TestCreateManifestFormatNoDecrement`
fullfiles | N/A *(checking command line usage of fullfiles binary)*
full-run | `TestFullRun`
full-run-delta | `TestFullRunDelta`
ghosting | `TestCreateManifestGhosted`
includes-deduplicate | `TestCreateManifestIncludesDeduplicate`
include-version-bump | `TestIncludeVersionBump`
no-delta | `TestNoDeltasForTypeChangesOrDereferencedSymlinks`
orphaned-renames | `TestCreateManifestsRenamesOrphanedDeletes` and `TestCreateRenamesOrphanedChain`
pack | N/A *(checking command line usage of pack binary)*
renames | *(#128)*
renames2 | *(#128)*
state-file | `TestCreateManifestsState`
subtract-delete | `TestSubtractDelete`
update | N/A *(checking command line usage of update binary)*

**Comment by cmarcelo** [comment]
@matthewrsj I did a best effort to identify what tests you've already imported and if they were already complete, but this worth a quick look in case I've missed anything.

**Comment by matthewrsj** [comment]
orphaned-renames: #134

**Comment by matthewrsj** [comment]
The `renames` and `renames2` tests are pretty decently covered by #128. #128 is now the PR that implements the `orphaned-renames` test.

#143 is merged. #142 is merged.

**Comment by cmarcelo** [comment]
> The renames and renames2 tests are pretty decently covered by #128.

I haven't looked in detail, but a quick glance on the original rename tests seems to have more test cases, e.g. checking if we don't create rename from "small" to "large" files (even if the delta was worthwhile). But maybe these are being tested elsewhere. Are we sure there isn't anything else there to pick up?

(I'm confirming this because importing tests as they are already uncovered a couple of issues).

**Comment by cmarcelo** [comment]
Closing this. Besides tests in rename, various other tests were added.
