### ISSUE TITLE
Format bumps add an "action" in the manifest header

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/mixer-tools#140]
When there was a format bump, swupd-server marked the MoM header with an "action: update".

https://github.com/clearlinux/swupd-server/blob/010131eb85b7b6a86b9febcdb6ce1891e05c8ad7/src/create_update.c#L376

See also the functional test: https://github.com/clearlinux/swupd-server/blob/master/test/functional/format-bump/test.bats#L55

**Comment by matthewrsj** [comment]
This "feature" is actually deprecated now and the detection is done client side. Didn't get around to removing it from the old server because we started rewriting. Consider this comment documentation that this isn't needed server-side (at least for now).

**Comment by cmarcelo** [comment]
Thanks!
