### ISSUE TITLE
Fail when the user is trying to create a mix that breaks format bumps

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/mixer-tools#145]
This is a first step towards #59: first we identify the undesired situation and do not generate a potentially invalid update. This is an easier task than providing auto format bumps, and identifying the case is necessarily anyway. Optionally add a flag to allow forcing create the mix even in the invalid scenario.

This only applies to mix creation, so regular Clear Linux workflow shouldn't be affected (no mix version in that workflow).

**Comment by tmarcu** [comment]
I just want to make sure your PR doesn't ignore the mixversion, as upstream workflow still uses it, but it happens to be that .mixversion = .clearversion.

**Comment by cmarcelo** [comment]
I thought that upstream workflow used mixversion == "" and only set clearversion.

**Comment by cmarcelo** [comment]
I think the "versions update" command (#188) will be sufficient to close this. It does prevent unwanted bumps until we support them.

**Comment by tmarcu** [comment]
Check merged into mastre.
