### ISSUE TITLE
Identify what deltas to put in packs based on rename data

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/mixer-tools#146]
Keeping track of

https://github.com/clearlinux/mixer-tools/blob/9b69f7a68ca41f84cd63d9d61ab3cce66b3c7e78/swupd/manifest.go#L543

once rename lands.

**Comment by matthewrsj** [comment]
**the rename has landed** 🦅

**Comment by matthewrsj** [comment]
Disregard, still has a conflict

**Comment by icarus-sparry** [comment]
OK, all tests passing and eventually rebased onto master.

Git was not happy about two different sets of changes to create_manifest_test.go!

**Comment by matthewrsj** [comment]
**the rename has landed** 🦅

**Comment by cmarcelo** [comment]
@icarus-sparry @tmarcu @matthewrsj 

Rename question.

`
# In version 10 Manifest we have identical files.
F... HASH1 10 fileA
F... HASH1 10 fileB
`

Then in version 20 (I'll describe the chroot of it): both files are gone, and there are two new files, identical to the other ones, called `dir2/fileA`, and `dir1/fileB`. What does the manifest for 20 looks like?

A second question, what does the manifest would look like if the new files were called `fileC` and `fileD`?

I'm trying to understand how the client decide (or is expected to decide) what is being rename to what, when it sees a `.d.r HASH filename`, I've previously got the impression that it could find the target file by matching the hash, but there might be more than one "to-rename" (e.g. `F..r`) that has the same hash.

**Comment by matthewrsj** [comment]
client will detect one pair as a rename as it processes the manifest, then the remaining.

So if fileA was renamed to dir2/fileA, client my actually detect fileA->dir1/fileB and fileB->dir2/fileA. That is fine because the to-from hashes will be identical. It can use the same delta even.

**Comment by icarus-sparry** [comment]
You would have this in the 20 Manifest

    .d.r HASH1 10 fileA
    .d.r HASH1 10 fileB
    F..r HASH1 20 dir2/fileC
    F..r HASH1 20 dir2/fileD

The client can decide  how it is going to do the rename - the hash (hopefully) tells us the content is identical, so it doesn't matter which is the 'source' for which 'destination'.

**Comment by matthewrsj** [comment]
@icarus-sparry +1 for his clearer example.

**Comment by cmarcelo** [comment]
I think I've got it. Thanks!

**Comment by cmarcelo** [comment]
@matthewrsj a client question. (also related to a conversation with @tmarcu)

It seems the client takes a more optimistic approach with regard to deltas than I was thinking. See 

https://github.com/clearlinux/swupd-client/blob/master/src/manifest.c#L1268

it walks through the new manifest files looking for rename pairs. If there's a pair, it checks the fromManifest to see if there's a file with that name.

So if we create extra deltas for files other than the "exact previous version of file -> new version of file", swupd-client today will be able to consume that. Am I reading this correctly?

**Comment by matthewrsj** [comment]
@cmarcelo so I'll cautiously say that should work, just based on the fact that that function is only called in the update path with from_manifest being the current manifest on the system.

Very nice catch!
