### ISSUE TITLE
swupd: only fill the tar header with values we care about

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/mixer-tools#195]
Right now we are taking whatever default the tar library reads from os.FileInfo, we should restrict to only read. It is not totally trivial to fix this because you need to get Uid/Gid, that are not available directly in os.FileInfo. See the source code of tar or of swupd-extract (that needs to read Uid/Gid).

See also: https://github.com/clearlinux/mixer-tools/blob/master/swupd/fullfiles.go#L363

**Comment by tmarcu** [comment]
@cmarcelo can you clarify if this is still relevant?

**Comment by cmarcelo** [comment]
Sure. When we create tar files, the library expects to know what metadata to put in (the tar.Header).

Right now the header is created using a helper function from archive/tar that grabs as much as information as possible from file in the disk. The issue is that it might get metadata we don't care about (e.g. AccessTime) and generate unnecessarily different tar files.

The original suggestion was to create the tar.Header ourselves, and that is still a valid option. An alternative idea is to keep using the helper function from the library, and either copy the values we care about to a new header or clean the values we don't care from the other header. (I haven't looked in the details of which one of those is a better choice, though).
