### ISSUE TITLE
Repeated calls to 'mixer bundle add'

### ISSUE THREAD

**Issue by kevincwells** [clearlinux/mixer-tools#213]
If a user calls `mixer bundle add <bundle>` multiple times, mixer still outputs `Adding bundle <bundle> from upstream bundles` every time. To improve clarity to users and better mirror the output of other commands, this output should instead report something like `Bundle <bundle> already found in mix; skipping`

**Comment by matthewrsj** [comment]
Is it skipped, or is the definition update/replaced with upstream?

**Comment by kevincwells** [comment]
This command adds the mix _to your Mix Bundle List_  (aka, "to your mix"), and thus does not affect definition files whatsoever. And as the Mix Bundle List is treated as a set, adding it to the list multiple times has the same effect as skipping. The patch I'm submitting just literally skips, and says so.

**Comment by matthewrsj** [comment]
ah ok.
