### ISSUE TITLE
listing bundles with missing local-bundles dir fails

### ISSUE THREAD

**Issue by mrkz** [clearlinux/mixer-tools#238]
IMO listing bundles when there's no local-bundles dir should be similar as having an empty local-bundles dir instead of an error.
```
ardilla@magneto ~/mix $ mixer bundle list
bootloader     (upstream) 
kernel-native  (upstream) 
os-core        (upstream) 
os-core-update (upstream) 

ardilla@magneto ~/mix $ ls local-bundles/

ardilla@magneto ~/mix $ rm -rf local-bundles

ardilla@magneto ~/mix $ mixer bundle list
ERROR: Failed to read bundles dir: /home/ardilla/mix/local-bundles: open /home/ardilla/mix/local-bundles: no such file or directory
```

**Comment by rchiossi** [comment]
I belive the main reason is because if you are making a new mix you are expected to have something that is not upstream. That is why LOCAL_BUNDLES_DIR is a required property in builder.conf

**Comment by bryteise** [comment]
Hrm I'd expect somebody to want to make a mix with exactly what is upstream though just having their own release cadence. Seems like a reasonable feature.

**Comment by kevincwells** [comment]
Or someone could want to limit their customers to a subset of what is in CLR.

**Comment by tmarcu** [comment]
The other option is to just mkdir the directory, either way I agree don't fail.

**Comment by mrkz** [comment]
The dir is created on mix init, but I deteled it for cleaning the dir (as I
won't create new bundles). But if it doesn't fail for empty dir, i would
expect to ignore the dir if it doesn't exists.

**Comment by kevincwells** [comment]
It doesn't seem wrong to me to fail if, in fact, `LOCAL_BUNDLE_DIR` is set. But it also seems reasonable to me to allow you to not set it and have it not exist.

**Comment by rchiossi** [comment]
In that case we need to change builder everywhere BundlesDir is used, not only for list bundles, since it expects the dir to always exists,

**Comment by kevincwells** [comment]
> In that case we need to change builder everywhere BundlesDir is used, not only for list bundles, since it expects the dir to always exists,

`LocalBundleDir`, but yeah, we would :frowning_face: 

But that's not that many places and it seems like a reasonable thing to me at first blush

**Comment by kevincwells** [comment]
>But if it doesn't fail for empty dir, i would expect to ignore the dir if it doesn't exists.

This I don't agree with. If you try to `ls` an empty directory, it returns nothing. Try to `ls` a non-existent directory, you get a `No such file or directory` error.

**Comment by kevincwells** [comment]
If we allow people to leave `LOCAL_BUNDLE_DIR` unset, it would mean that `mixer bundle edit` (which writes to `LOCAL_BUNDLE_DIR`) would need to fail cleanly with a nice message about `LOCAL_BUNDLE_DIR` not being set.

For other commands that only read from `LOCAL_BUNDLE_DIR`, we have the option of silently treating it like it is empty or actively commenting that local `LOCAL_BUNDLE_DIR` is not defined. Each seems appropriate for different situations.

Example: `mixer bundle list mix` technically reads from `LOCAL_BUNDLE_DIR` to give metadata about your bundles. It'd be sufficient to silently treat it as empty. For `mixer bundle list local` or `mixer bundle validate`, however, both of which are commands directly acting on local bundles, it probably makes sense to say it's not defined.

**Comment by tmarcu** [comment]
Attempting to do this with an empty directory works as expected with no output. This should not silently continue on missing dir because there's no context as to why it's not there, yet defined in the conf.
