### ISSUE TITLE
mixer build update merges paths incorrectly

### ISSUE THREAD

**Issue by mpurzynski** [clearlinux/mixer-tools#251]
When trying to update my mix from upstream version 21530 to 21630 I'm getting the following error (after having updated chroots, bumped a local version, etc).

ERROR: couldn't build update: failed to create update metadata: lstat /home/clr/mix/update/image/390/full/usr/share/systemd/language-fallback-map/usr/lib/systemd/system/multi-user.target.wants/prebuilt-trust-store.service: not a directory

Looks like two paths that have little to do with each other got merged?

A full log of my actions follows

root@clr-141f7bb770c54e568adf625071d8151f /home/clr/mix # mixer versions update --new-swupd
Current mix:      380
Current upstream: 21630 (format: 25)

Updated mix:      390
Updated upstream: 21630 (format: 25)

Wrote mixversion.
Wrote upstreamversion.
root@clr-141f7bb770c54e568adf625071d8151f /home/clr/mix # sudo mixer build chroots --new-chroots
Building bundles...
=> BUILD BUNDLES
Creating bundles for version 390 based on Clear Linux 21630
Preparing new /home/clr/mix/update/image/390
  and dnf config: /home/clr/mix/.yum-mix.conf
Packager command-line: dnf --config=/home/clr/mix/.yum-mix.conf -y --releasever=21630
Resolving packages using 2 workers
processing kernel-native
processing os-core
... done with kernel-native
processing os-core-update
... done with os-core-update
processing syslog-ng
... done with os-core
processing bootloader
... done with bootloader
processing bro
... done with bro
... done with syslog-ng
Resolving files using 2 workers
processing os-core-update
processing syslog-ng
Bundle os-core-update	2654 files
processing bootloader
Bundle bootloader	836 files
processing bro
Bundle bro	4856 files
processing kernel-native
Bundle syslog-ng	1446 files
processing os-core
Bundle kernel-native	3657 files
Bundle os-core	1974 files
Cleaning DNF cache before full install
Installing all bundles to full chroot
[1/6] bro
[2/6] kernel-native
[3/6] os-core
... building special os-core content
[4/6] os-core-update
... Adding swupd default values to os-core-update bundle
[5/6] syslog-ng
[6/6] bootloader

TIMINGS
  BUILD BUNDLES 25.193s
TOTAL: 25.193s
root@clr-141f7bb770c54e568adf625071d8151f /home/clr/mix # sudo mixer build update --new-swupd
=> CREATE MANIFESTS
[1/7] kernel-native
[2/7] os-core

TIMINGS
  CREATE MANIFESTS 0s
TOTAL: 0s
ERROR: couldn't build update: failed to create update metadata: lstat /home/clr/mix/update/image/390/full/usr/share/systemd/language-fallback-map/usr/lib/systemd/system/multi-user.target.wants: not a directory
root@clr-141f7bb770c54e568adf625071d8151f /home/clr/mix # sudo mixer build update --new-swupd
=> CREATE MANIFESTS
[1/7] kernel-native
[2/7] os-core

TIMINGS
  CREATE MANIFESTS 0s
TOTAL: 0s
ERROR: couldn't build update: failed to create update metadata: lstat /home/clr/mix/update/image/390/full/usr/share/systemd/language-fallback-map/usr/lib/systemd/system/multi-user.target.wants/prebuilt-trust-store.service: not a directory
root@clr-141f7bb770c54e568adf625071d8151f /home/clr/mix #

**Comment by matthewrsj** [comment]
We just figured out the root cause of this yesterday (well not full root cause, but we figured out where to pass the blame). You need to make sure you are running in a UTF-8 locale. It turns out the following internal command

`dnf repoquery --quiet -l systemd ca-certs-static ...`

combines the systemd file list and the ca-certs-static file list with no newline in between *if the command is not running in a UTF-8 locale*. This only happens with these two packages (that I've seen), and when the locale is not set to UTF-8. 

One gotcha is that even if your system has this locale set some runtime environments do not respect this env var. We have seen this issue with both jenkins and docker environments so far, so if you are using one of these please set LC_ALL=en_US.UTF-8 in those environments.

**Comment by cmarcelo** [comment]
> You need to make sure you are running in a UTF-8 locale. It turns out the following internal command
> ```dnf repoquery --quiet -l systemd ca-certs-static ...```

Could mixer set the environment variable when calling dnf?

**Comment by matthewrsj** [comment]
That's probably a good idea.
