### ISSUE TITLE
Improve error message when network connectivity fails

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/mixer-tools#252]
We have a set of users that will hit this kind of error because they need https_proxy but it is not set:

```
$ mixer init
Creating new builder.conf configuration file...
ERROR: Failed to retrieve latest published upstream version: Get https://download.clearlinux.org/latest: dial tcp 198.145.21.150:443: i/o timeout
```

It may be worthwhile to show a more human friendly error message here for such case, and if the relevant proxy is not set also suggest it as one option.

Also consider whether reducing the timeout could be helpful. (The default is a bit long).

**Comment by icarus-sparry** [comment]
Or I just get my localproxy stuff in soon so they don't need to set https_proxy explicitly.....

**Comment by tmarcu** [comment]
N/A

**Comment by cmarcelo** [comment]
> N/A

What does "N/A" mean?

**Comment by phmccarty** [comment]
"not applicable" usually

**Comment by anselmolsm** [comment]
Why N/A?

**Comment by rchiossi** [comment]
@anselmolsm is a scary guy, so I patched it! :)

**Comment by anselmolsm** [comment]
@rchiossi haha :P
