### ISSUE TITLE
build-image: support configurable state directory for ister

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/mixer-tools#26]
Ister supports the `-S` option to customize the swupd-client state directory location instead of using /var/lib/swupd. It would be nice if `mixer build-image` also supported a configurable client state directory, via command line option, builder.conf option, or both.

**Comment by tmarcu** [comment]
Agreed, the plan is to make it configurable, and to use a temp directory by default instead of /var/lib/swupd. It really should have its own clean statedir to avoid any corruption.

**Comment by cmarcelo** [comment]
https://github.com/clearlinux/mixer-tools/pull/47 made it use a temporary directory.
