### ISSUE TITLE
'mixer build bundles' fails with local and upstream package collisions.

### ISSUE THREAD

**Issue by kevincwells** [clearlinux/mixer-tools#260]
# Issue
Mixer fails to build update content if local and upstream rpm repositories have a package name collision with different content.

# Cause
`mixer build bundles` now relies on the output of `dnf repoquery -l` to get the contents of a given package and `dnf install` to put the contents of that package into the `full` chroot. `dnf repoquery` does not utilize the repository prioritization resolver that `dnf install` does, and instead lists the contents of every matching package in every repository. This results in the `<bundle>-info` file containing the file lists of both the upstream and the local version of the rpm, but the `full` chroot only containing the actual files from the (higher-priority) local rpm. `mixer build bundles` then fails as it attempts to resolve missing files.

# Proposed Solution(s)

- Further parse the output of `dnf install` to attain not just the list of package names, but also their version and release values. Use the full N-V-R value in the `dnf reqoquery -l`, so only one repository will return a match.
  - This has the limitation of still not allowing a full N-V-R collision between repositories. The implication is that if you want to replace an upstream package with a different version _of the same version number_, you **must** change the release number.
- Further parse the output of the `dnf install` to attain not just the list of package names, but also the repository they came from. Group packages by repository, and perform one batched `dnf repoquery -l --repo` per repo.
  - This is a more robust solution (full N-V-R collisions will be resolved correctly), but requires a much more significant refactor of the code.

**Comment by kevincwells** [comment]
@matthewrsj - does this adequately reflect your understanding of the conversation we just had? Writing this down in case I can't fix this before I leave.

**Comment by icarus-sparry** [comment]
Another solution is to implement the "zero root" approach and make the selection of the rpm's better (i.e. don't do `dnf install` at all, and make the virtual `dnf repoquery` know about priorities).
