### ISSUE TITLE
Need to support storing kernel source under /usr/src

### ISSUE THREAD

**Issue by bwarden** [clearlinux/mixer-tools#264]
https://github.com/clearlinux/mixer-tools/blob/c13b0dbf505eb750ec7d507f57be258274826a2e/swupd/heuristics.go#L62

Kernel source (e.g. to support building out-of-tree modules) is typically stored beneath /usr/src, but this path is specifically disallowed.

Example path: /usr/src/linux-4.16.4-556.native/

**Comment by tmarcu** [comment]
@bwarden can you clarify on this issue some more? CBM handles all the kernel stuff so things have to be put in specific places.

**Comment by bwarden** [comment]
This is no longer needed as I've moved the relevant content under /usr/lib/modules.
