### ISSUE TITLE
Allow LOCAL_BUNDLE_DIR ('local-bundles') to be a repository

### ISSUE THREAD

**Issue by mbelluzzo** [clearlinux/mixer-tools#269]
My mix custom bundles are kept on its own git repository. It is very convenient to just git clone that repository on LOCAL_BUNDLE_DIR for mixing. It used to work just fine when 'mix-bundles' was the bundles folder.

Now if I try to do that I get the following errors:
```shell
[murilo@clearlinux mix]$ mixer bundle list
ERROR: read /tmp/mix/local-bundles/.git: is a directory
[murilo@clearlinux mix]$ mixer bundle add --all-local
ERROR: Failed to read local bundles dir: /tmp/mix/local-bundles: read /tmp/mix/local-bundles/.git: is a directory
```

**Comment by matthewrsj** [comment]
We should just ignore all `.files` in this case.
