### ISSUE TITLE
New Feature: 'mixer init'

### ISSUE THREAD

**Issue by rchiossi** [clearlinux/mixer-tools#27]
Note: This issue is a feature proposal and should be labeled as 'Enhancement'.

Right now, the process of creating a new mix requires the user to go through a couple manual steps that can easily be automated and packed into a mixer command. The idea behind having this "mixer init" command is to mimic the functionality of a "git init" command and have the active folder set up for a mix to be performed.
This command should automate the initial setup steps of the workflow guide found here (https://clearlinux.org/documentation/clear-linux/guides/maintenance/mixer.html), namely:

* Copy `builder.conf` template file into the active directory
* Set active directory as the root for all the parameters under the [Builder] tag
    * e.g. `SERVER_STATE_DIR=$PWD/update`
* Create `local/` and `rpms/` directories
* Add `RPMDIR` and `REPODIR` to `builder.conf` and set them to the above directories

Fetching the Ister configuration could also be part of this command, but as this requires accessing an external server to get the config file, I believe it should not be part of it for now.

Any suggestions on extra or different behavior of this command are more than welcome.

**Comment by tmarcu** [comment]
This would be a great improvement. I agree the ister config file probably should be fetched later on, i.e as part of image building perhaps if it doesn't exist, maybe even from a template file like the builder.conf currently is.
I can imagine this replacing (or expanding) the current mixer init-mix command, and letting version setting either be an option to this, or just letting the version settings be handled by the build command later on by something like `mixer build <VER>...`.

**Comment by rchiossi** [comment]
merged in pr #101
