### ISSUE TITLE
Allow the user to set CONTENTURL and VERSIONURL during mixer init

### ISSUE THREAD

**Issue by mbelluzzo** [clearlinux/mixer-tools#270]
Just makes life easier, specially for scripts running mixer.

**Comment by rchiossi** [comment]
Those variables will soon be part of builder.conf. See this commit for reference: https://github.com/rchiossi/mixer-tools/commit/028460bc59d51b989ede316ed35b5b3695d8d144
(This is part of an ongoing patch I'm working on)

**Comment by mbelluzzo** [comment]
Those are already part of the builder.conf file, but I can't set its value during a 'mixer init' call.

If I understood your ongoing patch right, you are just moving the info located outside builder.conf to be inside it. But are you also adding more options so we can change values in builder.conf file in a convenient way?

**Comment by rchiossi** [comment]
Ah, got it. I don't think adding commands for every single configuration is the way to go, but we might be able to allow then to be set as envvars. I'll look into it.

**Comment by mbelluzzo** [comment]
For non human users, editing a config file is a pain. If we provide a pre-built one, its hard to keep track of changes you guys do here. So I do say that for me commands like mixer version update are a nice feature.

**Comment by tmarcu** [comment]
Mixer allows more fine grained configuration of it's variables now.
