### ISSUE TITLE
mixer versions update: Add argument to set the format as well

### ISSUE THREAD

**Issue by mbelluzzo** [clearlinux/mixer-tools#271]
In order to automate format bumps, the only value that still need to 'sed'ed on builder.conf is the format. If would help a lot on automation if we could just set the format number as easy as we can set clear-version and mix-version (Doesn't need to be via 'versions update')

**Comment by rchiossi** [comment]
There is a `mixer config set` command incoming, but I'm not convinced that it should work for format. Sounds misleading since a user might think just bumping on builder.conf is enough to do a format bump.

**Comment by mbelluzzo** [comment]
It would also be useful when someone is starting a mix from a clean environment but needs that his mix be of a given FORMAT to match previous builds. Imagine something happened with the workspace  but we need to keep going with a update stream that is already being provided to users.

**Comment by rchiossi** [comment]
That doesn't seems like a common use case. For such situation I don't think editing the file is too much of a problem. But I see your point. Originally I planned mixer configuration set to be agnostic and just edit the file, the the team was vocal against it for the reason I mentioned.

**Comment by gtkramer** [comment]
@rchiossi I think this would be a good use case for any downstream that wants to set up robust automation.  Perhaps if it's confusing to have a `mixer config set format` command, we could clarify this through documentation for mixer in a man page.

**Comment by tmarcu** [comment]
We will add this to mixer init, since format is automatically handled in all other bump cases.

**Comment by rchiossi** [comment]
Implemented in #381
