### ISSUE TITLE
Eliminate the "--local-rpms" options with "mixer init" and just automatically create the local-rpms and local-yum directories

### ISSUE THREAD

**Issue by bktan8** [clearlinux/mixer-tools#275]
Why not just automatically create the local-rpms and local-yum directories and add their paths into the builder.conf file without the user having to specify the "--local-rpms" option as part of the "mixer init"?

If the user misses the "--local-rpms" options at the beginning, s/he has to manually create the these "local" workspaces and modify the builder.conf which can lead to errors if not modified correctly.

**Comment by tmarcu** [comment]
Sure!

**Comment by bktan8** [comment]
awesome!
