### ISSUE TITLE
Would like to know the size of a mix with something like "mixer versions --size"

### ISSUE THREAD

**Issue by bktan8** [clearlinux/mixer-tools#280]

**Comment by matthewrsj** [comment]
can you be more specific? size of update? size of entire OS? size of each bundle? size of upstream? size of local only? size of local-rpms?

**Comment by matthewrsj** [comment]
This is not a trivial request, depending on what you are asking for.

**Comment by bktan8** [comment]
I'd like to know total size of all bundles in the mix and total size of the update.

**Comment by matthewrsj** [comment]
> total size of the update

Not sure about this one. An update can be from any version to any version, can include any bundle or not include any bundle.

> size of all bundles in the mix

So size of the entire os content for any version? I'm not seeing the usefulness of this to be honest. What is the specific use case?

For now you can run `du -sh <mix-workspace>/image/<mix-version>/full` and it will give you exactly what you want.

**Comment by matthewrsj** [comment]
Closing as wontfix
