### ISSUE TITLE
"mixer versions update" fails without a network connection to the upstream server

### ISSUE THREAD

**Issue by bktan8** [clearlinux/mixer-tools#282]
Incrementing mixversion with "mixer versions update" doesn't work unless there's a network connection.  Even if I add the "--offline" option, it still won't work.

**Comment by cmarcelo** [comment]
builder.go:UpdateVersions currently does all the checking of the upstream version is not going to change. In that case, these could probably be skipped.

**Comment by tmarcu** [comment]
@bktan8 you mean specifically just updating your mix version offline yes? Otherwise the upstreamversion option MUST use network because it's changing the base.

**Comment by bktan8** [comment]
@tmarcu - Yes, i'd like ability to increment my mix version without requiring a connection to upstream Clear.

**Comment by tmarcu** [comment]
Pending PR approval.
