### ISSUE TITLE
Extend mixer tool to support other linux distribution systems

### ISSUE THREAD

**Issue by TZRLYMY** [clearlinux/mixer-tools#291]
Is it possible to use the mixer tool to control system version of the centos 7? Or need to make some changes and customization?
Any suggestions?

**Comment by matthewrsj** [comment]
What exactly are you asking for? Mixer builds update content for swupd-client, the updater used by Clear Linux (and in some cases yocto I believe). Centos uses DNF to apply updates to installed RPMs. Swupd is a file-based updater and uses manifests to coordinate updates. These are entirely different, and incompatible, update mechanisms. 

Can you give some more details what you are looking for?

**Comment by tmarcu** [comment]
N/A, no reply.
