### ISSUE TITLE
Store the ClearLinux distribution and version used for Mix

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/mixer-tools#30]
Have Mixer save the upstream URL and version used when generating the new Mix.

This information is both useful historical information about the Mix as well as needed by any automation used to generate new mixes.

The primary use would be to identify the upstream's original Swupd Format when generating a new Mix. The Format of the upstream, and how many times it has bumped, are needed in order to generate the necessary mixes for upgrading the downstream client of the Mix.

Assuming a new Mix stream is created based on the Public ClearLinux distribution plus some additional bundles (i.e. for a production product), the following steps would be required.

A new production Mix, version 10 Format 1, is made based on the [ClearLinux 18030 which is Format 19 ](https://download.clearlinux.org/update/18030/). When the next Mix is needed, the public [ClearLinux is now at version 19110 which is Format 21](https://download.clearlinux.org/update/19110/); the Upstream Format has bumped 2 times.

One suggested solution is [saving the URL used for the Upstream and the version into files in the Mix when it is created](https://github.com/mdhorn/mixer-tools/commit/d102d77724f5fb958b533774824e41b2477c63b5).
https://github.com/mdhorn/mixer-tools/commit/d102d77724f5fb958b533774824e41b2477c63b5

With that information, the Format of the Upstream can be found:
https://download.clearlinux.org/update/18030/format = 19
Next, the latest release of Format 19 can be determined:
https://download.clearlinux.org/update/version/format19/latest = 18500

So the first new Mix (20; still at Mix Format 1) will need to be based on Upstream's 18500.
The next Mix (30; Mix Format 2) would need to be based on the First release of Format 20:
https://download.clearlinux.org/update/version/format20/first = 18510
And then another Mix (40; Mix Format 2) based on the Last release of Format 20:
https://download.clearlinux.org/update/version/format20/latest = 18930
Next Mix (50; Mix Format 3) based on the First release of Format 21:
https://download.clearlinux.org/update/version/format21/first = 18940

Finally, we can make our last Mix (60; Mix Format 3) based on the choose 19110.

The summary would be:

Upstream Version | Upstream Format | Mix Version | Mix Format
------------ | ------------- | ------------- | -------------
18030 | 19 | 10 | 1
18500 | 19 | 20 | 1
18510 | 20 | 30 | 2
18930 | 20 | 40 | 2
18940 | 21 | 50 | 3
19110 | 21 | 60 | 3

Without having the URL and version the previous Mix was created from, the upgrade path could not be created.

The reason to have the Upstream URL as well as the version is that a Mix could be based on another Mix, not just the public ClearLinux release.

**Comment by cmarcelo** [comment]
Have #31 fixed this issue?

**Comment by cmarcelo** [comment]
@mdhorn has #31 fixed this issue?

**Comment by mdhorn** [comment]
Yes, fixed by PR #31
