### ISSUE TITLE
add '--default-bundles' flag to 'mixer init'

### ISSUE THREAD

**Issue by kevincwells** [clearlinux/mixer-tools#300]
Current State
------------------

Currently, `mixer init` does one of three things:
1. Under normal circumstances, adds the four default bundles (os-core, os-core-update, bootloader, and kernel-native) to your mix.
1. If `--all-upstream` is passed, adds all upstream bundles to your mix. (And/or the niche `--all-local`, for all local bundles, if you already have them at init time.)
1. If the `mixbundles` file already exists, does nothing.

This behavior means people have resorted to creating an empty `mixbundles` file before running `mixer init` just to avoid having the default bundles added. Other users accidentally (or intentionally) had a `mixbundles` file, and expected `mixer init` to add those bundles anyway.

Proposal
------------
Add a new `--no-default-bundles` flag to `mixer init` that defaults to false. If false/omitted, _always_ add those default bundles to the mix bundle list, even if the file already exists. If true/passed, do not modify the list. Behavior of `--all-upstream` would remain unchanged.

**Comment by kevincwells** [comment]
>The only thing I dislike about this proposal is that so far all our flags enable things once you use them. So instead of having --default-bundles default to true, I'd rather have a --no-default-bundles flag that would skip adding those 4 bundles.

That feels a _little_ backward to me, 'cause what you're enabling is the act of _not_ doing something. But at the same time, that's exactly what I did with `mixer bundle edit --supress-editor` -- the default behavior is to do something, and you pass an affirmative flag to skip doing that thing.

I kind of liked that `--all-upstream`, `--all-local`, and `--default-bundles` all described what bundles would be added to the mix. Felt kind of symmetric. Kind of.

I don't have particularly strong feelings either way (an uncommon occurrence for me, I know).

**Comment by rchiossi** [comment]
For all those flags you just call them by name, you don't do `--all-local=true` or `--supress-editor=true`. 

`--default-bundles=false --all-local --all-upstream` looks very asymmetric to me ;)

**Comment by kevincwells** [comment]
> `--default-bundles=false --all-local --all-upstream` looks very asymmetric to me ;)

To be fair, you would never pass `--default-bundles=false` and `--all-upstream` at the same time, as the latter would undo the former... but point taken :wink:

**Comment by kevincwells** [comment]
@rchiossi  -- Updated. I should have just implemented this in the time I've spent on this issue. Then this rename discussion could have happened in the PR comments ;)
