### ISSUE TITLE
EditBundles api needs to be improved.

### ISSUE THREAD

**Issue by icarus-sparry** [clearlinux/mixer-tools#319]
EditBundles from builder/bundles.go has a confusing interface, with 3 bool flags to turn on and off things.

Whilst it has a good godoc comment

    // EditBundles copies a list of bundles from upstream-bundles to local-bundles
    // (if they are not already there) or creates a blank template if they are new,
    // and launches an editor to edit them. Passing true for 'suppressEditor' will
    // suppress the launching of the editor (and just do the copy or create, if
    // needed), and 'add' will also add the bundles to the mix.

if one is looking at the use of this function, e.g. on github the 3 bool flags make it hard to understand.

**Comment by rchiossi** [comment]
This command has been removed from mixer.
