### ISSUE TITLE
New Feature: mixer add-bundles

### ISSUE THREAD

**Issue by kevincwells** [clearlinux/mixer-tools#32]
Introduce new "mixer add-bundles" command to automate the addition of bundles to the mix-bundles/ directory.

Currently adding bundles to your mix means copying them manually from the pulled clear-bundles/clear-bundles-&lt;VER&gt;/bundles/ dir to your mix-bundles/ dir. This is a manual process, and thus following bundle dependencies (i.e., “include (other-bundle)”) is a manual process.

- Tool should accept list of bundles to add as argument
- Tool should pull bundle definitions from clear version specified by .clearversion
- Tool should parse bundle definition file and recursively copy dependency bundles
- Tool should default to skipping already-existent bundles (with warning), and overwrite with flag (--force)
- Tool should allow automatic git commit representing new bundles

This work is in progress and will be in a forthcoming PR.

**Comment by rchiossi** [comment]
In addition to that, it may be nice to also have a "list-bundles" command, that fetches and displays the available bundles for the clear version you are using.

**Comment by kevincwells** [comment]
@rchiossi -- I could see that potentially being useful, but I would see that as a separate command altogether.

The "add-bundles" command moves further in the direction of abstracting away the offline bundle cache (i.e., the user doesn't need to know where it lives or that it even exists in order to add bundles), and so I can see your proposal as a useful addition to that direction. Of course, there are well over 100 bundles in most versions of CLR, so the output would likely only be useful in conjunction with grep/less.

**Comment by kevincwells** [comment]
@mdhorn pointed out that if this is intended to be "the" way you add bundles from CLR to your mix, it really should support an --all flag, so I just submitted a PR (https://github.com/clearlinux/mixer-tools/pull/36) to implement this.
