### ISSUE TITLE
"mixin repo list" should perform "mixin repo init" if user hasn't added a repo

### ISSUE THREAD

**Issue by bktan8** [clearlinux/mixer-tools#323]
If a user hasn't added a repo, "$ mixin repo list" returns: 

     ERROR: stat /usr/share/mix/.yum-mix.conf: no such file or directory

I think it would be nicer if mixin simply performs "init" automatically and return the default repos like this: 

     Clear	https://download.clearlinux.org/releases/$releasever/clear/x86_64/os/
     Local	file:///usr/share/mix/local

**Comment by rchiossi** [comment]
Maybe a nicer error message warning the user that it has not been initialized and that he should run init instead. Just running init in the background can hide other errors (e.g. the user has already ran init, but is now running `mixin repo list` in the wrong folder)

**Comment by matthewrsj** [comment]
@rchiossi I like that idea. A better error message should be printed.

**Comment by tmarcu** [comment]
Needs better error message, I'm not sure I would want to run init without the user wanting to actually call init.
