### ISSUE TITLE
"Certificate verification error: self signed certificate" error occurs after rollback and not performing "swupd clean --all"

### ISSUE THREAD

**Issue by bktan8** [clearlinux/mixer-tools#325]
If you rollback and not perform "swupd clean --all", swupd issues: 

     Certificate verification error: self signed certificate
     WARNING!!! FAILED TO VERIFY SIGNATURE OF Manifest.MoM version 22600000

error messages because the original certificate exists.  

Steps to repo:

assuming clean system (have not rollbacked before)
1) sudo mixin repo add myrepo file:///home/user/mixin-repo/
2) sudo -E mixin package add helloworldb
3) sudo -E mixin build
4) sudo -E  swupd update --migrate
5) sudo -E swupd bundle-list -a
6) sudo -E bundle-add myrepo
-->Everything should work as expected at this point

7) sudo -E swupd verify --fix --picky -m 22600 -C /usr/share/clear/update-ca/Swupd_Root.pem
8) sudo mixin repo add myrepo file:///home/user/mixin-repo/
9) sudo -E mixin package add helloworldb
10) sudo -E mixin build
11) sudo -E  swupd update --migrate
12) sudo -E swupd bundle-list -a
-->Should get certificate verification error now.

13) sudo -E swupd verify --fix --picky -m 22600 -C /usr/share/clear/update-ca/Swupd_Root.pem
14) sudo swupd clean --all
15) sudo mixin repo add myrepo file:///home/user/mixin-repo/
16) sudo -E mixin package add helloworldb
17) sudo -E mixin build
18) sudo -E  swupd update --migrate
19) sudo -E swupd bundle-list -a
-->Should work as expected again.

**Comment by tmarcu** [comment]
Need to implement step 13 as a `swupd rollback `option, which also calls swupd clean --all to make sure we have a good state to go forward with.

**Comment by bktan8** [comment]
@tmarcu - maybe instead of using "rollback" we could use "--clear-cache" because user may "roll forward".

**Comment by reaganlo** [comment]
Closing this as the mixin feature has been removed in [v6.2.2](https://github.com/clearlinux/mixer-tools/releases/tag/v6.2.2)
