### ISSUE TITLE
mixin cannot add package from repo if the "clear" repo is removed

### ISSUE THREAD

**Issue by bktan8** [clearlinux/mixer-tools#326]
If you remove the default "clear" repo, "mixin package add" fails to find and add packages in a private repo.

Steps to repo:
1) mkdir -p /home/user/mixin-repo
2) cp helloworldb* /home/user/mixin-repo
3) cd /home/user/mixin-repo
4) sudo createrepo_c .
5) sudo mixin repo add myrepo file:///home/user/mixin-repo/
6) sudo mixin repo remove clear
7) sudo -E mixin package add helloworldb

Should get:

      Initializing mix version 22600000 from upstream version 22600
      ERROR: no such package

**Comment by reaganlo** [comment]
@bktan8 Can you provide a use-case where you would need to remove the "clear" repo?

**Comment by bktan8** [comment]
@reaganlo - A potential use-case is where the user wants to reduce the list of repos so it takes less time to find package(s) to add a bundle.  

Ultimately - Why should the "clear" repo be required for mixin to work properly?  It's just another repo.  Are there some dependencies in the "clear" repo that are required for mixin to work properly?  If it is, then make it so it can't be removed.  I realize removing the "clear" repo is a corner case, but someone is bound to do it for whatever reason.

**Comment by tmarcu** [comment]
hmm I'm keen on keeping it because unless the user package is incredibly one-off, it will likely require dependencies that are just magically resolved by having the clear repo available to use.In that case I'd rather make this repo non-removable. It can also be edited to point to a fake URL as a workaround @bktan8
