### ISSUE TITLE
Adding more bundle metadata to tracking files

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/mixer-tools#333]
It may be nice for swupd users to query specific information about a bundle. For example, they may want to know the status of a bundle, or its description, maintainer, etc. It could be implemented in swupd-client as a new subcommand (maybe `swupd bundle-info BUNDLE`).

To enable this swupd-client feature, mixer could add extra metadata to the bundle tracking files in `/usr/share/clear/bundles`, and later `swupd bundle-info` could start reading this metadata.

**Comment by matthewrsj** [comment]
Different solution done in #336
