### ISSUE TITLE
New Feature: mixer update-bundles

### ISSUE THREAD

**Issue by kevincwells** [clearlinux/mixer-tools#34]
# New Feature
Add new command to support updating bundle definitions to a new version of CLR.

# Use case
You have already initialized a mix (`mixer init-mix -clearver n -mixver m`) based on some CLR version. You have already pulled bundle definition files into your mix-bundles/ directory (`mixer add-bundles -bundles somebundle`). You have optionally modified any of the bundle definitions, or created your own. You may or may not have done anything else (`mixer build-chroots`, `mixer build-update`, etc.). A new version of CLR is released that adds a new package to one of the bundles you're using (among other potential changes). Now you want to base your next mix on this new CLR version to incorporate that change.
## Currently you have to...
- Manually edit the .clearversion file to the new CLR version number
- Run `mixer get-bundles`
- Manually inspect each and every bundle definition file in your mix-bundles/ directory, diff each with the corresponding file in clr-bundles/clr-bundles-&lt;NEW-VER&gt;/bundles/, and integrate any new content you notice however you see fit.
  - Note: Only if you haven't modified any of the bundle definitions, you could run `mixer add-bundles -bundles <BUNDLE_LIST> -force` with a list of every bundle in your mix-bundles/ directory to override your bundle definitions with the new ones.

This is laborious and error prone.

## Proposal
A new command: `mixer update-bundles` that will take an optional `-clearver` flag indicating what version you want to update to. (If omitted, "latest" is assumed.)

The tool will:
- Fetch the bundle definitions for the new CLR version
- For each bundle in mix-bundles/, check if bundle exists in old CLR definitions (thus ignoring bundles you created from scratch), and if so:
  - Create a patch by diffing the old bundle definition with definition found in mix-bundles/, to record additions/deletions you've made
  - Copy over the corresponding file from clr-bundles/clr-bundles-&lt;NEW-VER&gt;/bundles/ (or error if it is not present), overwriting the current version
  - Apply patch to newly-copied bundle, so your same additions/deletions are made to new bundle
  - Clean up patch file
- For each bundle in mix-bundles/, check for missing included bundles and recursively pull them in. (Note we don't recursively pull includes in until all patching has been completed, as a later patch might remove the include.)
- Update the .clearversion file
- Optionally (if `-git` is passed), add new git commit in mix-bundles/ directory.
- Optionally (if `-prune` is passed), clean up old CLR version bundle definition files. 

> Note: There is a corner case that can result in a dangling, unneeded bundle definition file in your mix-bundles/ directory. If an old bundle definition file previously included another bundle, but that include was removed in the new version of the definition file, and that included bundle still exists in the new verison of CLR, it will be left in your mix-bundles/ direcotry, as there is no way to know if it exists there due only to an include or you manually adding it. (If it does not exist in the new version of CLR, the tool will error out saying you have a bundle that no longer exists.)

**Comment by kevincwells** [comment]
If I understand correctly, this functionality would be needed to successfully automate format bumps, too.

Hypothetical example numbers:

CLR Format | CLR Version | Mix Version
--------- | ----------- |  ----------
10 | 100 | 10
10 | 110 | 10
11 | 120 | 10
11 | 130 | 10
11 | 140 | 10
12 | 150 | 10
12 | 160 | 10
12 | 170 | 20

Mix was originally based on upstream CLR version 100. Now you want to do a new mix, and meanwhile CLR has bumped multiple formats in addition to versions.

If I understand correctly, you cannot just jump from 100 to 170, becaues of the format bumps.  And to do the format bumps to get from CLR version 100 to CLR version 170, you'd need to update your bundle definitions in this way for each of the format bump builds you do, right? So you'd need to update your bundle definitions from 100 to 110/120, then again from 120 to 140/150, and then again from 150 to 170, right?

In a world where mixes only ever contain a subset of standard CLR bundles, updating bundle definitions is likely as easy as replacing each of the bundle files you have with the corresponding one from upstream. But when you consider that those bundle definitions can be altered or added to, that's when you need logic like I'm proposing here.

**Comment by cmarcelo** [comment]
+1 for the proposal, I think you should move forward trying to implement this.
@tmarcu do you have any specific feedback?

@kevincwells, a few comments:
- After that update step happen, automatically dump the diff of what changes were made.
- How do I recursively pull the bundles for the first use? I'm thinking about the sequence: init-mix, add my new bundle with includes(desktop), but I don't have desktop yet.
- I initially thought about a slightly different approach (being able to request without describing the contents of a bundle from upstream), but is something can be explored later on.

**Comment by cmarcelo** [comment]
> If I understand correctly, you cannot just jump from 100 to 170, becaues of the format bumps.

Correct.

> And to do the format bumps to get from CLR version 100 to CLR version 170, you'd need to update your bundle definitions in this way for each of the format bump builds you do, right?

Well, that depends. If your intention is to follow a bundle from upstream, then yes. This is one place where the slightly different approach I mentioned in other comment shines, you don't need to stop the mixing at some point just because the user needs to update the bundles ;-)

> So you'd need to update your bundle definitions from 100 to 110/120, then again from 120 to 140/150, and then again from 150 to 170, right?

I think so.

> In a world where mixes only ever contain a subset of standard CLR bundles, updating bundle definitions is likely as easy as replacing each of the bundle files you have with the corresponding one from upstream. But when you consider that those bundle definitions can be altered or added to, that's when you need logic like I'm proposing here.

Correct. One approach would be to teach update-bundles how to stop at the right boundary (and explain why it did). So I can do a sequence of update-bundles + <rest of update>.

**Comment by kevincwells** [comment]
@cmarcelo re your comments:
- Do you mean you'd like the changes being made to the bundles to be output to the user? I could see this being output at a debug log level, but I wouldn't want to flood the user with diffs in general.
- `mixer add-bundles` recursively pulls the includes of the bundles you bring over from the CLR bundles. You're asking, if you create _your own new_ bundle, how do you recursively pull in the includes you mention in it? I implemented `mixer add-bundles` with the bundle include parsing pulled out into a separate `GetIncludedBundles` helper, which would be easy to reuse for a use case like this. I'm not sure `update-bundles` is the right place to put that functionality, but I definitely agree it would be a useful feature to have. I have considered a `mixer check-bundle` command for linting; I could see it fitting into here, maybe.
- Don't quite follow your different approach, but I'm definitely open to ideas.

**Comment by cmarcelo** [comment]
> Don't quite follow your different approach, but I'm definitely open to ideas.

Imagine we teach mixer about a file called UPSTREAM_BUNDLES, that contains a list of bundles from upstream that we want to use "as is" (note: we do modify manually os-core / os-core-update, but the packages included are the same).

When doing init-mix, we create this file with os-core, os-update (whatever defaults we have). When building (chroots/updates), mixer will consider all the bundles we defined plus download the ones listed in UPSTREAM_BUNDLES.

If the user want to replace the definition of a bundle, it can download the file and add to it, but now is clearly manually maintained. We can have tooling to help downloading and updating those files, kind of along the lines you mentioned.

Note: this is the approach we've been taking in the mix me/Mark/Murilo are working.

**Comment by cmarcelo** [comment]
> You're asking, if you create your own new bundle, how do you recursively pull in the includes you mention in it?

It was more a suggestion to look at those "related" usages and see if the solution still looks good.

**Comment by kevincwells** [comment]
@cmarcelo -- ooooh. Yes, @rchiossi and I have discussed the possibility of what we were calling "remote bundles" that would work exactly like that -- the ability to list some bundles as pulled directly from upstream, without modification. Then the only bundle definitions you actually keep locally are those that are modified or original. 

I fully support this direction, and it is part of the future changes to mixer I envision, but it's a pretty big overhaul to how the system works right now, and thus I did not consider it for this. Much discussion with @tmarcu and crew is needed.

**Comment by tmarcu** [comment]
Handled internally by mixer now w/init.

**Comment by kevincwells** [comment]
This is outdated, but the concept here is still needed as part of automatic format bumps, and the basis of the implementation suggested is still applicable.

**Comment by reaganlo** [comment]
Handled internally by mixer now w/init.
