### ISSUE TITLE
mixin: Unable to make subsequence mix after first one

### ISSUE THREAD

**Issue by bktan8** [clearlinux/mixer-tools#340]
On an upstream Clear version (22850), I made a mix with one package, migrated, and successfully installed my bundle.  Then I tried to make a 2nd mix, but I get this error when building:

* Verified upstream Manifest.MoM
ERROR: open /usr/share/mix/update/www/22850000/Manifest.MoM: no such file or directory

**Comment by matthewrsj** [comment]
This seems related to #347?

**Comment by bktan8** [comment]
Looks like the same.  I'll close this one.
