### ISSUE TITLE
mixin: Would like ability to migrate to local mix without being forced to upgrade if there's a newer upstream version

### ISSUE THREAD

**Issue by bktan8** [clearlinux/mixer-tools#341]
If I make a local mix, using version 22640 for example, I would like the ability to migrate to just the mixed version (e.g. 22640000).  I don't want my mix to be upgraded if there's a newer version upstream.

**Comment by reaganlo** [comment]
Closing this as the mixin feature has been removed in [v6.2.2](https://github.com/clearlinux/mixer-tools/releases/tag/v6.2.2)
