### ISSUE TITLE
mixin: failed to migrate to custom mix

### ISSUE THREAD

**Issue by rebeccasf** [clearlinux/mixer-tools#343]
$ sudo -E swupd update --migrate
Attempting to migrate to your mix content...

Update started.
Preparing to update from 22880 to 22880000
Warning: hash check failed for Manifest.os-core for version 22880000. Deleting it.
Warning: Removing corrupt Manifest.os-core artifacts and re-downloading...
Downloading packs...
        ...100%

Statistics for going from version 22880 to version 22880000:

    changed bundles   : 1
    new bundles       : 0
    deleted bundles   : 0

    changed files     : 3998
    new files         : 0
    deleted files     : 0

Starting download of remaining update content. This may take a while...

Finishing download of update content...
Staging file content
File staging failed: /usr/share/clear/version
Calling post-update helper scripts.
double free or corruption (fasttop)
Aborted

**Comment by tmarcu** [comment]
@rebeccasf Thanks for opening this, but after looking at it the bug is coming from swupd-client actually. I'm going to close this and opened it in the client repo instead: https://github.com/clearlinux/swupd-client/issues/480
