### ISSUE TITLE
An invalid bundle name is still added to an image during "mixer build image" 

### ISSUE THREAD

**Issue by bktan8** [clearlinux/mixer-tools#365]
Even though the warning message says an invalid bundle is being skipped, the bundle name still shows up when you do "swupd bundle-list" for the created image.

Example:
clear@clr-da50329d227d4062bb2170a8b8162bd2 ~/mixer $ sudo -E mixer build image
Password: 
Reading configuration
Validating configuration
Creating virtual disk
Creating partitions
Mapping loop device
Creating file systems
Setting up mount points
Starting swupd. May take several minutes
Installing 4 bundles (and dependencies)...
.
....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Verifying version 10
**Warning: Bundle "BADBUNDLE" is invalid, skipping it...**
Downloading packs...

**Comment by reaganlo** [comment]
@bktan8 As discussed, the ideal fix for this is in the "ister" application. Just so that we don't lose sight of this issue, it would be great if you could log an issue in the "ister" repo and close this one.

**Comment by bktan8** [comment]
I've filed an issue with the ister repo.  https://github.com/bryteise/ister/issues/155.
