### ISSUE TITLE
Add zstd compression support

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/mixer-tools#366]
Currently, fullfile creation supports gzip, bzip2, and xz compression types. It would be nice to add zstd support, since it tends to produce smaller files in general and decompression speed is excellent. It would worth seeing how well zstd compresses packs too; zstd might be nice replacement (or a configurable replacement) for xz when compressing packs.

**Comment by matthewrsj** [comment]
Can't do that until swupd-client supports it, and right now swupd-client can't support it until libarchive makes a new release with zstd support.

**Comment by tmarcu** [comment]
Zstd has been added to delta pack creation; should we consider adding it to the rest in the near future?

**Comment by aaronovz1** [comment]
Any chance this work might move up the priority? The benchmarks on zstd are impressive and would be beneficial to IoT projects updating over low bandwidth 3G connections.

**Comment by rchiossi** [comment]
I'll keep that in mind and try to squeeze it in our planning, but I can't make any promises right now on when this will actually hit a release.

**Comment by aaronovz1** [comment]
Is there a public roadmap available? This ticket and #578 are useful to my project but I'm not sure where they currently sit in the plan and what time frame I'd be looking at.

**Comment by rchiossi** [comment]
Sadly no. Right now we have internally a broad planning that lists the main features and changes that need to be integrated, but it is not granular to issue # level.
But I have to say that posting a reminder on a feature that is important to your workflow does help bring attention to it and indirectly bump its priority.

**Comment by aaronovz1** [comment]
Ok thanks. I just didn't want to come off too pushy by bumping issues. If I was able to spend more time learning the codebase I might have gone the route of doing a pull request, but I am pretty strapped for time as well and Go isn't my forte.

**Comment by reaganlo** [comment]
This has been implemented in commit https://github.com/clearlinux/mixer-tools/commit/68eecc1ba2580001ca3f046a69e490ef67632116
