### ISSUE TITLE
mixin: Wrong version number used to build updated mix when migrating

### ISSUE THREAD

**Issue by bktan8** [clearlinux/mixer-tools#367]
Scenario: My upstream version is 23650.  I created a mix 2365000.  Then I migrate.  The latest upstream version is 23680.   During the migrate, (according to design) it's supposed to recreate a mix using the latest , but it's using the initial upstream version + 10.  A little confusing...

here's the message:
**Creating bundles for version 23650010 based on Clear Linux 23680**

Here's the log:

clear@10.54.69.230 ~ $ sudo mixin build
Directory walk started
Directory walk done - 0 packages
Temporary output repo path: ./.repodata/
Preparing sqlite DBs
Pool started (with 5 workers)
Pool finished
Generating certificate for signature validation...
Building bundles...
=> BUILD BUNDLES
Creating bundles for version 23650000 based on Clear Linux 23650
Preparing new /usr/share/mix/update/image/23650000
  and dnf config: /usr/share/mix/.yum-mix.conf
Packager command-line: dnf --config=/usr/share/mix/.yum-mix.conf -y --releasever=23650
Resolving packages using 2 workers
processing helloclear-bundle
processing os-core
... done with helloclear-bundle
... done with os-core
Resolving files using 2 workers
processing helloclear-bundle
processing os-core
Bundle os-core	3292 files
Bundle helloclear-bundle	260 files
Cleaning DNF cache before full install
Installing all bundles to full chroot
[1/2] os-core
... building special os-core content
... Adding swupd default values to os-core bundle
[2/2] helloclear-bundle

TIMINGS
  BUILD BUNDLES 9.113s
TOTAL: 9.113s
=> CREATE MANIFESTS
[1/3] helloclear-bundle
[2/3] os-core
[3/3] full
MoM version 23650000
- helloclear-bundle    23650000
- os-core              23650000
- os-core-update-index 23650000
Signing manifest.
Compressing Manifest.MoM
Compressing bundle manifests
  helloclear-bundle
  os-core
  os-core-update-index
  full

=> CREATE FULLFILES
Using 2 workers
- Already created: 0
- Not compressed:  0
- Compressed
  - external-gzip        1085
  - external-bzip2       127
  - gzip                 315
  - external-xz          1039
Total fullfiles: 2566

=> CREATE ZERO PACKS
Creating zero pack for helloclear-bundle to version 23650000
  Fullfiles in pack: 2
  Deltas in pack: 0
Creating zero pack for os-core to version 23650000
  Fullfiles in pack: 2561
  Deltas in pack: 0
Creating zero pack for os-core-update-index to version 23650000
  Fullfiles in pack: 5
  Deltas in pack: 0
Saving the upstream URL: https://download.clearlinux.org
Saving the upstream version: 23650
Setting latest version to 23650000

TIMINGS
  CREATE MANIFESTS  1.302s
  CREATE FULLFILES  33.168s
  CREATE ZERO PACKS 24.342s
TOTAL: 58.813s
* Verified upstream Manifest.MoM
Successfully built mix content
clear@10.54.69.230 ~ $ sudo swupd update --migrate
Attempting to migrate to your mix content...

Update started.
NEW CLEAR AVAILABLE 23680
Directory walk started
Directory walk done - 0 packages
Temporary output repo path: ./.repodata/
Preparing sqlite DBs
Pool started (with 5 workers)
Pool finished
Building bundles...
=> BUILD BUNDLES
Creating bundles for version 23650010 based on Clear Linux 23680
Preparing new /usr/share/mix/update/image/23650010
  and dnf config: /usr/share/mix/.yum-mix.conf
Packager command-line: dnf --config=/usr/share/mix/.yum-mix.conf -y --releasever=23680
Resolving packages using 2 workers
processing os-core
processing helloclear-bundle
... done with helloclear-bundle
... done with os-core
Resolving files using 2 workers
processing helloclear-bundle
processing os-core
Bundle helloclear-bundle	260 files
Bundle os-core	3297 files
Cleaning DNF cache before full install
Installing all bundles to full chroot
[1/2] helloclear-bundle
[2/2] os-core
... building special os-core content
... Adding swupd default values to os-core bundle

TIMINGS
  BUILD BUNDLES 11.061s
TOTAL: 11.061s
=> CREATE MANIFESTS
[1/3] os-core
[2/3] helloclear-bundle
[3/3] full
MoM version 23650010
- helloclear-bundle    23650000
- os-core              23650010
- os-core-update-index 23650010
Signing manifest.
Compressing Manifest.MoM
Compressing bundle manifests
  os-core
  os-core-update-index
  full

=> CREATE FULLFILES
Using 2 workers
- Already created: 0
- Not compressed:  0
- Compressed
  - external-bzip2       11
  - external-gzip        15
  - external-xz          16
  - gzip                 1
Total fullfiles: 43

=> CREATE ZERO PACKS
Zero pack already exists for helloclear-bundle to version 23650000
Creating zero pack for os-core to version 23650010
  Fullfiles in pack: 2564
  Deltas in pack: 0
Creating zero pack for os-core-update-index to version 23650010
  Fullfiles in pack: 5
  Deltas in pack: 0
Saving the upstream URL: https://download.clearlinux.org
Saving the upstream version: 23680
Setting latest version to 23650010

TIMINGS
  CREATE MANIFESTS  1.297s
  CREATE FULLFILES  484ms
  CREATE ZERO PACKS 24.268s
TOTAL: 26.05s
* Verified upstream Manifest.MoM
Successfully built mix content
Checking manifest uniqueness...
Preparing to update from 23650 to 23650010
Downloading packs...

Extracting cockpit pack for version 23680
	...6%
Extracting dev-utils-dev pack for version 23670
	...10%
Extracting kernel-native pack for version 23670
	...26%
Extracting libX11client pack for version 23670
	...32%
Extracting mail-utils-dev pack for version 23670
	...36%
Extracting network-basic-dev pack for version 23670
	...51%
Extracting os-core-dev pack for version 23680
	...53%
Extracting os-core-update-dev pack for version 23670
	...57%
Extracting os-installer pack for version 23670
	...59%
Extracting package-utils pack for version 23680
	...73%
Extracting storage-utils pack for version 23670
	...77%
Extracting storage-utils-dev pack for version 23670
	...79%
Extracting sysadmin-basic pack for version 23670
	...83%
Extracting sysadmin-basic-dev pack for version 23670
	...85%
Extracting vim pack for version 23670
	...100%

Statistics for going from version 23650 to version 23650010:

    changed bundles   : 18
    new bundles       : 0
    deleted bundles   : 0

    changed files     : 3735
    new files         : 1513
    deleted files     : 1507

Starting download of remaining update content. This may take a while...
	...100%
Finishing download of update content...
Staging file content
Applying update
	...100%
Update was applied.
Calling post-update helper scripts.
none
systemd-udevd.service: needs a restart (a library dependency was updated)
systemd-journald.service: needs a restart (a library dependency was updated)
systemd-resolved.service: needs a restart (a library dependency was updated)
systemd-timesyncd.service: needs a restart (a library dependency was updated)
Update took 69.1 seconds
Update successful. System updated from version 23650 to version 23650010
clear@10.54.69.230 ~ $ sudo swupd check-update
Current OS version: 23650010
There are no updates available

**Comment by reaganlo** [comment]
Closing this as mixin feature has been removed in [v6.2.2](https://github.com/clearlinux/mixer-tools/releases/tag/v6.2.2)
