### ISSUE TITLE
Add a --no-clean option for build bundles

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/mixer-tools#376]
Such an option would be useful to allow users to mount a block device with ister in the full image/chroot directory mixer makes during the build bundles operation.  This can be used to allow users to prototype bootable images very quickly if many need prototyped at once because it avoids needing to copy the full image/chroot into a block device and then remove it after the block device is unmounted.

**Comment by matthewrsj** [comment]
But the full chroot sticks around. What are you asking not to clean?

**Comment by tmarcu** [comment]
@matthewrsj when build bundles is called, it wipes update/image/VER no matter what. His use case is specific to some custom testing to already have image/VER/full created, and mount the image to full, so mixer automatically populates the VM filesystem as part of the build. Saves some time copying into the image after building & don't have to wipe /full after to save space from having it in 2 places (workspace + vm).

**Comment by gtkramer** [comment]
Saves time and disk I/O when I already have a guarantee of a clean environment.  It's more of an advanced usage option only for folks who know what they are doing.
