### ISSUE TITLE
Add exclude-pkgs option action to repo command

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/mixer-tools#377]
For prototyping environments, want to mimic the behavior of koji where if one package updates, it substitutes the existing package (and all of its sub packages).  This allows a proper integration to take place.  This is a dnf config option that can be added per-repo.  Such a CLI may look like:

mixer repo exclude-pkgs clear <pkg list, separated by space or comma>

Really only useful after a user has already done a:

mixer repo add dev <pkg repo url>

**Comment by tmarcu** [comment]
I think this should be handled by case-by-case basis and just manually updated in the dnf conf if it has to persist. Another option would be to possibly pass it to the internal dnf call in mixer as --exclude=<list of packages entered on command line>

so your mixer calls would then look like

mixer build bundles --exclude=pkg1 pkg2 pkg3...pkgN

But idk if this is persistent it'd be easier to just 
sed -i 's/\[reponame\]/\[reponame\]\nexclude=pkg1 pk2 pk3/' dnf.conf

**Comment by tmarcu** [comment]
merged in 5.1.0
