### ISSUE TITLE
Mixer still checks online when --offline is passed to build bundles

### ISSUE THREAD

**Issue by tmarcu** [clearlinux/mixer-tools#378]
Don't check online when --offline is passed...

**Comment by kevincwells** [comment]
Unless it's changed since I introduced it, `--offline` only prevents mixer from pulling upstream bundle definitions. It's a short-circuit early return in the fetch function. What other network calls is mixer making that you're trying to prevent?

**Comment by tmarcu** [comment]
#398 Merged and released,
