### ISSUE TITLE
Mixer.state is overwritten if it already exists

### ISSUE THREAD

**Issue by tmarcu** [clearlinux/mixer-tools#379]
We need to do an os.Stat() and never overwrite the file if it already exists.

**Comment by icarus-sparry** [comment]
No, never do it this way. Instead give the correct flags to open so the open fails if the file already exists. This avoids a race condition.

Probably something like

     f, err := os.OpenFile("Mixer.state", os.O_EXCL | os.O_CREATE | os.O_WRONLY, 0644)

**Comment by rchiossi** [comment]
This file is meant to be overwriten over and over. It is a state file afteral! But I assume you meant overwriten on initialization, which indeed should never happen.

The current code looks just like what @icarus-sparry suggested:
```     f, err := os.Open(state.filename)
    if err != nil {
        // If state does not exists, create a default state
        return state.Save()
    }
```

The issue is probably somewhere else then,

@tmarcu Do you have more details on which scenario is it being overwritten?

**Comment by tmarcu** [comment]
@rchiossi sorry I was not detailed enough, just read my mind next time x) 
Yes - the case is the file is being overwritten during` mixer init `(bad), and also overwritten during `mixer bundle add` (double bad). So it had to be re-set manually before calling build bundles otherwise it would keep trying to pull the latest from builder.conf (or in this case, the system since builder.conf did not have FORMAT).

It should only ever be edited by an internal build command, i.e format bump, or by manual user intervention if it already exists.

**Comment by tmarcu** [comment]
The scenario here is we already have a mixer.state file with FORMAT = 1, but it kept overwriting it with format 25 because that's what the system was on, even though the state file existed.

**Comment by rchiossi** [comment]
I never expected mixer init to be called on a directory with a state file... It the state file exists, then this directory should already be an initialized mix.
I just tested with bundle add and it gave me a warning but did not overwrite the file. The warning shouldn't be there, so I'll take a look into it.

**Comment by tmarcu** [comment]
Closing as calling init multiple times should technically re-init the workspace as it currently is. Bundle add is not the culprit of this behaviour.
