### ISSUE TITLE
mixer runs in docker container?

### ISSUE THREAD

**Issue by shrmrf** [clearlinux/mixer-tools#382]
Hi!  

I've been using the `mixer` tooling without problem for some days. Today I ran `sudo swupd update` and I got a new version of mixer: `Mixer 5.0.1`

This really doesn't work. Whatever was building before now doesn't as this command tries to run mixer inside of a docker container. Is this the new default behavior? Is there some way to override this and have the same behavior as `Mixer 4.7.0`? I'm running `mixer` inside of a VM. But this will probably break if I were using the `clr-sdk` docker container..

**Comment by rchiossi** [comment]
You can use the - -native flag to run outside the container, but be aware that you may stumble on compatibility issues (e.g. When crossing format boundaries)

**Comment by shrmrf** [comment]
Hey, thanks @rchiossi ... How is the `clr-sdk` docker container going to be affected by it? 

Can the `--native` config be changed so it's the default? Also, [`docker` isn't part of the `os-clr-on-clr` bundle](https://github.com/clearlinux/clr-bundles/blob/master/bundles/os-clr-on-clr) it seems... Furthermore, if you have a proxy, `docker` doesn't work out of the box (we need to do some configurations... Further furthermore, if the org has a local DNS, it needs to be configured... Also, installing `containers-basic` bundle doesn't automagically `enable/start` the `docker.service`... 

Mixer used to be easier back in the day especially on VMs.

In summaray, using `docker` might not be the most ergonomic solution.

**Comment by kevincwells** [comment]
As far as the bundle dependencies not being present, I thought `docker` would have been added to the `mixer` bundle prior to this release. Sorry about that! I know it is in the backlog of tasks and will be updated soon.

**Comment by shrmrf** [comment]
Hey @kevincwells thanks for the detailed response. And I agree that it all makes a lot of sense now!!

- I was (as I alluded,) trying to run this inside [a Virtualbox VM (using `vagrant`)](https://github.com/AntonioMeireles/ClearLinux-packer). 

- I would like to point out again that `docker.service` isn't started if you install the `containers-basic`. And behind corporate proxies (like the ones you'd have at Intel) and DNS configurations is non-trivial for the beginner (who's looking for a quickstart). 

- And the manpages and `--help` arg needs to be updated still :)

I had also thought about the `docker.sock` trick but haven't tried it yet. 

Thanks again!!

**Comment by rchiossi** [comment]
@shrmrf Doesn't `--native` show up when you run `mixer build --help` ? I'm pretty sure it's been in there for a while now. This flag was not part of the 5.0 release.

**Comment by shrmrf** [comment]
@rchiossi maybe it does... I might have overlooked, sorry.
