### ISSUE TITLE
Generic docker errors after upgrading to mixer 5.0.1

### ISSUE THREAD

**Issue by mpurzynski** [clearlinux/mixer-tools#383]
This is a blocker for me, I cannot build custom mixes anymore.

I'm trying to rebuild my mix

# mixer build all

Warning: Using Format=1 from mixer.state for this build.
Running command in container: "mixer build all"
**docker: invalid reference format.**
See 'docker run --help'.
ERROR: Failed to run command in container: failed to execute docker run -i --network=host --rm --workdir /home/clr/mix --entrypoint mixer -v /home/clr/mix:/home/clr/mix :25 build all --native: exit status 125

There is a space between the word mix and the :25 so I tried running it manually, without a space

docker run -i --network=host --rm --workdir /home/clr/mix --entrypoint mixer -v /home/clr/mix:/home/clr/mix:25 build all --native
Unable to find image 'build:latest' locally
docker: Error response from daemon: pull access denied for build, repository does not exist or may require 'docker login'.
See 'docker run --help'.

**Comment by shrmrf** [comment]
@mpurzynski welcome to my world :) as discussed in https://github.com/clearlinux/mixer-tools/issues/382 

What I've settled at doing for now (in my current state) is to force the version of Clear Linux (with the version of `mixer` I'm happy with)...

```
swupd verify --force -f -m 23970 # or whatever version you were happy with previously
```

**Comment by rchiossi** [comment]
I can reproduce on my end, I'm looking into this issue.

**Comment by kevincwells** [comment]
@mpurzynski -- I can definitely understand why you'd interpret that as a erroneous space between `mix` and `:25`. What's actually going on is the code concatenates the value of `DOCKER_IMAGE_PATH` (from the config) with the correct format version tag -- that _should_ be reporting "`clearlinux/mixer:25`" for you. Apparently the default value for `DOCKER_IMAGE_PATH` in the config got messed up in the latest config change?

In the meantime, please set `DOCKER_IMAGE_PATH` to "`clearlinux/mixer`" in your config.

**Comment by rchiossi** [comment]
The issue is a missing thefault value when you initialize a new mix. For existing mixes, the fix is simple: Open builder.conf and change `DOCKER_IMAGE_PATH = ""` to `DOCKER_IMAGE_PATH = "clearlinux/mixer`

I'm writing a patch to fix the default initialization.

**Comment by rchiossi** [comment]
Hmm, there is more to it than I expected. I suggest running with `--native` until next minor release. I'll update this issue when the PRs get integrated.

**Comment by mpurzynski** [comment]
There must be something more to it, indeed. I tried setting the docker image path to clearlinux/mixer and that image got fetched correctly


Warning: Using Format=1 from mixer.state for this build.
Running command in container: "mixer build all"
Unable to find image 'clearlinux/mixer:25' locally
25: Pulling from clearlinux/mixer
a496bbd67f46: Pull complete 
afb45c7a782d: Pull complete 
Digest: sha256:7a6f6ea2b7ac712303ff8ac9266063294e959534defdde224a4b4a99f63f8755
Status: Downloaded newer image for clearlinux/mixer:25
ERROR: Missing required field in config file: FORMAT
ERROR: Failed to run command in container: failed to execute docker run -i --network=host --rm --workdir /home/clr/mix --entrypoint mixer -v /home/clr/mix:/home/clr/mix clearlinux/mixer:25 build all --native: exit status 1


Now that is a surprise, if FORMAT still needed in the builder.conf? I just removed it, following warnings that the format version from mixer.state will be used instead.

Just for a test, I added FORMAT=1 back under the [swup] section in my builder.conf

I think it's building now.

**Comment by rchiossi** [comment]
Yeah. For some reason our docker image didn't get updated. It is still running an older version of mixer that does not understand either the TOML config or the new mixer.state. We are looking into it.

**Comment by shrmrf** [comment]
I can also replicate the issue @mpurzynski stated at the top...

I'm going `--native` (or older version) for now... Is this the issue that I should track for an update on the fix?

**Comment by kevincwells** [comment]
@shrmrf  Yeah, we'll post here when it's updated. I just built a new container, and @rchiossi is validating it now, so it shouldn't be long. (Assuming that that does indeed fix it, anyhow)

**Comment by mpurzynski** [comment]
Warning: Using Format=1 from mixer.state for this build.
Running command in container: "mixer build all"

(cool, looks like the new image has a correct version of mixer)

A new version of my mix has built without any issues. Thanks!

**Comment by shrmrf** [comment]
congrats @mpurzynski I'm on my way to the office where I'll check the new version out.

**Comment by rchiossi** [comment]
@shrmrf Did you try setting up the docker daemon to use a https proxy?(https://docs.docker.com/config/daemon/systemd/#httphttps-proxy)

Let me know if it solves the issue.

This seems to be very setup specific and I'd rather keep it tied to docker setup than to mixer use. That being said, I'm thinking about things that could be done to make the user life easier when they stumble on that issue (like having a better and more informative error message).

**Comment by shrmrf** [comment]
@rchiossi yup. I had already configured the docker daemon to use http/https proxies. These are proxies for the docker daemon and are not passed down _into_ the containers.

No, I think it's definitely not setup specific. We have to be able to pass the `--env HTTP_PROXY=$http_proxy` somehow.. It probably can be done safely and silently within the `mixer` command.

Or, what would you suggest is the alternative?

**Comment by rchiossi** [comment]
@shrmrf  You are right. I expected docker daemon to pass down the proxy config to the clients, but it seems the way to go on current docker version is to add it to config.json. We can also use the old way like you mentioned by setting `--env HTTPS_PROXY=...`, but both cases will need to be set to user defined values which is what I wanted to avoid.
Adding an option to pass the proxy during `mixer build` is a bad idea in my opinion, since it requires knowledge from the user that this is the stage where the proxy is relevant. Adding a proxy option to builder.conf seems equally bad since it will only be used for the operations inside docker, not for the other network related features of mixer.
I believe our best option here is to read the user environment and propagate the `HTTPS_PROXY` var to docker.
@tmarcu any inputs?

**Comment by shrmrf** [comment]
@rchiossi I think propagating both `http_proxy` and `https_proxy` (non-case sensitive) silently is a good option to explore. Not be very Golang but rather Ruby-ish.

**Comment by tmarcu** [comment]
Proxy environments are too ephemeral & user specific, I don't think it's a good idea to hardcode passing them in TBH, and especially not silently. Using an autoproxy discovery setup removes the need to define any environment variables & mixer runs with no problems, see -> redsocks or pacdiscovery which we provide in Clear.

**Comment by shrmrf** [comment]
@tmarcu can you elaborate further on why you think they're "too ephemeral and user specific"? 

>I don't think it's a good idea to hardcode passing them in TBH, and especially not silently.

I don't see what a possible disadvantage of passing them through is? If they're not defined, they don't have any affect and if they _are,_ they're passed without the user having to be explicit.

**Comment by tmarcu** [comment]
@shrmrf I'm happy to review and discuss PRs submitted to mixer from anyone :slightly_smiling_face: 
Are you still running this in a clr-sdk container?

**Comment by shrmrf** [comment]
@tmarcu sure!! I'll see if I can submit a PR tomorrow..

No, I'm running [Clearlinux inside a Virtualbox VM](https://github.com/AntonioMeireles/ClearLinux-packer) at the moment but the goal is to use the `clr-sdk` (or a modified/fixed version of it) again. I guess `--native` is my best bet. 

Our IT only supports Ubuntu 16.04 (custom proxy, custom dns) at the moment. I've fixed Mixer's version to `4.7.0` at this point (don't recall the Clear OS version atm)... So, Docker would be really nice and I think `--native` should work just fine.

**Comment by kevincwells** [comment]
@rchiossi the proxy configurations in Docker's `config.json` file exclusively deal with the daemon's network interactions, like its connections to registries for pulling images; it does not impact the networking configuration of containers themselves. The `--env` option to `docker run` sets the _container's_ environment.

I too am opposed to the idea of trying to silently, automatically infer the host system's proxy configuration and pass it on to the container. Having worked behind proxies for many years, I know there are many ways people handle proxies, and my biggest issue is simply a matter of trying to create a one-size-fits-all solution. Odds are we'll just create inconsistent and hard-to-debug behavior.

**Passing arbitrarily-set data in to the `docker run` command _does_ pose actual risk, too.** Consider the following scenario:
```bash
export HTTP_PROXY="something -v /some/path:/container/path --entrypoint /usr/bin/nano"
docker run --rm -it --env HTTP_PROXY=$HTTP_PROXY clearlinux/mixer:25
```
If you try the above steps, docker will indeed automatically run nano and, worse, mount an arbitrary path on the host to the container. Now imagine if someone maliciously set it to something else; the process running in the container runs as root, so it'd be easy to construct a damaging payload. We went through significant effort to ensure that mixer will only mount directories to which the running user has read/write access, but an injected mount like this would circumvent those checks. Whitelist filtering the variable would be error prone and finicky.

I think the best solution is @tmarcu's suggestion to run a `redsocks`-type solution that removes the need for configuring the proxies of individual processes.

**Comment by shrmrf** [comment]
I can't agree more with what you wrote here @kevincwells .. This does pose a security risk!!

I guess it's `--native` at least for now then.

**Comment by shrmrf** [comment]
BTW, where can I find the Dockerfile for the `clearlinux/mixer:25` container?

**Comment by rchiossi** [comment]
@kevincwells I was not referring to the daemon config, I was referring to the client config as desbribes here: https://docs.docker.com/network/proxy/

**Comment by rchiossi** [comment]
@shrmrf btw, can you test setting your client proxy in the config as mentioned in method 1 in the link above and check if it works?

**Comment by shrmrf** [comment]
@rchiossi thanks!! I hadn't realized there was a way to pass proxy variables by _default_ into containers when you run them. I'll check it out tomorrow at work and let you know.

Thanks again guys!!! 🙌

**Comment by tmarcu** [comment]
@shrmrf we're actually in the process of having these specific mixer containers become part of regular release artifacts (vs. us manually making & pushing them up), and putting the necessary bits in place right now. I'll send you the information once it's setup on our side

**Comment by shrmrf** [comment]
@tmarcu and team, thanks for all the help. 

I just checked and the `mixer` command works well for me after adding `clearlinux/mixer` as mentioned by @kevincwells (https://github.com/clearlinux/mixer-tools/issues/383#issuecomment-409026649)

Thanks all!!

**Comment by shrmrf** [comment]
I see the `DOCKER_IMAGE_PATH` configuration has been populated in `builder.conf` in the latest release (`24120`)!! 

Cool.

**Comment by tmarcu** [comment]
Since it's in the wild now with that release, will close this issue. Please re-open or set new ones up with any issues that follow from this if you still get any problems!

**Comment by kevincwells** [comment]
> @rchiossi I was not referring to the daemon config, I was referring to the client config as described here: https://docs.docker.com/network/proxy/

Oh wow, you can do that now? Thanks for pointing me to that!!!
