### ISSUE TITLE
mixer init --offline returns an error

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/mixer-tools#386]
I want to use mixer with local bundles only, so I tried running `mixer init --offline`, but it returned an error:

```
$ mixer init --offline
Creating new builder.conf configuration file...
Initializing mix version 10 from upstream version 24180
ERROR: Cannot find bundle "os-core" in local or upstream bundles
```

**Comment by phmccarty** [comment]
This is starting from a clean workspace, by the way.

**Comment by phmccarty** [comment]
@matthewrsj just suggested that I try `mixer init --offline --no-default-bundles`, and that worked. Maybe `--no-default-bundles` should be an implied setting in this case?

**Comment by tmarcu** [comment]
I agree it should be implied on that setting, but in all other cases it doesn't make sense to try to init a workspace offline since it relies on bundles being available :P will update this ty!
