### ISSUE TITLE
Mixer creates mixer.state file when it shouldn't

### ISSUE THREAD

**Issue by tmarcu** [clearlinux/mixer-tools#388]
Just running `mixer` will automatically create a mixer.state file in the running directory.

**Comment by rchiossi** [comment]
Do we want to support custom path for mixer state or do we use the same path as builder.conf?
The original design assumed the directory where mixer runs should hold the state file, but it doesn't work if you have multiple mixes but always run the binary from the same directory.
I believe using the same directory as the config is the best option.
(PS: I will only be able to change this once I'm back from vacations.)

**Comment by tmarcu** [comment]
> I believe using the same directory as the config is the best option.

This is my idea too. Right now there's people using mixer and storing their builder.conf in a different directory. @rchiossi np :) Just didn't want to forget about this, it's more of a low hanging bug I noticed.

**Comment by reaganlo** [comment]
Has been fixed.
