### ISSUE TITLE
Add ability to choose compression types for swupd artifacts

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/mixer-tools#399]
The compression types mixer uses to compress swupd artifacts (i.e. fullfiles, packs, and manifests) have fixed defaults in the code. To override the fixed defaults, I would like the compression types to be configurable on the command line, in the conf file, or both.

Some ideas for the command-line options and how the values are interpreted:

###  Example 1
```
mixer build update --fullfile-compression gzip
```
- build swupd update content as normal, but use gzip (only) to compress fullfile tars.

### Example 2
```
mixer build update --fullfile-compression xz,zstd
```
- same as previous command, but try compressing fullfile tars with both xz and zstd, and pick the compressed tar with the smallest file size.

### Example 3
```
mixer build update --pack-compression zstd
```
- use zstd to compress zero packs.

**Comment by reaganlo** [comment]
This has be implemented using the Swupd.COMPRESSION config parameter.

**Comment by reaganlo** [comment]
This has be implemented using the Swupd.COMPRESSION config parameter.
