### ISSUE TITLE
proposal: follow Go conventions for mixer-tools repository

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/mixer-tools#40]
At the moment the mixer-tools repository is organized that it assumes it will be set as the GOPATH to operate. This is not the conventional way to do things, which means that some of the tooling around Go either don't work or need special care to work.

The conventional way is to assume the sources will be inside an existing GOPATH, in the github.com/clearlinux/mixer-tools directory.

Changes needed:
- Move the contents of src/ into the root of the repository
- Change import paths to use the new name of the package
- Update the Makefile to work in this new setting. Make it so that the Makefile works regardless where the mixer-tools sources is (so it would still set the GOPATH for now). For this change would be helpful to know what Makefile targets are used besides "make", "make check" and "make install".

**Comment by cmarcelo** [comment]
@tmarcu ^

**Comment by matthewrsj** [comment]
good idea, +1 from me

**Comment by kevincwells** [comment]
Agreed. +1

**Comment by cmarcelo** [comment]
The commit in master https://github.com/clearlinux/mixer-tools/commit/9607078d6d03d42fcb1f008dd011988bf6b52312 implemented part of this.

But I think there might still things to do for ensuring packaging is working correctly with the released tarball: https://github.com/clearlinux/mixer-tools/commit/9607078d6d03d42fcb1f008dd011988bf6b52312#r26373933

**Comment by tmarcu** [comment]
That commit definitely does not address everything in here, but it gets the ball rolling on these changes. I agree with the suggestions you make here.
