### ISSUE TITLE
bundle content silently entirely dropped if no bundle headers present

### ISSUE THREAD

**Issue by ahkok** [clearlinux/mixer-tools#412]
If I create a bundle file without headers, the content of the bundle is entirely dropped without as much as a warning or error.

This should be an error instead. Even a warning is silly, because the end result is that all the files from the bundle are silently omitted from the build.

Attempting to fix the bundle results in the bundle STILL not getting a manifest, either. Somehow mixer things "nothing changed" but I have to start from scratch to get the mix to actually include the RPM content.

**Comment by rchiossi** [comment]
Patch #417 solves the problem with mixer not reporting the error. I'll close this issue once it gets merged.
For the problem with %ghost files in the RPM, we will keep track on #416 .

**Comment by tmarcu** [comment]
Hmm I don't think this is related to 417 or 416 which are RPM issues, can we update the description @ahkok ?

**Comment by tmarcu** [comment]
@ahkok are you using mixer bundle <cmd> to do this stuff?

**Comment by tmarcu** [comment]
@ahkok bump pls

**Comment by ahkok** [comment]
It's slightly mislabelled, and this is fixed. Let's just close it.
