### ISSUE TITLE
Feature: mixer build docker-image

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/mixer-tools#413]
Same way Clear Linux has docker containers, enable mixes to have those.

```mixer build docker-image``` would add a docker image to the local (host) docker created from the mix at the current version. Or maybe a tarball that can be imported directly (in case that is a better way to do it), but suitable for containers.

See also: the internal script used to create docker images as part of Clear Linux release.

**Comment by tmarcu** [comment]
I want to re-visit what mixer provides in terms of image creation service. It may be more useful to have a separate image creator that handles building images of all types, rather than just having mixer shell out to ister and other things IMO.

**Comment by matthewrsj** [comment]
I agree with @tmarcu here, I'd rather take image creation out of mixer altogether. May be tough to do with people using it already though :confused:
