### ISSUE TITLE
proposal: implement bundle-chroot-builder functionality inside mixer

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/mixer-tools#42]
AFAIK mixer is the only user of the Python script. Both mixer and and bundle-chroot-builder read the same configuration file, which the template value provided to users come from bundle-chroot-builder but might include some mixer specific values.

The expected result is: avoid duplication of configuration reading code, making easy to maintain the default configuration for mixer, making easy to debug mixer (one less external script in the workflow).

It is always possible to provide an extra binary later if the functionality is needed by itself without mixer.

**Comment by matthewrsj** [comment]
good idea, +1 from me
