### ISSUE TITLE
mixer init --upstream-url error

### ISSUE THREAD

**Issue by qzheng527** [clearlinux/mixer-tools#428]
I got below errors when setting the upstream-url for mixer init.

$mixer init --upstream-url=http://linux-ftp.sh.intel.com/pub/mirrors/clearlinux/
ERROR: Failed to retrieve latest published upstream version. Missing proxy configuration? : got status "404 Not Found" when downloading: http://linux-ftp.sh.intel.com/latest

Looks like the mixer tool ignored the strings after the first "/" for upstream-url.

**Comment by rchiossi** [comment]
Fixed by #430
