### ISSUE TITLE
swupd-server to mixer (yocto integration)

### ISSUE THREAD

**Issue by aaronovz1** [clearlinux/mixer-tools#429]
@matthewrsj / @kevincwells creating a ticket here to follow on from conversations in https://github.com/clearlinux/swupd-server/issues/111.

Some slight progress but running into some issues and segfaults. These are the steps I've taken so far:

1. Start the docker image: `sudo docker run -v /media/data/yp2.5/build/intel/tmp/deploy/swupd/intel-64/intel-image:/home/clr/mix -it clearlinux/clr-sdk`
2. `sudo mixer init --native`
3. Modify `mixversion` file to have value of 1 instead of 10. Otherwise I get `ERROR: Couldn't build update: failed to create update metadata: no full manifest found` because my OS version starts at 1 not the default 10. I can probably fix this by using `--mix-version=1` in mixer init?
4. `sudo mixer build update --new-config=false --native` this appears to try to do something but then errors with a segfault

```
clr@13a48903e139 ~/mix $ sudo mixer build update --new-config=false --native
=> CREATE MANIFESTS
Generating initial manifests...
  os-core
  connectivity
  security
  dss
  kernelmodules
  debugging
  security-tools
Reading bundle includes...
Performing manifest file subtraction...
Detecting manifest changes...
Writing manifest files...

TIMINGS
  CREATE MANIFESTS 0s
TOTAL: 0s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x7265f9]

goroutine 1 [running]:
github.com/clearlinux/mixer-tools/swupd.(*Manifest).subtractManifestFromManifest(0xc4204e2380, 0x0)
	/builddir/build/BUILD/mixer-tools-5.1.3/.gopath/src/github.com/clearlinux/mixer-tools/swupd/manifest.go:592 +0x59
github.com/clearlinux/mixer-tools/swupd.(*Manifest).subtractManifests(0xc4204e2380, 0x0)
	/builddir/build/BUILD/mixer-tools-5.1.3/.gopath/src/github.com/clearlinux/mixer-tools/swupd/manifest.go:631 +0x92
github.com/clearlinux/mixer-tools/swupd.writeIndexManifest(0xc42014b1c8, 0xc42014b178, 0xc420133a78, 0x1, 0x1, 0xc4203ea240, 0xd, 0xc4203c1fa0)
	/builddir/build/BUILD/mixer-tools-5.1.3/.gopath/src/github.com/clearlinux/mixer-tools/swupd/manifest.go:838 +0x6a2
github.com/clearlinux/mixer-tools/swupd.CreateManifests(0x1, 0x19, 0xc4203ea240, 0xd, 0x8b9834, 0x5, 0x0)
	/builddir/build/BUILD/mixer-tools-5.1.3/.gopath/src/github.com/clearlinux/mixer-tools/swupd/create_manifests.go:416 +0x9fa
github.com/clearlinux/mixer-tools/builder.(*Builder).buildUpdateContent(0xc42017e200, 0x0, 0x0, 0x0, 0x1, 0xc42014bbb0, 0x8, 0xc4203c1980)
	/builddir/build/BUILD/mixer-tools-5.1.3/.gopath/src/github.com/clearlinux/mixer-tools/builder/builder.go:1567 +0x23f
github.com/clearlinux/mixer-tools/builder.(*Builder).BuildUpdate(0xc42017e200, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0)
	/builddir/build/BUILD/mixer-tools-5.1.3/.gopath/src/github.com/clearlinux/mixer-tools/builder/builder.go:1508 +0x245
github.com/clearlinux/mixer-tools/mixer/cmd.glob..func6(0xab55e0, 0xc4201365c0, 0x0, 0x2)
	/builddir/build/BUILD/mixer-tools-5.1.3/.gopath/src/github.com/clearlinux/mixer-tools/mixer/cmd/build.go:369 +0x146
github.com/clearlinux/mixer-tools/vendor/github.com/spf13/cobra.(*Command).execute(0xab55e0, 0xc420136580, 0x2, 0x2, 0xab55e0, 0xc420136580)
	/builddir/build/BUILD/mixer-tools-5.1.3/.gopath/src/github.com/clearlinux/mixer-tools/vendor/github.com/spf13/cobra/command.go:702 +0x2c6
github.com/clearlinux/mixer-tools/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xab8280, 0x405c6c, 0xc42008c058, 0x0)
	/builddir/build/BUILD/mixer-tools-5.1.3/.gopath/src/github.com/clearlinux/mixer-tools/vendor/github.com/spf13/cobra/command.go:783 +0x2e4
github.com/clearlinux/mixer-tools/vendor/github.com/spf13/cobra.(*Command).Execute(0xab8280, 0x0, 0xc420134330)
	/builddir/build/BUILD/mixer-tools-5.1.3/.gopath/src/github.com/clearlinux/mixer-tools/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/clearlinux/mixer-tools/mixer/cmd.Execute()
	/builddir/build/BUILD/mixer-tools-5.1.3/.gopath/src/github.com/clearlinux/mixer-tools/mixer/cmd/root.go:207 +0x2d
main.main()
	/builddir/build/BUILD/mixer-tools-5.1.3/.gopath/src/github.com/clearlinux/mixer-tools/mixer/main.go:22 +0x20
```

builder.conf is setup as follows:
```
#VERSION 1.0

[Builder]
  CERT = "/home/clr/mix/Swupd_Root.pem"
  SERVER_STATE_DIR = "/home/clr/mix"
  VERSIONS_PATH = "/home/clr/mix"
  YUM_CONF = "/home/clr/mix/.yum-mix.conf"

[Swupd]
  BUNDLE = "os-core-update"
  CONTENTURL = "http://127.0.0.1/updates"
  VERSIONURL = "http://127.0.0.1/updates"

[Server]
  DEBUG_INFO_BANNED = "true"
  DEBUG_INFO_LIB = "/usr/lib/debug"
  DEBUG_INFO_SRC = "/usr/src/debug"

[Mixer]
  LOCAL_BUNDLE_DIR = "/home/clr/mix/local-bundles"
  LOCAL_REPO_DIR = ""
  LOCAL_RPM_DIR = ""
  DOCKER_IMAGE_PATH = "clearlinux/mixer"
```

server.ini
```
[Server]
imagebase=/home/clr/mix/image/
outputdir=/home/clr/mix/www/
emptydir=/home/clr/mix/empty/

```

groups.ini
```
[os-core]
group=os-core

[core]
group=core

[connectivity]
group=connectivity

[kernelmodules]
group=kernelmodules

[debugging]
group=debugging

[security]
group=security

[security-tools]
group=security-tools

[dss]
group=dss
```

**Comment by rchiossi** [comment]
Just a side note: You don't need `--new-config=false` in there since you are using a new config. Mixer now identifies it and select the right one for you (that is why it didn't break on config parse), but this option is a no-op here.

**Comment by rchiossi** [comment]
`builder.conf` does not have a `FORMAT` variable anymore. Mixer will use the value in `mixer.state` only.
`upstreamversion` is the upstream release you want to base your mix on. Setting it to 1 will to to crate a mix for clearlinux 1 which is many years old. You probably want to set it to the current release (`25070` at the moment)
`https://download.clearlinux.org` is the upstreamurl. you can use `--upstream-url` in `mixer init` to change it.

**Comment by rchiossi** [comment]
Also, if you don't have an upstream and will build everything yourself (or you have all the rpms and bundles available locally), you cans use the '--offline' flag.

**Comment by aaronovz1** [comment]
I don't want to base anything on clearlinux releases though. I am using mixer/swupd with a custom built OS using Yocto. I just need mixer to generate the delta updates between versions of my OS. So for the upstreamversion, it would be starting at 0 or 1 for the initial build, not a version of clearlinux. How is the very first build achieved in clearlinux?

**Comment by rchiossi** [comment]
If I understand correctly, you can achieve what you want with something like this:
1 - Init the mix with `mixer init --offline --clear-version 1 --format 1 --upstream-url none --no-default-bundles  --local-rpms`
2 - Add your bundles to `local-bundles/` folder
3 - Add your rpms to `local-rpms/` folder
4 - add everything to the mix with `mixer bundle add --all-local` 
5 - Build everything with `mixer build all --native`

**Comment by aaronovz1** [comment]
mixer init fails with `ERROR: Cannot find bundle "bootloader" in local or upstream bundles`, so I modified the file `mixbundles` to include my list of bundles, instead of default clearlinux bundles. However, I don't know what data mixer is looking for in terms of bundles. The only data I have for bundles generated from the old meta-swupd code which was compatible with swupd-server, are the `.content.txt` files under the `image` directory. I am trying to hopefully reuse the old data with mixer, as I was under the assumption mixer is essentially swupd-server and should be compatible.

What should be under `local-bundles`?

**Comment by rchiossi** [comment]
well, that is weird. If you inti with `--no-default-bundles`, mixbundles should be empty.

**Comment by rchiossi** [comment]
To create a new bundle just use `mixer bundle edit you_bundle_name`. It will create a template for you. To add it to your mix use `mixer bundle add your_bundle_name`.

Basically a bundle is just a list of packages you want to add. If you want to see the content of one of the official bundles, just create a normal mix (`mixer init`), add a bundle (e.g. `mixer bundle add editors`) and look for the contents inside the the `upstream-bundles` folder (e.g. `upstream-bundles/clr-bundles-25070/bundles/editors`).

Not that you never need to edit `mixbundles` file directly. You can use the `mixer bundle` subcommand to manipulate it.

**Comment by aaronovz1** [comment]
I don't think I need to create the bundles using `mixer bundle`. meta-swupd already performs the steps that `mixer build bundles` does. So I already have the `.content.txt` files under `<mixer/workspace>/update/image/<version>` which `mixer build update` expects as input.

With that said - `build update` still tries to access the URL listed in `upstreamurl` and because I set it to `none` or default, it fails. Can someone explain what it is trying to access from this URL? I would expect that it needs nothing when doing the very first build as there is no previous version to update from. The only way I can get it to move forward is if I fudge it and create a file `update/1/format` with value "1" on my own webserver. But then I'm back to my original problem with the segfault in `subtractManifestFromManifest`

**Comment by aaronovz1** [comment]
At this stage I just want to get the basics working and have swupd-server swapped out to mixer with the least amount of changes to meta-swupd. Assuming swupd-server and mixer are still compatible this should be fine for the time being. meta-swupd generates the bundles with this code https://github.com/aaronovz1/meta-swupd/blob/master/lib/swupd/bundles.py

I tried using `--offline` with `mixer build update` and it still failed on the invalid URL. So perhaps a bug there too.

Is there a verbose/debug mode so I can see what is happening before it segfaults? It seems to sit there processing something for a minute before it crashes.

Thanks!

**Comment by rchiossi** [comment]
Yeah, indeed there is a bug there. There is a part of the code that checks if the URL is empty to decide if it should check the internet or not instead of checking the `--offline` flag.

For now,  run init with `--upstream-url ""` instead of  `--upstream-url none` and it should work.

**Comment by rchiossi** [comment]
I tried reproducing the segfault om my machine and I'm unable to do so. Can you give me a more detailed guide on how to reproduce it?

**Comment by aaronovz1** [comment]
I have uploaded my workspace directory [here](https://www.dropbox.com/s/chcn22kawfeenrd/my-image.tar.xz?dl=0). You should be able to mount it under the clr-sdk docker image and run the `mixer build update` command.

**Comment by rchiossi** [comment]
This is what I get running your workspace:
```
~/b/my-image > ls
builder.conf  empty/  groups.ini  image/  local-rpms/  local-yum/  maps/  mixbundles  mixer.state  mixversion  server.ini  temp/  upstream-bundles/  upstreamurl  upstreamversion
~/b/my-image > docker run -i --network=host --workdir /home/clr/mix --entrypoint mixer -v /home/rchiossi/bug_image/my-image/:/home/clr/mix clearlinux/clr-sdk build update --native
--offline
Warning: The host format and mix upstream format do not match. Mixer may be incompatible with this format; running natively may fail.
=> CREATE MANIFESTS
Generating initial manifests...
  dss
  os-core
  connectivity
  debugging
  core
  kernelmodules
  security-tools
  security
Reading bundle includes...
Performing manifest file subtraction...
Detecting manifest changes...
Writing manifest files...

TIMINGS
  CREATE MANIFESTS 0s
TOTAL: 0s
ERROR: Couldn't build update: failed to create update metadata: no full manifest found
~/b/my-image >
```

**Comment by rchiossi** [comment]
I just noticed your workspace does not have any bundle definition or rpm. Did you link the right one?

**Comment by rchiossi** [comment]
I just noticed that this workspace looks nothing like a mixer workspace before `build update`. You can run `mixer init && mixer build bundles` in a separate directory to check it for yourself.  Like I said, it is a bad idea to build the bundles manually...

**Comment by aaronovz1** [comment]
I setup a blank workspace for comparison and I can see what you mean. The structure is a little different as groups.ini, image folder, etc sit under the "update" folder instead of next to the builder.conf file. This is probably because my builder.conf has SERVER_STATE_DIR set differently.

It was useful though to see the contents under `image`. It looks like mixer doesn't use `.content.txt` files anymore, but instead uses a JSON structure? I thought @matthewrsj mentioned in another thread that mixer supports both JSON and full file tree (full chroots) though.

**Comment by matthewrsj** [comment]
https://github.com/clearlinux/mixer-tools/blob/master/docs/tutorials/custom-content-from-chroot.md

**Comment by aaronovz1** [comment]
I'm not sure that answers my question about the use of JSON vs full file tree lists (`.content.txt` files). Did mixer drop support for it in favor of JSON?

**Comment by aaronovz1** [comment]
Hi @matthewrsj,

I now better understand the link you provided. However, this will mean having to copy a lot of files on disk which will increase build time. This might be why meta-swupd was creating the `.content.txt` files manually instead. Can you confirm if mixer still supports this format and how I would get it to recognize them?

Cheers

**Comment by aaronovz1** [comment]
I had some success today going the route @matthewrsj mentioned above with the custom content from chroot. I did stumble upon a potentially bug though. If I re-run `mixer build update` without cleaning out the `www`, I get a segfault.

```
clr@fb353e0d6ad4 ~/mix $ sudo mixer build update --native --offline
Warning: The host format and mix upstream format do not match. Mixer may be incompatible with this format; running natively may fail.
=> CREATE MANIFESTS
Generating initial manifests...
  os-core
  connectivity
  security
  core
  kernelmodules
  dss
  security-tools
  debugging
Reading bundle includes...
Performing manifest file subtraction...
Detecting manifest changes...
Writing manifest files...
MoM version 1
- connectivity         1
- core                 1
- debugging            1
- dss                  1
- kernelmodules        1
- os-core              1
- os-core-update-index 1
- security             1
- security-tools       1
Signing manifest.
Compressing Manifest.MoM
Compressing bundle manifests
  security-tools
  os-core
  os-core-update-index
  kernelmodules
  debugging
  connectivity
  dss
  security
  core
  full

=> CREATE FULLFILES
Using 8 workers
- Already created: 0
- Not compressed:  0
- Compressed
  - gzip                 1638
  - external-xz          11244
  - external-gzip        32197
  - external-bzip2       2847
Total fullfiles: 47926

=> CREATE ZERO PACKS
Creating zero pack for connectivity to version 1
  Fullfiles in pack: 683
  Deltas in pack: 0
Creating zero pack for core to version 1
  Fullfiles in pack: 10468
  Deltas in pack: 0
Creating zero pack for debugging to version 1
  Fullfiles in pack: 6883
  Deltas in pack: 0
Creating zero pack for dss to version 1
  Fullfiles in pack: 29897
  Deltas in pack: 0
Creating zero pack for kernelmodules to version 1
  Fullfiles in pack: 1054
  Deltas in pack: 0
Creating zero pack for os-core to version 1
  Fullfiles in pack: 2307
  Deltas in pack: 0
Creating zero pack for os-core-update-index to version 1
  Fullfiles in pack: 2
  Deltas in pack: 0
Creating zero pack for security to version 1
  Fullfiles in pack: 2094
  Deltas in pack: 0
Creating zero pack for security-tools to version 1
  Fullfiles in pack: 151
  Deltas in pack: 0
Saving the upstream URL: none
Saving the upstream version: 1
Setting latest version to 1

TIMINGS
  CREATE MANIFESTS  16.384s
  CREATE FULLFILES  2m47.548s
  CREATE ZERO PACKS 1m57.584s
TOTAL: 5m1.517s
clr@fb353e0d6ad4 ~/mix $ sudo mixer build update --native --offline
Warning: The host format and mix upstream format do not match. Mixer may be incompatible with this format; running natively may fail.
=> CREATE MANIFESTS
Generating initial manifests...
  os-core
  core
  kernelmodules
  connectivity
  debugging
  security-tools
  security
  dss
Reading bundle includes...
Performing manifest file subtraction...
Detecting manifest changes...
Writing manifest files...

TIMINGS
  CREATE MANIFESTS 0s
TOTAL: 0s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x7265f9]

goroutine 1 [running]:
github.com/clearlinux/mixer-tools/swupd.(*Manifest).subtractManifestFromManifest(0xc420365b20, 0x0)
	/builddir/build/BUILD/mixer-tools-5.1.3/.gopath/src/github.com/clearlinux/mixer-tools/swupd/manifest.go:592 +0x59
github.com/clearlinux/mixer-tools/swupd.(*Manifest).subtractManifests(0xc420365b20, 0x0)
	/builddir/build/BUILD/mixer-tools-5.1.3/.gopath/src/github.com/clearlinux/mixer-tools/swupd/manifest.go:631 +0x92
github.com/clearlinux/mixer-tools/swupd.writeIndexManifest(0xc42013d1c8, 0xc42013d178, 0xc42012d8d0, 0x1, 0x1, 0xc4204342b0, 0xd, 0xc420419240)
	/builddir/build/BUILD/mixer-tools-5.1.3/.gopath/src/github.com/clearlinux/mixer-tools/swupd/manifest.go:838 +0x6a2
github.com/clearlinux/mixer-tools/swupd.CreateManifests(0x1, 0x1, 0xc4204342b0, 0xd, 0x8b9834, 0x5, 0x0)
	/builddir/build/BUILD/mixer-tools-5.1.3/.gopath/src/github.com/clearlinux/mixer-tools/swupd/create_manifests.go:416 +0x9fa
github.com/clearlinux/mixer-tools/builder.(*Builder).buildUpdateContent(0xc42016a200, 0x0, 0x0, 0x0, 0x1, 0xc42013dbb0, 0x7, 0xc4200722a0)
	/builddir/build/BUILD/mixer-tools-5.1.3/.gopath/src/github.com/clearlinux/mixer-tools/builder/builder.go:1567 +0x23f
github.com/clearlinux/mixer-tools/builder.(*Builder).BuildUpdate(0xc42016a200, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0)
	/builddir/build/BUILD/mixer-tools-5.1.3/.gopath/src/github.com/clearlinux/mixer-tools/builder/builder.go:1508 +0x245
github.com/clearlinux/mixer-tools/mixer/cmd.glob..func6(0xab55e0, 0xc42010e860, 0x0, 0x2)
	/builddir/build/BUILD/mixer-tools-5.1.3/.gopath/src/github.com/clearlinux/mixer-tools/mixer/cmd/build.go:369 +0x146
github.com/clearlinux/mixer-tools/vendor/github.com/spf13/cobra.(*Command).execute(0xab55e0, 0xc42010e820, 0x2, 0x2, 0xab55e0, 0xc42010e820)
	/builddir/build/BUILD/mixer-tools-5.1.3/.gopath/src/github.com/clearlinux/mixer-tools/vendor/github.com/spf13/cobra/command.go:702 +0x2c6
github.com/clearlinux/mixer-tools/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xab8280, 0x405c6c, 0xc42008c058, 0x0)
	/builddir/build/BUILD/mixer-tools-5.1.3/.gopath/src/github.com/clearlinux/mixer-tools/vendor/github.com/spf13/cobra/command.go:783 +0x2e4
github.com/clearlinux/mixer-tools/vendor/github.com/spf13/cobra.(*Command).Execute(0xab8280, 0x0, 0xc420016830)
	/builddir/build/BUILD/mixer-tools-5.1.3/.gopath/src/github.com/clearlinux/mixer-tools/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/clearlinux/mixer-tools/mixer/cmd.Execute()
	/builddir/build/BUILD/mixer-tools-5.1.3/.gopath/src/github.com/clearlinux/mixer-tools/mixer/cmd/root.go:207 +0x2d
main.main()
	/builddir/build/BUILD/mixer-tools-5.1.3/.gopath/src/github.com/clearlinux/mixer-tools/mixer/main.go:22 +0x20
```

**Comment by rchiossi** [comment]
I'll take a look at this crash.

**Comment by rchiossi** [comment]
> 1. What is `--mix-version` used for in `mixer init`? Is it the version of mixer tools or does it relate to something else? I'm not sure what I should be setting it to or what the default of 10 refers to. I have assumed `--clear-version` refers to the OS version updates are being generated for.

`--clear-version` is indeed the version that you are creating the update to. `--mix-version` is the version of your mix. If this mix is not a branch, but the next upstream itself, it should be set to a number bigger than `clear-version`. Traditionally we move in increments of 10, so in this case, `mix-version` would be set to `clear-version + 10`.

> 2. In docker container `clr-sdk` how do you pass `--mixdir` or `--id` to the container? All combinations I've tried don't recognize the args and fails. I've tried putting them before the container and after in the `docker run` command. I'm pretty sure I need these settings so that content under `www` isn't owned by root. If not - how would I get around this without doing a chown on the host (which would require sudo and couldn't be scripted).

Both `--mixdir` and `--id` are not valid mixer flags and I'm not familiar with swupd-server to know what they used to be. I assume `--mixerdir` should be what we now call `VERSIONS_PATH` in `builder.conf`. If that is the case, you can set it with the command `mixer config set Builder.VERSIONS_PATH /my/path/here`. I don't know what `--id` is supposed to be.

Regarding the files being owned by `root`, I don't think there is a way around it. Basically what mixer does is create an empty chroot and tell `dnf` to install the packages there. `dnf` will set the owner and permission for the file. The way mixer "avoids" using root is by spawning a docker instance and building inside it, but since you are already inside docker and cannot spawn a nested instance, there is no way to build without root.
