### ISSUE TITLE
Shrink the size of the mixer container image.

### ISSUE THREAD

**Issue by kevincwells** [clearlinux/mixer-tools#432]
**Problem**
We've talked in the past about wanting/needing to fine-tune what's included in the mixer bundle so that the container mixer downloads is as small as possible. Obviously keeping the bundle trim improves usage/install times for general users as well.

As recent as a few weeks ago, the format 25 container was ~350MB compressed. Sometime in those weeks, it jumped up to [950MB](https://hub.docker.com/r/clearlinux/mixer/tags/).  As DevOps finally starts publishing these with every release, that means mixer will need to re-pull a nearly 1GB file up to twice a day.

**Proposal**
Docker is one of the complicating factors, and including the `containers-basic` bundle in mixer likely accounts for some/most of the size increase.  But docker isn't actually needed for the version of mixer inside the container itself.

In addition to general trimming where possible, I propose that we split mixer into two bundles: **`mixer`** and **`mixer-native`**. `mixer` would include docker (and whatever else is needed for it, without pulling in the entire `containers-basic`) and `mixer-native`. `mixer-native` would only include what is needed to run mixer natively.  Then, we change the `clearlinux/mixer` docker image to only include the `mixer-native` package, rather than the higher-level `mixer` meta package.

**Comment by reaganlo** [comment]
Docker has been removed from mixer.
