### ISSUE TITLE
unsupported protocol scheme "file"

### ISSUE THREAD

**Issue by aaronovz1** [clearlinux/mixer-tools#436]
In the older swupd-server it was possible to use file:// to reference local/network file paths for the previous update data for content/version URL's. The only way around this currently is to setup a local webserver which seems like overkill when it could just read from the local disk directly.

**Comment by matthewrsj** [comment]
You are right that is overkill. In swupd-server we could use libcurl to just handle it all internally. The golang net/http library doesn't allow file protocol. We should add an internal API to handle file protocol in mixer, I agree.

**Comment by matthewrsj** [comment]
Maybe something like https://github.com/hashicorp/go-getter, though that may be a little heavy-weight.

**Comment by aaronovz1** [comment]
Is this going to be considered in a near term release?

**Comment by reaganlo** [comment]
@aaronovz1 I believe this already works. You can set the update and version url with the "file" scheme in the builder.conf and point swupd to it.
E.g.
```
mixer config set Swupd.CONTENTURL file://$PWD/update/www
mixer config set Swupd.VERSIONURL file://$PWD/update/www
```
Can you please try if it works for you?

**Comment by reaganlo** [comment]
Closing as this feature is supported.
