### ISSUE TITLE
Host format not configurable

### ISSUE THREAD

**Issue by aaronovz1** [clearlinux/mixer-tools#437]
I am building outside the Clearlinux environment (Yocto integration) and have come across a warning which I think also leads into a segfault later in the chain.

`Warning: The host format and mix upstream format do not match. Mixer may be incompatible with this format; running natively may fail.`

This appears to be because the host format is read from `/usr/share/defaults/swupd/format` and I don't see a way to configure that dynamically either through `mixer init` or `mixer build`. The default value in the clr-sdk container is `25`, but in non-clearlinux operating systems, the format will be something custom (in many cases starting at 1).

The segfault I mentioned in #429, but I think it all stems from the same problem. When there is missing data under `update/image/<version>` it will segfault with something like below. I believe it needs to check for a null manifest pointer. Some extra logging to help determine what might be missing would be nice to have in the fix.

```
=> CREATE MANIFESTS
Generating initial manifests...
  os-core
  core
  debugging
  security
  security-tools
  connectivity
  dss
  kernelmodules
Reading bundle includes...
Performing manifest file subtraction...
Detecting manifest changes...
Writing manifest files...

TIMINGS
  CREATE MANIFESTS 0s
TOTAL: 0s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x7265f9]

goroutine 1 [running]:
github.com/clearlinux/mixer-tools/swupd.(*Manifest).subtractManifestFromManifest(0xc420235180, 0x0)
  /builddir/build/BUILD/mixer-tools-5.1.3/.gopath/src/github.com/clearlinux/mixer-tools/swupd/manifest.go:592 +0x59
github.com/clearlinux/mixer-tools/swupd.(*Manifest).subtractManifests(0xc420235180, 0x0)
  /builddir/build/BUILD/mixer-tools-5.1.3/.gopath/src/github.com/clearlinux/mixer-tools/swupd/manifest.go:631 +0x92
github.com/clearlinux/mixer-tools/swupd.writeIndexManifest(0xc42014d1c8, 0xc42014d178, 0xc42013a068, 0x1, 0x1, 0xc4201524c0, 0x14, 0xc420152c80)
  /builddir/build/BUILD/mixer-tools-5.1.3/.gopath/src/github.com/clearlinux/mixer-tools/swupd/manifest.go:838 +0x6a2
github.com/clearlinux/mixer-tools/swupd.CreateManifests(0x1, 0x4, 0xc4201524c0, 0x14, 0x8b9834, 0x5, 0x0)
  /builddir/build/BUILD/mixer-tools-5.1.3/.gopath/src/github.com/clearlinux/mixer-tools/swupd/create_manifests.go:416 +0x9fa
github.com/clearlinux/mixer-tools/builder.(*Builder).buildUpdateContent(0xc4201e8000, 0x0, 0x0, 0x0, 0x1, 0xc42014dbb0, 0x7, 0xc420152b80)
  /builddir/build/BUILD/mixer-tools-5.1.3/.gopath/src/github.com/clearlinux/mixer-tools/builder/builder.go:1567 +0x23f
github.com/clearlinux/mixer-tools/builder.(*Builder).BuildUpdate(0xc4201e8000, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0)
  /builddir/build/BUILD/mixer-tools-5.1.3/.gopath/src/github.com/clearlinux/mixer-tools/builder/builder.go:1508 +0x245
github.com/clearlinux/mixer-tools/mixer/cmd.glob..func6(0xab55e0, 0xc42008f070, 0x0, 0x1)
  /builddir/build/BUILD/mixer-tools-5.1.3/.gopath/src/github.com/clearlinux/mixer-tools/mixer/cmd/build.go:369 +0x146
github.com/clearlinux/mixer-tools/vendor/github.com/spf13/cobra.(*Command).execute(0xab55e0, 0xc42008f050, 0x1, 0x1, 0xab55e0, 0xc42008f050)
  /builddir/build/BUILD/mixer-tools-5.1.3/.gopath/src/github.com/clearlinux/mixer-tools/vendor/github.com/spf13/cobra/command.go:702 +0x2c6
github.com/clearlinux/mixer-tools/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xab8280, 0x405c6c, 0xc420084058, 0x0)
  /builddir/build/BUILD/mixer-tools-5.1.3/.gopath/src/github.com/clearlinux/mixer-tools/vendor/github.com/spf13/cobra/command.go:783 +0x2e4
github.com/clearlinux/mixer-tools/vendor/github.com/spf13/cobra.(*Command).Execute(0xab8280, 0x0, 0xc420098750)
  /builddir/build/BUILD/mixer-tools-5.1.3/.gopath/src/github.com/clearlinux/mixer-tools/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/clearlinux/mixer-tools/mixer/cmd.Execute()
  /builddir/build/BUILD/mixer-tools-5.1.3/.gopath/src/github.com/clearlinux/mixer-tools/mixer/cmd/root.go:207 +0x2d
main.main()
  /builddir/build/BUILD/mixer-tools-5.1.3/.gopath/src/github.com/clearlinux/mixer-tools/mixer/main.go:22 +0x20

```

**Comment by rchiossi** [comment]
you can use `--format` flag in mixer init to set the format. The waning might still proc, but you can ignore it if you set it manually during init.

**Comment by aaronovz1** [comment]
Perhaps I'm running into a different issue then. I realised I wasn't calling `mixer init` on every build, only for the first build. After changing it to call it every build, I get a different error.

```
Initializing mix version 1 from upstream version 1
ERROR: Failed to download bundles for upstream version 1: Failed to download file: got status "404 Not Found" when downloading: https://github.com/clearlinux/clr-bundles/archive/1.tar.gz
```

Basically I am trying to build an update from version 1 to version 2. I was able to successfully build version 1 and deployed the files to a local webserver.

This is the init command I'm using:
`init --clear-version 2 --format 4 --upstream-url 'http://172.23.1.55' --upstream-version 1 --no-default-bundles --mix-version 1`

I am not sure why it tries to reference `https://github.com/clearlinux/clr-bundles/archive/1.tar.gz`. I don't require any bundles from clearlinux. Am I using clear-version and upstream-version parameters correctly?

Thanks

**Comment by aaronovz1** [comment]
Ok I resolved that issue. I didn't realize `mixer init` can accept the `--offline` flag as it's not documented in the manpages for 5.1.3. I think the next issue requires the recent fixes for the --offline flag in 5.2.1.

@kevincwells what is the best way to update mixer to the latest in the clr-sdk container?

**Comment by rchiossi** [comment]
Yes, `--offline` is a global flag and can always be used.

> Perhaps I'm running into a different issue then. I realised I wasn't calling `mixer init` on every build, only for the first build.

Actually, you should only run `mixer init` for the first build. Is there any reason why you are running it again?

**Comment by aaronovz1** [comment]
That is the way I had it originally. I guess I'm getting confused around how mixer determines what the next version is that it needs to generate the updates for. If I call `mixer init` once with `--clear-version 1`. How does it know to generate updates for version 2? In the deprecated swupd-server, you would normally pass `--osversion` to `swupd_create_update` and `swupd_make_fullfiles`. I don't see an equivalent in `mixer build update`.

**Comment by rchiossi** [comment]
Ah, indeed. That is probably the best way to go if you are your own upstream.

In theory you could also do the same with the `mixer versions update` command, but I just noticed it doesn't like the `--offline` flag.

**Comment by aaronovz1** [comment]
Should we create a separate ticket to fix `mixer versions` to obey the --offline flag?

Would the `--increment` flag for `mixer build` also achieve a similar thing or does refer to something else?

I don't suppose you know how to update mixer inside the docker containers? I'm kind of blocked until I update to 5.2.1.

**Comment by rchiossi** [comment]
> Should we create a separate ticket to fix `mixer versions` to obey the --offline flag?

There is already an issue to make a global offline mode that should fix all those issues. It is already ongoing so I think there is no need to create another one.

> Would the `--increment` flag for `mixer build` also achieve a similar thing or does refer to something else?

`--increment` automatically adds `+10` to `mixver`, but it won't change clearversion.
 
> I don't suppose you know how to update mixer inside the docker containers? I'm kind of blocked until I update to 5.2.1.

You could call `swupd update` on every boot (which sounds bad), or you could build mixer yourself, mount a directory with the new binary inside the container and use that mixer instead. That is probably the best way to test things in the meantime until clr-sdk gets updated.

**Comment by aaronovz1** [comment]
Thanks for the help. I finally got it working! I ended up with the following init call:

```
init --clear-version {previousversion} --format {format} --upstream-url 'http://serverurlhere'  --no-default-bundles --mix-version {nextversion} --offline
```

**Comment by rchiossi** [comment]
Awesome! I'm still looking at that segfault just to make sure it wont crash again in the future.
