### ISSUE TITLE
"mixer build delta-packs" doesn't work through container 

### ISSUE THREAD

**Issue by bktan8** [clearlinux/mixer-tools#439]
Building delta-packs through container seems to generate some errors.

clear@clr-class01 ~/mixer $ mixer build delta-packs --from 10 --to 20
Warning: Using Format=25 from mixer.state for this build.
Updating docker image
25: Pulling from clearlinux/mixer
Digest: sha256:1f21a92dbdee1555825b1cbc1e254ff669b73467267b6cc7dfa3f440b22e7f3c
Status: Image is up to date for clearlinux/mixer:25
Running command in container: "mixer build delta-packs --from=10 --to=20"
Using 8 workers
=> CREATE DELTA PACKS
Creating delta packs from 10 to 20
  Delta pack already exists for curl from 0 to 20
  Delta pack already exists for editors from 0 to 20
  Delta pack already exists for emacs from 0 to 20
  Delta pack already exists for p11-kit from 0 to 20
  Delta pack already exists for perl-basic from 0 to 20
  Delta pack already exists for python3-basic from 0 to 20
  Delta pack already exists for vim from 0 to 20
  Creating delta pack for bundle "os-core" from 10 to 20
  Creating delta pack for bundle "os-core-update-index" from 10 to 20
**ERROR: Pack "os-core-update-index" from 10 to 20 FAILED to be created: exec: "zstd": executable file not found in $PATH
ERROR: Pack "os-core" from 10 to 20 FAILED to be created: exec: "zstd": executable file not found in** $PATH

TIMINGS
  CREATE DELTA PACKS 5ms
TOTAL: 5ms

If it's done through --native, seems to be ok.  

clear@clr-class01 ~/mixer $ sudo mixer build delta-packs --from 10 --to 20 --native
Password: 
Using 8 workers
=> CREATE DELTA PACKS
Creating delta packs from 10 to 20
  Delta pack already exists for curl from 0 to 20
  Delta pack already exists for editors from 0 to 20
  Delta pack already exists for emacs from 0 to 20
  Delta pack already exists for p11-kit from 0 to 20
  Delta pack already exists for perl-basic from 0 to 20
  Delta pack already exists for python3-basic from 0 to 20
  Delta pack already exists for vim from 0 to 20
  Creating delta pack for bundle "os-core" from 10 to 20
  Creating delta pack for bundle "os-core-update-index" from 10 to 20
    Fullfiles in pack: 2
    Deltas in pack: 1
    Fullfiles in pack: 7
    Deltas in pack: 1

TIMINGS
  CREATE DELTA PACKS 9ms
TOTAL: 9ms

**Comment by tmarcu** [comment]
@bktan8 thanks for bringing this up, turns out it's not just a problem with systems running other OS's. Adding a patch to include zstd binary into mixer as well, since only the zstd dev library is provided by default in libarchive. Will close this once it's released.
