### ISSUE TITLE
corrupt pack files being generated

### ISSUE THREAD

**Issue by aaronovz1** [clearlinux/mixer-tools#442]
I finally got mixer generating updates without any obvious errors but when I tried testing updating my OS from version 1 to version 2, the client couldn't unpack any of the `pack-*-from-1.tar` files. Trying to open the tar files throws an error as if they are corrupt or weren't written completely. Doing a `file` shows they aren't interpreted as XZ compressed data like the `pack-*-from-0.tar` files.

Does anyone know how this might occur or have any ideas on tracking this down? I can provide more information if I know what to look for.

```
delta:                                directory
files:                                directory
format:                               very short file (no magic)
Manifest.dss:                         ASCII text
Manifest.dss.tar:                     XZ compressed data
Manifest.full:                        UTF-8 Unicode text
Manifest.full.tar:                    XZ compressed data
Manifest.MoM:                         ASCII text
Manifest.MoM.sig:                     data
Manifest.MoM.tar:                     XZ compressed data
Manifest.os-core:                     UTF-8 Unicode text
Manifest.os-core.tar:                 XZ compressed data
Manifest.os-core-update-index:        ASCII text
Manifest.os-core-update-index.tar:    XZ compressed data
mixer-src-version:                    ASCII text, with no line terminators
pack-dss-from-0.tar:                  XZ compressed data
pack-dss-from-1.tar:                  data
pack-os-core-from-0.tar:              XZ compressed data
pack-os-core-from-1.tar:              data
pack-os-core-update-index-from-0.tar: XZ compressed data
pack-os-core-update-index-from-1.tar: data
upstreamurl:                          ASCII text, with no line terminators
upstreamver:                          very short file (no magic)
```

**Comment by tmarcu** [comment]
@aaronvz1 do you have zstd compression available on your system? Delta packs are created using zstd only now, and zero packs are xz.

**Comment by aaronovz1** [comment]
@tmarcu I am running mixer in the docker clr-sdk container. I would assume zstd is in the container? If not then it should probably be added as a dependency.

**Comment by aaronovz1** [comment]
Never mind. You’re referring to the host system, in which case I don’t have zstd installed. I’ll set that up tomorrow and close this out if it solves the problem.

**Comment by tmarcu** [comment]
Great let me know if that gets you any further! This doesn’t solve your problem, but, I have to say for the record I would also highly encourage other options than the sdk container, I.e a regular VM if the host system can’t be Clear.

**Comment by aaronovz1** [comment]
This was a non issue. I had to install zstd and update libarchive. Closing.
