### ISSUE TITLE
mixer init must create .yum-mix.conf

### ISSUE THREAD

**Issue by tmarcu** [clearlinux/mixer-tools#452]
This should be shifted left from being create in build bundles, to being created during mixer init phase, with a --repo flag that sets the default repo in it to something other than download.clearlinux. A user may want to edit this file before building their first mix because they are a full upstream building completely offline, so make it easier for them to do so from the beginning.

**Comment by ahkok** [comment]
Ideally, this is created when needed and removed elsewhere, and `builder.conf` contains the needed hints to include e.g. a local repo. See #454. Maybe both things are possible, though - if it exists, use it, else, create it on the fly for each operation and remove after it's no longer needed?

**Comment by tmarcu** [comment]
It's always needed is the thing though, but I understand where you're coming from now. *Technically* it isn't necessarily needed for a plain default mix case with no extra repos, you're right there.

**Comment by rchiossi** [comment]
Isn't it? afaik dnf always get the -config flag used, even if you don't add anything. So even if id doesn't need it, it will at least look if the file exists when mixer calls it.
