### ISSUE TITLE
RFE: relative file paths in configs (builder.conf and .yum-mix.conf)

### ISSUE THREAD

**Issue by ahkok** [clearlinux/mixer-tools#454]
Moving the mixer folder, or renaming it breaks it. This is awkward, and you have to manually edit two files to recover.

Expected behavior:

- the yum repo file is just created on the fly, and destroyed after the operation completes
- builder.conf contains relative file paths by default

**Comment by tmarcu** [comment]
The dnf conf should not be destroyed, can you explain why that would be useful? It’s com
