### ISSUE TITLE
Implement alternative input layout

### ISSUE THREAD

**Issue by aaronovz1** [clearlinux/mixer-tools#476]
There is functionality from the original swupd-server that wasn't brought across to mixer which allows custom bundles to be defined as a file list. This avoids having to copy each bundle rootfs which the document [here](https://github.com/clearlinux/mixer-tools/blob/master/docs/tutorials/custom-content-from-chroot.md) describes.

Please see the original pull request here for more information:
https://github.com/clearlinux/swupd-server/pull/55

@matthewrsj  - Would it be possible to get this into mixer any time soon?

**Comment by matthewrsj** [comment]
@aaronovz1 there is no plan to add that feature *as it existed in swupd-server* right now, but one thing you could do that is essentially the same thing is provide a bundle-info file instead of the individual chroot. All that `mixer build update` uses from the bundle-info file is the file list anyways.

mycustombundle-info:
```
{
    "Name": "mycustombundle",
    "Filename: "",
    "Header": {
        "Title": "",
        "Description": "",
        "Status": "",
        "Capabilities": "",
        "Maintainer": ""
    },
    "DirectIncludes": null,
    "AllPackages": null,
    "Files": {
        "/usr/bin/foo": true,
        "/usr/bin/bar": true,
        ...
    }
}
```
You may need to validate that, you *might* need to define `DirectIncludes` but I think you're fine without.

If you do it this way all the `Files` listed need to exist in the full chroot of course.

**Comment by aaronovz1** [comment]
Ok thanks. Let me try that route and see how I go.

**Comment by matthewrsj** [comment]
You will still need to add the bundle to the groups.ini as well and put the bundle-info file in the `image/<ver>` directory.

**Comment by aaronovz1** [comment]
Ok. I have the JSON files being generated under `image/<ver>`. Mixer complained that it couldn't stat `image/<ver>/mybundle` for each of the bundles. So I added to my script to create empty directories for each of the bundles. But then I get error from mixer `ERROR: Couldn't build update: failed to create update metadata: manifest has a zero file count`.

Do I need to change how I call `mixer build` when using this method?

**Comment by tmarcu** [comment]
@aaronovz1 if you put empty directories, it will treat it as "all files were deleted for this bundle," so don't do that, only use bundle-info files, or use a directory that is a chroot. What version of mixer are you using? 

> Do I need to change how I call mixer build when using this method?

No :)

**Comment by aaronovz1** [comment]
If I have empty directories and just have bundle-info files, then mixer throws an error that it can't stat a directory with the same name as the bundle. I am running mixer 5.2.1 within the clr-sdk docker image.

**Comment by aaronovz1** [comment]
@tmarcu / @matthewrsj 
It seems like the code path goes into:
https://github.com/clearlinux/mixer-tools/blob/70a3f68c580c9da94491ad03f326dd930193c519/swupd/create_manifests.go#L101

Then:
https://github.com/clearlinux/mixer-tools/blob/70a3f68c580c9da94491ad03f326dd930193c519/swupd/fullchroot.go#L34

Which fails because the path `image/<ver>/<bundle>` does not exist.

I could be wrong but I don't have a quick way to add extra debug logging, compile, and add commit it into the docker image to test. Any tips on the best process for that would help.

**Comment by aaronovz1** [comment]
Ok. I totally messed up. Did not realize when I was making the bundle-info files they had a `.json` extension. This breaks everything. I did however figure out how to compile mixer and commit it into a docker image in the process, so now I can debug mixer quite easily :)
