### ISSUE TITLE
os-core-update-index still being generated

### ISSUE THREAD

**Issue by aaronovz1** [clearlinux/mixer-tools#508]
I thought in mixer 5.4 the os-core-update stuff was removed. However, I am still seeing some files being generated.
```
/update/image/1/os-core-update-index/usr/share/clear/bundles/os-core-update-index
update/www/1/Manifest.os-core-update-index
```

Is this expected?

**Comment by matthewrsj** [comment]
The `/usr/share/clear/os-core-update-index` file itself was removed, yet the `os-core-update-index` bundle still exists to provide the content under `/usr/share/clear/allbundles`
