### ISSUE TITLE
Is mixer bundle "edit" being deprecated?

### ISSUE THREAD

**Issue by bktan8** [clearlinux/mixer-tools#520]
I don't see it in "mixer bundle --help", but the "edit" subcommand still works and no message about it being deprecated or not.

**Comment by rchiossi** [comment]
Indeed. Since we removed the editor from `bundle edit`, **edit** and **create** became pretty much the same command, so now **edit** is an alias to **create**. If you just type `mixer bundle edit` or `mixer bundle create` you will see both are listed in the **Aliases** section.
