### ISSUE TITLE
Can we have "mixer bundle set-local <upstream bundle name>" to make an upstream bundle a local bundle?

### ISSUE THREAD

**Issue by bktan8** [clearlinux/mixer-tools#522]
"mixer bundle create <upstream bundle name>" doesn't make sense and is not intuitive at all.  
I think "create" should just be for creating a new bundle.

**Comment by rchiossi** [comment]
Maybe the wording of the command description generates some confusion, but basically `bundle create` always creates a new bundle, what changes is what mixer uses as a template for the created file: blank is not found, upstream if found. 
If you call create on a bundle that exists upstream, you are creating a completely new bundle even thought they have the same name.

**Comment by reaganlo** [comment]
There needs to be a balance between intuition and providing unnecessary additional options that the user would need to remember. I think its easier for a user to just remember one command that creates a local copy of a bundle (be it an upstream one or a new one).

**Comment by chivakker** [comment]
Could we have also mixer bundle remove-local, or is there another way to revert back to upstream bundle once I'm done with my local copy? (i.e. my changes made it upstream and I just want to continue tracking that)

**Comment by jwakre** [comment]
@chivakker There is _mixer bundle remove --local_ command, but this seems to remove the upstream reference from the mix too. Another way to remove a local bundle is to erase the corresponding bundle file from the local-bundles directory.

**Comment by chivakker** [comment]
@jwakre I'm currently just removing manually the local-bundles copy.  It would be nice to have a mixer command that does that.

**Comment by reaganlo** [comment]
This has been fixed with the --local flag.
