### ISSUE TITLE
Improve iterative manifest effectiveness for minversion updates

### ISSUE THREAD

**Issue by jwakre** [clearlinux/mixer-tools#527]
Minversions create large updates, but typically without content changes. Since these updates can change many file versions, iterative manifests (if generated) will usually be very long. In this case, iterative manifests could add entries based on content changes instead of version changes to reduce unnecessary manifest entries caused by minversions.

Based on offline discussion, I know that @otaviobp is interested in improving iterative manifest performance for minversion updates and @rchiossi has concerns with empty iterative manifests which could be created with the above solution.

**Comment by jwakre** [comment]
I was thinking more about improving iterative manifest performance for minversions. I think a better solution would be to use the MoM flags to mark iterative manifest entries when their bundle was updated by a minversion and has no content changes. This would allow Swupd to uses MoM entries to skip over these bundles and Mixer would not need to generate them. Below is an outline of the changes required by Mixer/Swupd:

Mixer:

* When a bundle is updated by a minversion and does not have a content change, create an iterative manifest entry in the MoM with an additional (or alternative) flag to mark it unused (**Iu..** or something similar. Would need to confirm that other flags do not conflict.)
* Do not generate iterative manifests when the iterative manifest MoM entry contains the unused flag.

Swupd:

* When consuming iterative manifests, skip over MoM entries marked with the unused flag. The bundle should already be up-to-date on the system, so we don't need to update files or download bundle manifests.
* The bundle update statistics would need modifications to consistently report information, like number of files changed.

**Comment by reaganlo** [comment]
Iterative manifests have been removed in Mixer v6.0.0 by PR https://github.com/clearlinux/mixer-tools/pull/620
