### ISSUE TITLE
Feature: Bundle lint tool

### ISSUE THREAD

**Issue by kevincwells** [clearlinux/mixer-tools#53]
# New Feature
Add a new command ("mixer bundle check") to lint and validate a bundle definition file.

# Use Case
If a developer wants to write their own bundle file, or alter an existing one, it would be useful to be able to verify that it is correct.

# Functionality
- The tool will at minimum "lint" the bundle file, ensuring that it is correctly formatted.
- The tool could validate that fields are not empty.
- The tool could validate that packages/bundles mentioned in the file actually exist.
  - Bundles seems easy, packages seems harder.

# Notes
- While this is being proposed as a stand-alone call, the intent is to incorporate this linting as an automatic (but suppressible) step for any other commands that involve creating or editing bundles.
- The logic of this would need to be rewritten if the bundle definition format changes (e.g., to a TOML file), but such changes would actually significantly simplify the logic needed to lint/parse.

**Comment by kevincwells** [comment]
Most of this is implemented by #177.

What's not in that PR is checking validity of the bundles and packages listed in the bundle.
Checking packages would be pretty easy - calling `getBundlePath` on each included bundle would do the trick. Not entirely sure where to look to validate packages. @matthewrsj probably knows.

Both of these can be incremental patches.

**Comment by tmarcu** [comment]
This issue is fixed, we can open another for packages.
