### ISSUE TITLE
mixer cannot finish the upstream-format built

### ISSUE THREAD

**Issue by mpurzynski** [clearlinux/mixer-tools#536]
Hey!

I was told by the mixer versions update command to update my format range

root@clr-141f7bb770c54e568adf625071d8151f /home/clr/mix # mixer versions update --upstream-version latest
Old mix:      1170
Old upstream: 27310 (format: 27)

New mix:      1180
New upstream: 27310 (format: 27)

Wrote mixversion.
Wrote upstreamversion.
The upstream version for this build (27310) is outside the format range of your last mix (format 26, upstream versions 25770 to 27200). This build cannot be done until you complete an upstream format build. Please run the following command to complete the format bump:
mixer build upstream-format
Once this has completed you can re-run this build you are attempting to create.
* Please note that if you are multiple format bumps behind, mixer will detect you are still behind and re-run the command until the proper format is reached.

So I did that and ran 

mixer build upstream-format

Building bundles...
2019/01/18 00:50:34 => BUILD BUNDLES
Creating bundles for version 1180 based on Clear Linux 27310
Preparing new /home/clr/mix/update/image/1180
  and dnf config: /home/clr/mix/.yum-mix.conf
Packager command-line: dnf --config=/home/clr/mix/.yum-mix.conf -y --releasever=27310
Resolving packages using 2 workers
processing storage-utils
processing dosfstools
... done with dosfstools
processing acpica-unix2
... done with acpica-unix2
processing irssi
... done with storage-utils
processing syslog-ng
... done with irssi
processing gdb
... done with gdb
processing kernel-install
... done with kernel-install
processing unzip
... done with unzip
processing openssh-server
... done with openssh-server
processing git
... done with git
processing gzip
... done with gzip
processing kernel-native
... done with kernel-native
processing os-core
... done with os-core
processing os-core-webproxy
... done with os-core-webproxy
processing xz
... done with xz
processing python3-basic
... done with python3-basic
processing strace
... done with strace
processing bootloader
... done with bootloader
processing parallel
... done with syslog-ng
processing weechat
... done with parallel
processing p11-kit
... done with weechat
processing which
... done with p11-kit
processing bro
... done with which
processing tzdata
... done with bro
processing essentials
... done with tzdata
processing diffutils
... done with essentials
processing file
... done with diffutils
processing zstd
... done with file
processing network-basic
... done with zstd
processing perl-basic
... done with perl-basic
processing findutils
... done with network-basic
processing ethtool
... done with findutils
processing os-core-update
... done with os-core-update
processing auditd
... done with auditd
processing less
... done with less
processing wpa_supplicant
... done with wpa_supplicant
processing logrotate
... done with logrotate
processing powertop
... done with powertop
processing kbd
... done with ethtool
processing smartmontools
... done with kbd
processing nfs-utils
... done with smartmontools
processing xfsprogs
... done with nfs-utils
processing patch
... done with xfsprogs
processing tmux
... done with patch
processing iproute2
... done with tmux
processing suricata
... done with iproute2
processing telemetrics
... done with suricata
processing znc
... done with telemetrics
processing openssl
... done with znc
processing pmdk
... done with pmdk
processing sysadmin-basic
... done with sysadmin-basic
processing htop
... done with htop
processing sudo
... done with sudo
processing nagios
... done with nagios
processing curl
... done with curl
... done with openssl
Resolving files using 2 workers
processing kbd
processing smartmontools
Bundle smartmontools	523 files
processing nfs-utils
Bundle kbd	1092 files
processing xfsprogs
Bundle xfsprogs	362 files
processing patch
Bundle patch	284 files
processing tmux
Bundle tmux	1243 files
processing telemetrics
Bundle telemetrics	1591 files
processing znc
Bundle nfs-utils	1564 files
processing iproute2
Bundle znc	1436 files
processing suricata
Bundle iproute2	572 files
processing sysadmin-basic
Bundle suricata	9144 files
processing htop
Bundle htop	659 files
processing openssl
Bundle sysadmin-basic	23676 files
processing pmdk
Bundle openssl	1227 files
processing curl
Bundle curl	1485 files
processing sudo
Bundle sudo	440 files
processing nagios
Bundle nagios	1534 files
processing acpica-unix2
Bundle acpica-unix2	280 files
processing storage-utils
Bundle storage-utils	4425 files
processing dosfstools
Bundle dosfstools	535 files
processing irssi
Bundle pmdk	607 files
processing syslog-ng
Bundle irssi	3492 files
processing gdb
Bundle gdb	979 files
processing gzip
Bundle syslog-ng	1674 files
processing kernel-install
Bundle gzip	90 files
processing unzip
Bundle kernel-install	63 files
processing openssh-server
Bundle unzip	282 files
processing git
Bundle openssh-server	1497 files
processing os-core-webproxy
Bundle git	1950 files
processing xz
Bundle os-core-webproxy	3446 files
processing kernel-native
Bundle xz	346 files
processing os-core
Bundle kernel-native	6625 files
processing python3-basic
Bundle os-core	3107 files
processing strace
Bundle python3-basic	4743 files
processing weechat
Bundle strace	2348 files
processing bootloader
Bundle weechat	3646 files
processing parallel
Bundle parallel	2573 files
processing bro
Bundle bro	5028 files
processing tzdata
Bundle tzdata	1903 files
processing essentials
Bundle essentials	347 files
processing p11-kit
Bundle p11-kit	1227 files
processing which
Bundle which	275 files
processing zstd
Bundle zstd	323 files
processing network-basic
Bundle network-basic	10888 files
processing diffutils
Bundle diffutils	385 files
processing file
Bundle file	292 files
processing auditd
Bundle auditd	4124 files
processing less
Bundle less	655 files
processing wpa_supplicant
Bundle wpa_supplicant	1679 files
processing logrotate
Bundle bootloader	339 files
processing perl-basic
Bundle logrotate	287 files
processing findutils
Bundle perl-basic	4735 files
processing ethtool
Bundle findutils	410 files
processing os-core-update
Bundle ethtool	278 files
processing powertop
Bundle os-core-update	3912 files
Bundle powertop	959 files
Cleaning DNF cache before full install
Installing all bundles to full chroot
[1/55] nagios
[2/55] curl
[3/55] sudo
[4/55] dosfstools
[5/55] acpica-unix2
[6/55] storage-utils
[7/55] irssi
[8/55] gdb
[9/55] syslog-ng
[10/55] git
[11/55] gzip
[12/55] kernel-install
[13/55] unzip
[14/55] openssh-server
[15/55] os-core
... building special os-core content
[16/55] os-core-webproxy
[17/55] xz
[18/55] kernel-native
[19/55] strace
[20/55] python3-basic
[21/55] parallel
[22/55] weechat
[23/55] bootloader
[24/55] which
[25/55] bro
[26/55] tzdata
[27/55] essentials
[28/55] p11-kit
[29/55] file
[30/55] zstd
[31/55] network-basic
[32/55] diffutils
[33/55] os-core-update
... Adding swupd default values to os-core-update bundle
[34/55] auditd
[35/55] less
[36/55] wpa_supplicant
[37/55] logrotate
[38/55] perl-basic
[39/55] findutils
[40/55] ethtool
[41/55] powertop
[42/55] kbd
[43/55] smartmontools
[44/55] nfs-utils
[45/55] xfsprogs
[46/55] patch
[47/55] tmux
[48/55] suricata
[49/55] telemetrics
[50/55] znc
[51/55] iproute2
[52/55] pmdk
[53/55] sysadmin-basic
[54/55] htop
[55/55] openssl
2019/01/18 00:52:38 
TIMINGS
2019/01/18 00:52:38   BUILD BUNDLES 2m3.716s
2019/01/18 00:52:38 TOTAL: 2m3.716s
 Copying +20 bundles to +10 bundles
2019/01/18 00:52:39 ERROR: Couldn't build update: invalid format
2019/01/18 00:52:39 ERROR: failed to execute mixer build format-bump old --new-format  --native: exit status 1

Now mixer cannot also finish the mixer build all as well.

Let me know what other useful kinds of debug information I should collect to help troubleshoot it. The summary here would be that I cannot upgrade anymore and that's kinda bad :)

**Comment by rchiossi** [comment]
One thing that looks weird in that log is the fact that mixer is trying to update from 27310 to 27310. Did you already have a successful build based on 27310?

**Comment by mpurzynski** [comment]
I had not, I just tried to run the same command several times. Should I change the version manually somewhere, to avoid confusion?

**Comment by mpurzynski** [comment]
Wish I knew - I do not remember and there does not seem to be any evidence left.

Maybe I could manually downgrade the upstream version for my mix to build against, i.e. tell it to build against the last version before the format change?

**Comment by rchiossi** [comment]
You can find the upstream version inside the update folder from your last good build. Check `update/www/$LAST_GOOD_BUILD/upstreamver` file

**Comment by mpurzynski** [comment]
Looks like it was 27160

for i in {1100..1200}; do if [ -f update/www/$i/upstreamver ]; then echo -n $i ; echo -n " " ; cat update/www/$i/upstreamver; echo ""; fi ; done;

1100 26280
1120 27160
1140 27160
1160 27160

1170 27210 <-- this failed

**Comment by mpurzynski** [comment]
The LAST_VER file is on 1160 that corresponds to the 27160 upstream, too.

**Comment by rchiossi** [comment]
After some testing it seems that there is a bug in mixer that will need to be addressed in a new release. We will publish a new release today with some fixes, but for the time being you will need to to a manual format bump. Note that this requires the new mixer that will be published in a couple hours from now.

First, you need to reverse your mix prior to the error. The instructions below assume that the format for build `1160` was `26`. You can check that by reading the contents of `update/www/1160/format`. If you have any other value, just use it instead. Also, if you have a different value, replace any mention to `27` to `your_value+1`.

- Make sure `FORMAT` in `mixer.state` has the same value as `update/www/1160/format`
- Change `upstreamversion` file content to the previous version, in this case `27160`
- Make sure update/image/LAST_VER` points to the last good build, in this case `1160`
- Remove any folder inside `update/image` for versions above `1160`
- Remove any forlder inside `update/www` for versions above `1160`
- Make sure `update/www/version/format26/latest` point to the last good build, in this case `1160`
- Remove any folders inside `update/version/` for formats above 26
- Change `mixversion` to point to the last good build, in this case 1160`

At this point you should be back to the starting point. To perform a bump we need to generate two builds, 1170 and 1180 that are based on the last build of the old format and the first build of the new format. 
To build 1170 run the following commands:
- `mixer versions update --upstream-version 27200`
- `sudo mixer build bundles --native`
- `sudo sed -i 's/\(VERSION_ID=\).*/\11180/' update/image/1170/full/usr/lib/os-release`
- `sudo sh -c 'echo -n 1180 > update/image/1170/full/usr/share/clear/version'`
- `sudo sh -c 'echo 27 > update/image/1170/full/usr/share/defaults/swupd/format'`
- `sudo mixer build update --native`

Now build 1180:
- `sudo sh -c 'echo 27210 > upstreamversion'`
- `sudo sh -c 'echo 1180 > mixversion'`
- `sed -i 's/\(FORMAT\).*/\1 = "27"/' mixer.state`
- `sudo cp -al update/image/1170 update/image/1180`
- `sudo mixer build update --native --min-version 1180 --offline`

Note that this is an adaptation of the full format bump process exemplified in this reference script: https://github.com/clearlinux/mixer-tools/blob/master/afb.sh

From this point forward you should be able to update your mix normally with `mixer versions update --upstream-version latest`

**Comment by rchiossi** [comment]
I believe I found a much simpler solution that already works with the current version of mixer. 
So, performe the cleanup as described above and then run these commands:
- `mixer versions update --upstream-version 27390`
- `sudo mixer build upstream-format --new-format 27`

**Comment by mpurzynski** [comment]
I'm doing the cleanup and it seems like my

update/www/1160/format has 2 in it

What is also strange is that I have

ls update/www/version/format*

update/www/version/format:

(this directory is empty)

update/www/version/format1:
latest

cat update/www/version/format1/latest 
1070

**Comment by rchiossi** [comment]
First off, the format value can be any number. If you are running mixer on clearlinux, it will default to the same format clear is using, if not, it will default to 1. This value has no relation to the upstream format, so the fact that your format value is 1 is totally normal. Just use 1 and 2 instead of 26 and 27 in my instructions.

Now, if you've never been through a format bump before, than your format should be the same since the very first build you've made. This makes me think that 1070 is actually your last good build since it is the last one on format 1. Are the folders for the other releases populated and if so, are they of a similar size as the 1070 and previous ones?

**Comment by mpurzynski** [comment]
I'm happy to report I have followed all the steps and now my mix is synced with the newest upstream!

A test-upgrade went well on several systems and everything seems to be fine. I aligned local format numbers with upstream, to keep things simple.

It's my second format bump and the second that went south - but maybe it's my inexperience speaking out here as well.

Thanks a lot for the help - this level of support is simply unmatched!

**Comment by rchiossi** [comment]
I'm glad to know that your mix is back on track!

Sadly, those problems with format bumps are not uncommon. From what you can tell from my description of the manual bump process, it is fairly complicated to bump a downstream mix and we are committed to provide a more transparent way for our users to go through it. The current implementation was our first step towards this direction but there are still a lot to do.

From our interaction it seems clear to me that mixer could benefit from some sort of **cleanup** or **rollback** commands to get back to the last good build. That is something that I'll will look into implementing.

Working with our users help us find those areas were mixer is still lacking, so thanks for working through this issue with us.
