### ISSUE TITLE
Config parsing

### ISSUE THREAD

**Issue by kevincwells** [clearlinux/mixer-tools#54]
# Proposal
Rewrite the mixer code that parses `builder.conf` using the [Viper library](https://github.com/spf13/viper).

# Benefits
- Remove fragile regex-based parsing
- Correctly support config "Section" to value affiliation (right now sections are ignored)
- Allow easy generation of default `builder.conf`
- Integrate with Cobra to fluidly support CLI flag overrides of config values (optional).

# Notes
Viper will treat `builder.conf` as a TOML file. Technically, as it is read by `bundle-chroot-builder.py`, which relies on the Python [ConfigParserr](https://docs.python.org/3/library/configparser.html) library, it is not a full TOML file, and instead limited to the subset INI format. This should not be a problem with current usage.

**Comment by cmarcelo** [comment]
I would take the opportunity to:
- Remove any unused or redundant configurations if still exist
- Review the names of the configurations (get feedback from people working on the tools around)
- Review how we handle the default values: my overall impression is that the configuration feels repetitive, most of time there'll be a "main" work directory and I'm fine with all the default names for the subdirectories

(I also think is fine to split this off into a separate task, but felt it fits the overall config theme).

**Comment by tmarcu** [comment]
@rchiossi working on this right now.

**Comment by tmarcu** [comment]
@rchiossi close this ?

**Comment by rchiossi** [comment]
Yep. Closing.
