### ISSUE TITLE
Hash Mismatch for os-core-update-index Bundle in MoM

### ISSUE THREAD

**Issue by jwakre** [clearlinux/mixer-tools#541]
Sometimes, after an update where the os-core-update-index bundle has not been changed, the bundle hash entry in the MoM will not match the hash from the previous MoM.

This issue has occurred in the following versions of Clear:

27230->27240
27530->27540

Note: These errors started after the introduction of iterative manifests which did make changes to index manifests.

**Comment by gtkramer** [comment]
When this issue occurs, it is an automatic no-go for DevOps because we cannot release a build with a hash mismatch.  Users with the os-core-update-index bundle installed would not be able to update to that build.

**Comment by otaviobp** [comment]
As we have discussed the new plan is to deprecate the index by generating an Manifest that will install and empty index and remove all pending files, i.e.:
 - if the previous index exists and it's not empty, we generate an empty index
 - if the previous index doesn't exist we don't generate any index
 - if the previous index is an empty index, we just point to it in the new MoM
