### ISSUE TITLE
swupd doesn't work inside mix.

### ISSUE THREAD

**Issue by c-edw** [clearlinux/mixer-tools#545]
I'm not sure where the best place to file this issue would be.

I've created an image with mixer and booted it, but can't use `swupd`. I think this is because `curl` is missing from the system. Here's some example output:

```
$ swupd bundle-add network-basic
Curl error: (3) URL using bad/illegal format or missing URL
Trying fallback CA path /usr/share/ca-certs/.prebuilt-store/anchors
Curl error: (3) URL using bad/illegal format or missing URL
Failed updater initialization, exiting now.
```

Since `swupd` depends on `curl`, should it not be a component of the base system?

Thanks.

**Comment by rchiossi** [comment]
Did you set upstream url to point to your server (where you are hosting the packages) when you created the mix?

**Comment by c-edw** [comment]
I left it as it is in the example since I'm not interested in hosting my own packages:

``
  CONTENTURL = "<URL where the content will be hosted>"
  VERSIONURL = "<URL where the version of the mix will be hosted>"
```

Also - I just realised those errors are probably from libcurl.

**Comment by rchiossi** [comment]
If you are not hosting your own packages, then mixer is probably not the right tool for you. Once you create a mix, you are creating a derivative OS. When you create a mix you define which packages will be available for your deirative OS' swupd to get. Note that the mix contains all packages, but you can use an arbitrary number of them to generate an image from your mix image. A mix relies on its own server to get content from, it will not be able to download packages from upstream.

If all you want is a custom image using upstream packages, then clear-installer is the way to go: https://github.com/clearlinux/clr-installer

**Comment by c-edw** [comment]
Sorry, I should have been more clear. I'm not interesting in hosting my own packages *right now*. I'm still getting familiar with the tool. I wasn't aware of clr-installer before, but it doesn't look like it will give the level of control I'm looking for.

**Comment by rchiossi** [comment]
I see. `swupd` uses `libcurl` to download packages. It seems to me that the error comes from the fact that there is no valid URL for it to get the packages from. It is trying to access something like `http://<URL where the content will be hosted>/update/27700/pack-network-basic-dev-from-0.tar` since that was the value of content url when you created the mix.

**Comment by c-edw** [comment]
Yep, that's what I had figured too. Maybe the config could have some basic validation checks at build time? The better solution IMO would be for swupd to print a better error message.

**Comment by rchiossi** [comment]
There are use cases where that URL is not needed, e.g. embedded devices that are always reflashed when a new image is released. Still, I agree on the error message. @otaviobp is there an open issue on swupd to track improvements on error messages or should we open a new one?

**Comment by otaviobp** [comment]
>   CONTENTURL = "<URL where the content will be hosted>"
>   VERSIONURL = "<URL where the version of the mix will be hosted>"

@rchiossi When the content and version url is not set on a mix we shouldn't add them to contenturl and versionurl file in the system. But not sure what's the best approach for that. Maybe preventing users to include os-clear-update if the URL is not set.

> There are use cases where that URL is not needed, e.g. embedded devices that are always reflashed when a new image is released.

In this case swupd won't work as expected. If you install one image from a mix and try to bundle-add, update or any other swupd command pointing to the upstream CL server you may have serious issues. For the embedded case where you only provide full images, I don't see a reason to provide swupd to the users.

**Comment by otaviobp** [comment]
> is there an open issue on swupd to track improvements on error messages or should we open a new one?

No, but we have changed this message for the next release. In this case that would be:

Error: Failed to connect to update server: <URL where the version of the mix will be hosted>
Possible solutions to this problem are:
	Fix the system clock
	Run 'swupd info' to check if the urls are correct
	run  'clrtrust generate' to regenerate SSL certificates
Failed verify initialization, exiting now.

Is this clear for you?

**Comment by c-edw** [comment]
That's much more clear. I would personally opt to print out the update server URL, although it looks like that can be viewed with `swupd info`. Thanks.

**Comment by otaviobp** [comment]
Sorry, I failed when I copied and paste that from the source code. It's printing the url as you said

**Comment by c-edw** [comment]
Alright, that's great. Thanks a lot man :+1:. Closing this.
