### ISSUE TITLE
Add support for Manifest Correctness Check (MCA)

### ISSUE THREAD

**Issue by jwakre** [clearlinux/mixer-tools#546]
The goal of MCA is to verify that Mixer generates manifests correctly between 2 versions based on the contents of the RPMs that it consumes. From a high level, MCA will be composed of the following steps:

1. Compute RPM data differences
2. Compute manifest data differences
3. Compare RPM/manifest data differences to validate that they match
4. Report results

**Comment by rchiossi** [comment]
@gabibeyer can you provide information to @jwakre on this project? He will be responsible for the port.

**Comment by jwakre** [comment]
Closed by #555
