### ISSUE TITLE
swupd library fails to parse 0-file iterative manifests

### ISSUE THREAD

**Issue by evil-brain** [clearlinux/mixer-tools#547]
When importing the swupd library, and parsing a zero-file-length iterative manifest, parsing fails and returns an error.
Here's an example program that shows this behavior:
https://github.com/evil-brain/test_program
The program expects two files to be in same directory as the executable - so 'go get' this and then be sure to either copy the files or go to $GOPATH/src/github.com/evil-brain/test_program and run 'go build'.

Here's a patch that fixes the problem:
https://gist.github.com/evil-brain/ddad4ef46e565b5c9cf9ec6187588d1d
...but it's not perfect, because it changes the API. This is necessary because the type information is coded in the file name of the manifest, and there's no way I can find to get this info from an io.Reader.
Probably not the best solution, but I can put it in a PR and start massaging it into something that will work.

**Comment by otaviobp** [comment]
When we introduced the I/D manifests we had a discussion about allowing or not empty manifest files. I remember we had a use case for empty Delta manifests, but not for empty Iterative manifests.

Is this empty Iterative manifest real? What is the scenario where we have an  update but no new files?

**Comment by jwakre** [comment]
> When we introduced the I/D manifests we had a discussion about allowing or not empty manifest files. I remember we had a use case for empty Delta manifests, but not for empty Iterative manifests.
> 
> Is this empty Iterative manifest real? What is the scenario where we have an update but no new files?

The empty iterative manifest was a bug fix for the case when a bundle's includes section was updated without any file changes.

**Comment by otaviobp** [comment]
> The empty iterative manifest was a bug fix for the case when a bundle's includes section was updated without any file changes.

It makes sense. Thanks

**Comment by jwakre** [comment]
There is already a function called _ParseManifestFile_, so I think we shouldn't make _ParseManifest_ accept a file path as an argument. Maybe it would be better to add an argument to _ParseManifest_ that specifies the manifest type because it cannot be determined by reading the manifest.

**Comment by evil-brain** [comment]
> so I think we shouldn't make ParseManifest accept a file path as an argument.

ParseManifestFile just calls ParseManifest after os.Open'ing the passed-in path. There's an implicit cast when calling ParseManifest (os.File to os.Reader). By that I mean, I'm not suggesting passing the path to ParseManifest directly/I agree.

We could absolutely change ParseManifest and require a ManifestType parameter. I don't really have a preference at this point, I just want Diva to be able to parse recent Clear releases. :smile:

What should I do if I were to make a PR? My number 1 concern is breaking whoever is already a customer of the swupd lib.

**Comment by jwakre** [comment]
> What should I do if I were to make a PR? My number 1 concern is breaking whoever is already a customer of the swupd lib.

I don't who consumes individual Mixer packages or how strict we are on breaking them. @rchiossi probably has an opinion on which approach to take for your PR to be accepted.

**Comment by reaganlo** [comment]
Iterative manifests has been deprecated.
