### ISSUE TITLE
Enforce `/opt` folders are not allowed, as well as `/usr/local`

### ISSUE THREAD

**Issue by ahkok** [clearlinux/mixer-tools#548]
See: https://github.com/clearlinux/distribution/issues/483

A user was able to mix files in `/opt` which results in `swupd` correctly removing the folder structure. Both Mixer and swupd are following design, and `/opt/` and `/usr/local` should have not been allowed to be mixed.

**Comment by bryteise** [comment]
I'm inclined to say it should be configurable, something like blacklist folders. Some mixer users may want to have control over the entire rootfs. They will need to configure swupd-client to match though and probably we should default to not allowing /opt or /usr/local.

**Comment by aaronovz1** [comment]
We use `/opt` for installing our applications, this decision was based on the [Filesystem Hierarchy Standard](http://www.pathname.com/fhs/pub/fhs-2.3.html#OPTADDONAPPLICATIONSOFTWAREPACKAGES). So I think it should be configurable.

**Comment by ahkok** [comment]
For now I think we should make mixer/mixing error out. We can work on a solution later, but this also means swupd is patched as well.

**Comment by ahkok** [comment]
@aaronovz1 `/opt` is, and should remain reserved for `third-party` software. Mixer and Mixin are not providers of `third party` software, hence the conflict. The third-party application is perfectly fine to be shipping in `/opt`, but mixer and mixin are not the proper packaging/distribution tools for them, since they are (designed for, and properly implementing) for packaging distribution software, not third-party software.

**Comment by rchiossi** [comment]
> For now I think we should make mixer/mixing error out. We can work on a solution later, but this also means swupd is patched as well.

I agree that for now marking the package as invalid and printing an explanation with the error (just like we do por proxy error) is a good approach. I'll look into it.

**Comment by reaganlo** [comment]
@ahkok @bryteise Since we are going to support building 3rd party software using mixer, is this requirement still valid?

**Comment by bryteise** [comment]
I think that it depends on how 3rd-party building with mixer looks. The main distro policy still holds that non-stateless folders like /opt aren't allowed. The distro has other ways of validating this though so it is perhaps not something that needs to be in mixer.

**Comment by ahkok** [comment]
Honestly I think the hard rules we have for `/opt`, `/etc` and others shouldn't apply to anything 3rd party. We'd want to encourage people to avoid making a mess, but really, we should not prevent users from making 3rd party repos that install stuff into `/etc` or `/opt`.

**Comment by ahkok** [comment]
I think my previous comment was reasonable in light of the changes:

> `/opt` is, and should remain reserved for third-party software.

Still stands

> Mixer and Mixin are not providers of third party software, hence the conflict.

This obviously is no longer the case, with mixer being a provider of 3rd party content.

**Comment by reaganlo** [comment]
Closing this as mixer now supports 3rd party content in /opt
