### ISSUE TITLE
mixer init --clear-version may need a change in the wording

### ISSUE THREAD

**Issue by LibertadCruz** [clearlinux/mixer-tools#550]
So, I have read some issues like (#153 #123 ) merged about the --clear-version flag and the default that it should be assigned. I read that before it accepted integer and the default was 1 but now it says it accepts strings and the default is "latest". 

The thing is that now as is, I as a user am tempted to introduce something like:

mixer init --clear-version 28000s  

and that would fail with a message: 

Error: invalid argument "28000s" for "--clear-version" flag: strconv.Atoi: parsing "28000s": invalid syntax

As I user I understand that according to the "mixer init -h"  I can introduce a string other than latest and it should not fail.  Plus the man mixer.init does not specify if it can be string or int.

I think idealy a user should be restricted and limited in his input to any option. Ideally it should be by code.

**Comment by LibertadCruz** [comment]
so, my point is documentation the wording to let the user know that it should be a valid clear version  and it should be integer

**Comment by reaganlo** [comment]
Has been fixed.
