### ISSUE TITLE
os-core-update-index bundle is too big and unused

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/mixer-tools#559]
This bundle was an attempt to make metadata available to improve search and other queries, but I don't think it was ever used, besides people reading the files directly. It has some problems at the moment:

- It does include a list of all files in each bundle. While this is useful, it is also expensive. The bundle has about 800M nowadays.
- The representation of the file list is actually a map from files to boolean, and they are always true, so we have a `: true` in every line.

For the reference, the open issues related to os-core-update-index:

- "Use it for search" https://github.com/clearlinux/swupd-client/issues/394
- "Use it for getting bundle info" https://github.com/clearlinux/swupd-client/issues/461
- A bug! https://github.com/clearlinux/mixer-tools/issues/541

**Comment by otaviobp** [comment]
+1 for removing that. no plans to use them on search anymore.

**Comment by miguelinux** [comment]
Do we have a replacement for it?

**Comment by gtkramer** [comment]
Not only is it unused, but it is buggy #541 and has the potential to block release engineering from publishing builds.

**Comment by reaganlo** [comment]
os-core-update-index bundle has been deprecated in Mixer v6.0.0 by the PR https://github.com/clearlinux/mixer-tools/pull/636
