### ISSUE TITLE
Support OS identification modification for downstream build

### ISSUE THREAD

**Issue by sweeaun** [clearlinux/mixer-tools#560]
Suggest to create a new section in builder.conf to support OS identification data for downstream Clear Linux build. Allow Mixer be more friendly to downstream Clear Linux build by allowing custom modification on os-release.

Current default Clear Linux filesystem os-release is configured as below. Only VERSION_ID will be used during mixer version build which it store the mixversion value, the rest will be remain the same. 

NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=1
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"

Suggest a new section [Os] can be added into builder.conf configuration file.
New section allow user to configure NAME, VERSION, ID, ID_LIKE, PRETTY_NAME, ANSI_COLOR, HOME_URL, SUPPORT_URL, BUG_REPORT_URL and PRIVACY_POLICY_URL for downstream Clear Linux build if user provide the customized value in builder.conf. Take note that new section will not modify the VERSION_ID since it will be used by Mixer for mixverion. 

Example for [Os] section in builder.conf that change NAME, VERSION and ID:

[Os]
 NAME = “Clear Linux OS – Customized ”
 VERSION = “2”
 ID = “clear-linux-os-customized ”

**Comment by reaganlo** [comment]
@rchiossi Is this still high priority?

**Comment by rchiossi** [comment]
This has already been integrated. It is the `OS_RELEASE_PATH` option introduced in config version 1.1
