### ISSUE TITLE
Mixin or Mixer to replace a system library?

### ISSUE THREAD

**Issue by yaroslavros** [clearlinux/mixer-tools#566]
Trying to customise a fresh clear linux installation with a custom build of OpenSSL (with RC4 enabled for backwards RDP compatibility).

Generating new RPMs was very straightforward thanks to autospec tool, but hit a wall with both mixer and mixin. Not sure if I am running into a bug or is this expected behaviour.

Mixin seemed to be natural way to mixin my own openssl bundle. I followed process outlined at https://clearlinux.org/documentation/clear-linux/guides/maintenance/mixin

$ sudo mixin repo add mylocalrepo file://${HOME}/mixin-repo/
Added mylocalrepo repo at file:///home/yaroslav/mixin-repo/ url.
$ sudo mixin package add openssl --bundle openssl
2019/04/14 18:53:56 Warning: Using FORMAT value from /usr/share/defaults/swupd/format
Initializing mix version 28830000 from upstream version 28830
Adding bundle "os-core" from upstream bundles
Created bundle "openssl" in "/usr/share/mix/local-bundles"
Adding bundle "openssl" from local bundles
Added openssl package to openssl bundle.

Mixin build went smoothly
[mixin.log](https://github.com/clearlinux/mixer-tools/files/3077693/mixin.log)

However swupd is not happy about findutils manifest:
$ sudo swupd update --migrate
Attempting to migrate to your mix content...

Update started.
Preparing to update from 28830 to 28830000
Warning: hash check failed for Manifest.findutils for version 28830000. Deleting it.
Warning: Removing corrupt Manifest.findutils artifacts and re-downloading...
Warning: Downloading missing manifest for bundle findutils version 28710.
Warning: hash check failed for Manifest.findutils for version 28830000. Deleting it.
Error: Cannot load server MoM sub-manifests, exiting
Update took 0.7 seconds, 0 MB transferred
Update failed.

Is this a bug, misconfiguration or expected behaviour of mixin attempting to replace an upstream bundle?

I tried to use mixer instead of mixin. It happily accepted openssl RPMs from local-rpms and correctly generated packages. I had no issues with swupd migration to local tree.
However, it seems that upstream bundles are not automatically mixed in by mixer and enabling "--all-upstream" makes mixer build and update processes running for many hours with ~75G resulting mixer tree.
Is this expected behaviour of mixer?

Is there any supported way to replace/customise a system library with a custom build/RPM?

**Comment by jwakre** [comment]
Your custom bundle is named  **openssl** which conflicts with an existing bundle name. When I add a bundle called openssl with Mixin, I can replicate this error. Can you try changing the name?

Also, Mixin currently has a number of bugs, so it is possible to encounter issues with it.

**Comment by yaroslavros** [comment]
Tried starting from scratch and adding openssl to a different bundle name:
```
# sudo mixin package add openssl --bundle customopenssl
2019/04/16 00:26:32 Warning: Using FORMAT value from /usr/share/defaults/swupd/format
Initializing mix version 28830000 from upstream version 28830
Adding bundle "os-core" from upstream bundles
Created bundle "customopenssl" in "/usr/share/mix/local-bundles"
Adding bundle "customopenssl" from local bundles
Added openssl package to customopenssl bundle.
```

Build went successfully and this time mixin did not replace findutils lib-openssl or p11-kit bundles, just customopenssl, os-core and os-core-update-index:
```
# sudo mixin build
00:26:50: Version: 0.12.2 (Features: LegacyWeakdeps )
00:26:50: Signal handler setup
00:26:50: Thread pool ready
00:26:50: Dir to scan: ./.repodata
00:26:50: Package count: 0
00:26:50: No packages found - skipping metadata loading
00:26:50: Creating .xml.gz files
00:26:50: Setting number of packages
00:26:50: Creating databases
00:26:50: Thread pool user data ready
00:26:50: Generating repomd.xml
00:26:50: Old repodata doesn't exists: Cannot rename ./repodata/ -> ./repodata.old.1055.20190416002650.824729: No such file or directory
00:26:50: Renamed ./.repodata/ -> ./repodata/
00:26:50: Memory cleanup
00:26:50: All done
Generating certificate for signature validation...
Building bundles...
2019/04/16 00:26:55 => BUILD BUNDLES
Creating bundles for version 28830000 based on Clear Linux 28830
Preparing new /usr/share/mix/update/image/28830000
  and dnf config: /usr/share/mix/.yum-mix.conf
Packager command-line: dnf --config=/usr/share/mix/.yum-mix.conf -y --releasever=28830
Resolving packages using 8 workers
processing customopenssl
processing os-core
... done with customopenssl
... done with os-core
Resolving files using 8 workers
processing customopenssl
processing os-core
Bundle customopenssl	1245 files
Bundle os-core	2768 files
Cleaning DNF cache before full install
Installing all bundles to full chroot
[1/2] customopenssl
[2/2] os-core
... building special os-core content
... Adding swupd default values to os-core bundle
2019/04/16 00:27:29
TIMINGS
2019/04/16 00:27:29   BUILD BUNDLES 33.552s
2019/04/16 00:27:29 TOTAL: 33.552s
2019/04/16 00:27:29 => CREATE MANIFESTS
Generating initial manifests...
  customopenssl
  os-core
Reading bundle includes...
Performing manifest file subtraction...
Detecting manifest changes...
Writing manifest files...
MoM version 28830000
- customopenssl        28830000
- os-core              28830000
- os-core-update-index 28830000
Signing manifest.
Compressing Manifest.MoM
Compressing bundle manifests
  customopenssl
  os-core-update-index
  os-core
  full
2019/04/16 00:27:29 &{0xc00006a0c0}
2019/04/16 00:27:29 => CREATE FULLFILES
Using 8 workers
- Already created: 0
- Not compressed:  0
- Compressed
  - external-gzip        854
  - external-bzip2       94
  - gzip                 325
  - external-xz          1085
Total fullfiles: 2358
2019/04/16 00:27:35 &{0xc00006a0c0}
2019/04/16 00:27:35 => CREATE ZERO PACKS
Creating zero pack for customopenssl to version 28830000
  Fullfiles in pack: 229
  Deltas in pack: 0
Creating zero pack for os-core to version 28830000
  Fullfiles in pack: 2268
  Deltas in pack: 0
Creating zero pack for os-core-update-index to version 28830000
  Fullfiles in pack: 4
  Deltas in pack: 0
Saving the upstream URL: https://cdn.download.clearlinux.org
Saving the upstream version: 28830
Setting latest version to 28830000
2019/04/16 00:27:43
TIMINGS
2019/04/16 00:27:43   CREATE MANIFESTS  541ms
2019/04/16 00:27:43   CREATE FULLFILES  5.793s
2019/04/16 00:27:43   CREATE ZERO PACKS 8.349s
2019/04/16 00:27:43 TOTAL: 14.684s
* Verified upstream Manifest.MoM
Successfully built mix content
```

swupd migrate did not report any issues:
```
# sudo swupd update --migrate
Attempting to migrate to your mix content...

Update started.
Preparing to update from 28830 to 28830000
Downloading packs...
	...100%

Statistics for going from version 28830 to version 28830000:

    changed bundles   : 1
    new bundles       : 0
    deleted bundles   : 0

    changed files     : 2770
    new files         : 0
    deleted files     : 0

Starting download of remaining update content. This may take a while...
	...100%
Finishing download of update content...
Staging file content
Applying update
	...100%
Update was applied.
Calling post-update helper scripts.
Update took 2.1 seconds, 0 MB transferred
Update successful. System updated from version 28830 to version 28830000
```

Adding customopenssl bundle pretended to work smoothly:
```
# swupd bundle-add customopenssl
Starting download of remaining update content. This may take a while...
	...100%
Finishing download of update content...
Installing bundle(s) files...
	...100%
Calling post-update helper scripts.
Successfully installed 1 bundle
```

However actual openssl binary was not changed (I guess due to clearlinux/swupd-client#863).
And even if a custom bundle overwrites a binary provided by an upstream bundle, would upgrade of the upstream bundle not revert it back?
I think ability to replace upstream bundles is essential for mixin. There is a number of potential use cases when a user might want to have own variant of openssl (or any other upstream library) without having to spend many hours in building a completely separate mixer-based repository that would similarly take many hours to upgrade.

**Comment by rchiossi** [comment]
The main problem here is that Clearlinux does not have the concept of package version, but rather of system version. A clear linux version is a collection of package versions that are locked in place. Updating a package will change this invariant list, which means the system version must also be updated.

The most stable way of doing so at the moment is to have your own custom mix built with mixer, but that is indeed overkill if you just want to update a single package. Mixin was created to try to cover that use case and go into the direction of a "ppa style" content management, but it is still a long way to go to  achieve similar user experience. Mixin uses mixer apis so it is performing the same actions that mixer would, with added quality of life facilities to simplify the update.

> And even if a custom bundle overwrites a binary provided by an upstream bundle, would upgrade of the upstream bundle not revert it back?

When upstream updates a package a new upstream version is generated. This means that you will only get an update for the package you replaced if you update the upstream version your system is based on. This means that mixin will have to redo all the work it did initially to create your local custom mix, and in the process it will overwrite the upstream package again with your custom one.

**Comment by yaroslavros** [comment]
This is perfectly fine since mixin takes few minutes at most (mixer for full upstream bundle tree takes many hours).
It seems that the bug is that if an upstream bundle is "upgraded" with a custom one during mixin process, it fails manifest hash check during swupd migration despite the fact that new version number (28830000 in my case) is consistent. Not sure if the bug is on mixin or swupd side.

Anything I can do to help fix this?

**Comment by yaroslavros** [comment]
I think I have located root cause of the issue. Swupd does not care about bundle manifest version in MoM and picks up the first one (which makes sense).
In case of upstream bundle replacement, mixin should leave only custom bundle and remove upstream manifest from MoM.

Pull request submitted.
