### ISSUE TITLE
contentsize calculation issue

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/mixer-tools#568]
For two identical mixes, the contentsize manifest header values should always match. However, I am seeing some unexpected mismatches. See steps below.

Steps to reproduce:

1. mkdir mix1; cd mix1
2. mixer init --native --upstream-version=29040
3. mixer bundle add os-clr-on-clr
4. sudo mixer build bundles --native
5. sudo mixer build update --native --skip-fullfiles --skip-packs --no-publish
6. cd ..
7. mkdir mix2; cd mix2
8. sudo cp ../mix1/*.pem .
9. repeat steps 2-5
10. cd ..
11. Check for contentsize differences. I used the script below for this purpose, which ignores several expected differences:. much of the `os-core-update-index` manifest, the `timestamp` header values in all manifests, and the `/usr/share/clear/versionstamp` file from `os-core`.

```
for m in $(awk '/^M./ { if ($4 == "os-core-update-index") next; print $4 }' mix1/update/www/10/Manifest.MoM); do
  out=$(diff -U0 mix{1,2}/update/www/10/Manifest.$m | tail -n +4 | grep -Ev '(^@|[+-]timestamp|/usr/share/clear/versionstamp$)') && echo -e "$m diff:\n$out"
done
```

**Comment by phmccarty** [comment]
For my test run, I see the following contentsize differences:

```diff
Babel diff:
-contentsize:   26789137
+contentsize:   26793233
c-basic diff:
-contentsize:   450777984
+contentsize:   450782080
containers-basic diff:
-contentsize:   477010033
+contentsize:   477014129
fonts-basic diff:
-contentsize:   231851271
+contentsize:   231843079
global diff:
-contentsize:   3286945
+contentsize:   3291041
httpd diff:
-contentsize:   45135400
+contentsize:   45139496
lib-samba diff:
-contentsize:   84766849
+contentsize:   84770945
libX11client diff:
-contentsize:   157874869
+contentsize:   157887157
mutt diff:
-contentsize:   16231581
+contentsize:   16235677
openldap diff:
-contentsize:   6361005
+contentsize:   6365101
os-installer diff:
-contentsize:   108732253
+contentsize:   108736349
perl-basic diff:
-contentsize:   85825418
+contentsize:   85833610
texlive diff:
-contentsize:   2900725068
+contentsize:   2900708684
```

**Comment by phmccarty** [comment]
@jwakre has started looking into this bug.

**Comment by jwakre** [comment]
Some packages do not install directories with consistent sizes. After talking with @phmccarty it was decided to hardcode the content size for directories in Mixer to 4096 to make mixes reproducible. Also, the hardcoded directory content size approach was used by swupd-server.
