### ISSUE TITLE
Proposal: Automate Ister config file

### ISSUE THREAD

**Issue by kevincwells** [clearlinux/mixer-tools#58]
# Proposal
Change mixer to automate the acquisition/editing of the `ister` config file (currently `release-image-config.json`).

# Notes
- At a minimum, automate the acquisition of this file so the user doesn't have to `curl` it. Ship a local copy? Curl it ourselves in `mixer init`?
- Automate the setting of the "version" and "format" variables using the values from `builder.conf`?
  - "Version" is in the `config.json` file, while "format" is passed to `ister` as a commandline flag.
- Introduce a "Image Bundles List" in `builder.conf` (or elsewhere), then generate the `config.json` file's "Bundles" list automatically?

**Comment by cmarcelo** [comment]
> At a minimum, automate the acquisition of this file so the user doesn't have to curl it. Ship a local copy? Curl it ourselves in mixer init?

No download. We can embed a default in our code for purposes of "mix init". The format of this configuration for ister should be stable by now.

> Introduce a "Image Bundles List" in builder.conf (or elsewhere), then generate the config.json file's "Bundles" list automatically?

I thought about this before too, but I've changed my mind and don't think we should do this.

The partitioning, mounting table are also important bits for the user to tweak, e.g. "the default 10G images are too big for me" or "I need an extra partition for data by default". The config used by ister has exactly this level of information. Note: I'm envisioning I would add these configuration files for the images I want to keep into version control for the mix I'm creating.

> Automate the setting of the "version" and "format" variables using the values from builder.conf?
>    "Version" is in the config.json file, while "format" is passed to ister as a commandline flag.

I feel neither Version or Format should be in this configuration file for image.

**Comment by kevincwells** [comment]
@cmarcelo 
> No download. We can embed a default in our code for purposes of "mix init". The format of this configuration for ister should be stable by now.

Agreed - I don't think we should be curling it from the network. Easiest right now would be to just ship a local copy with mixer's install, and copy it in to the mix with the init (just like how `builder.conf` gets created right now). It could also be generated programmatically, especially if we did want to have ister config parsing/editing logic in mixer.

> I thought about this before too, but I've changed my mind and don't think we should do this.

Yeah, I've changed my mind on this topic too, I think. Especially after talking to @mdhorn about how people would likely want to use this in practice, I don't think mixer can auto-generate ister config in any meaningfully useful way.

> I feel neither Version or Format should be in this configuration file for image.

I haven't delved into ister much at all, so I'm not sure why things are where they are. I'm guessing cleaning this up would require changes to ister itself, too.

**Comment by tmarcu** [comment]
> Easiest right now would be to just ship a local copy with mixer's install, and copy it in to the mix with the init (just like how builder.conf gets created right now). 

I agree with this approach.

**Comment by reaganlo** [comment]
To restate the issue:
Currently "sudo mixer build image --native" errors out if the default ister config json file "release-image-config.json" is not present in the mix directory.

Recommending the following solution:
When "sudo mixer build image --native" is executed, if "release-image-config.json" is not present in the mix directory", mixer should:
1) Copy the default file from "/usr/share/defaults/ister/release-image-config.json" to the mix directory.
2) Update the "release-image-config.json" file with the bundle list from the "mixbundles" file.
3) Inform the user about the above two steps.
4) Continue the existing build process.

@matthewrsj @phmccarty Please confirm if the above recommendation would suffice.

**Comment by matthewrsj** [comment]
:+1: that looks good to me

**Comment by phmccarty** [comment]
@reaganlo Sounds good to me, too

**Comment by reaganlo** [comment]
ister has been replaced with clr-installer and this has been fixed.
