### ISSUE TITLE
mixer build upstream-format fails - cannot update my mix anymore

### ISSUE THREAD

**Issue by mpurzynski** [clearlinux/mixer-tools#587]
I was trying to update my mix to the most recent version and here's what I got after doing the mixer build upstream-format

(...)
Creating zero pack for os-core to version 1400
  Fullfiles in pack: 2283
  Deltas in pack: 0
Creating zero pack for os-core-update to version 1400
  Fullfiles in pack: 1071
  Deltas in pack: 0
Saving the upstream URL: https://download.clearlinux.org
Saving the upstream version: 29740
Setting latest version to 1400

TIMINGS
  CREATE MANIFESTS  1m4.556s
  CREATE FULLFILES  25ms
  CREATE ZERO PACKS 25.627s
TOTAL: 1m30.21s
2019/06/17 20:23:23 Warning: The host format and mix upstream format do not match. Mixer may be incompatible with this format; running natively may fail.
2019/06/17 20:23:23 ERROR: Couldn't build update: invalid format
2019/06/17 20:23:23 ERROR: failed to execute mixer build format-bump new --new-format  --native: exit status 1

**Comment by mpurzynski** [comment]
My upstreamversion file points to the 29740

This host is on Installed version: 29940

**Comment by rchiossi** [comment]
Did you try running with the format parameter, just like last time?
`sudo mixer build upstream-format --new-format 28`

**Comment by mpurzynski** [comment]
This also failed

Copying +20 bundles to +10 bundles
2019/06/17 21:17:55 ERROR: Couldn't build update: invalid format
2019/06/17 21:17:55 ERROR: failed to execute mixer build format-bump old --new-format 28  --retries 3 --native: exit status 1

**Comment by rchiossi** [comment]
This will usually happen if you run the command above without cleaning up the failed version directories from `update/image` and `update/www`. Just double check the cleanup steps in #536 .

**Comment by rchiossi** [comment]
It is also likely that `FORMAT` value is missing or empty in your `mixer.state`

**Comment by mpurzynski** [comment]
I cleaned everything, rolled back to 1340 and then managed to build 1350 that is based on 29740. What should I do now?

**Comment by rchiossi** [comment]
ok, so if your last stop was a good build in the last format, run the following;
`sudo mixer versions update --upstream-version 29940`
`sudo mixer build upstream-format --new-format 28`

**Comment by mpurzynski** [comment]
System successfully updated. Thanks a lot for the assistance!
Do you think instructions like these could go into documentation?

**Comment by rchiossi** [comment]
actually, this should work out of the box without the need for the extra parameters. I thought this was fixed in our last release, but apparently it slipped through.
But just in case, I'll add it to the docs as well.
