### ISSUE TITLE
Removing includes from bundle definition files can delete bundles

### ISSUE THREAD

**Issue by jwakre** [clearlinux/mixer-tools#592]
When a bundle is added to the mix, any bundles that it includes are also added. Currently, if a bundle that was added to the mix by an include is removed from the bundle definition file, it will be deleted from the MoM. This breaks the bundle deletion workflow.

Steps to reproduce:

1. `mixer bundle create foo`
2. Edit bundle definition at `local-bundles/foo` to include a bundle
3. `mixer bundle add foo`
4. `mixer build all --increment --native --skip-fullfiles --skip-packs`
5. Delete included bundle from bundle definition at `local-bundles/foo`
6. `mixer build all --increment --native --skip-fullfiles --skip-packs`
7. Compare the generated MoMs. The included bundle that was removed should be deleted from the newer MoM.

**Comment by rchiossi** [comment]
Indeed. Includes must be handled as a normal bundle that has been manually added to the mix.

**Comment by jwakre** [comment]
Confirmed that this is not an issue in Mixer 6.1.4.
