### ISSUE TITLE
Incorrect Manifest Generation in Docker

### ISSUE THREAD

**Issue by jwakre** [clearlinux/mixer-tools#594]
Host: Clear Linux, Version 30400
Container: Clear Linux, Version 30340; Mixer 5.7.2

Sometimes when generating manifests inside of a Docker container, they are generated incorrectly. This does not happen every time, but after several calls to `mixer build all`, a manifest will be generated incorrectly.

Steps to reproduce:

Host:
* `sudo docker run --rm -it --net host clearlinux`

Container:
* `swupd bundle-add mixer`
* `mixer init`
* `mixer build all --increment --native`
* `mixer build all --increment --native`
* `mixer build all --increment --native`... Repeat until manifest incorrectly generated

Expected Results: Only the os-core manifest should be updated

Failing Results: Sometimes a partially complete bundle manifest will be generated. It will appear like files were added or deleted to the manifest.

**Comment by jwakre** [comment]
The default runtime for Clear is kata which doesn't support `--net host`. The failures above are likely caused by this lack of support and can probably be resolved by specifying the runc runtime. Although, Mixer should be able to handle this error instead of incorrectly generating manifests.

**Comment by jwakre** [comment]
I replicated this issue with Mixer's built-in Docker support (not using the `--native` flag)

```
mixer init
mixer build all --increment --skip-packs --skip-fullfiles
mixer build all --increment --skip-packs --skip-fullfiles
mixer build all --increment --skip-packs --skip-fullfiles
...
```

Sometimes the manifest generation will be incorrect. This does not seem like a kata runtime issue because Mixer uses the runc runtime when calling Mixer without the `--native` flag

**Comment by jwakre** [comment]
Marked as high priority because Mixer runs in Docker by default. The `--native` flag can be used to not use Docker.

**Comment by gtkramer** [comment]
Alternatively, if memory is correct, mixer started using docker as a means for compatibility between the current and previous formats.  Given mixer will have format compatibility built-in in its code, Docker functionaltiy isn't needed anymore.  Maybe we could prioritize removing Docker from mixer?

**Comment by reaganlo** [comment]
Changing this from high to medium priority because Docker has been removed from mixer in v6.0.0 and now running natively is the default.

**Comment by reaganlo** [comment]
@jwakre Since docker has been removed from mixer, can we close this?
