### ISSUE TITLE
mixer-user-bundler should output progress status during build stage

### ISSUE THREAD

**Issue by bktan8** [clearlinux/mixer-tools#613]
Right now, it's just sits there and it's hard to know if it's stuck or something.  
Printing "......" or more verbose information would be very helpful.

**Comment by rchiossi** [comment]
Can you elaborate? I'm not sure what you mean by `mixer-user-bundler`

**Comment by bktan8** [comment]
`mixer-user-bundler` is a script that comes with the mixer bundle used to generate 3rd-party bundle.

**Comment by rchiossi** [comment]
This is not part of mixer. You should report the issue on clr-user-bundles github. https://github.com/clearlinux/clr-user-bundles

**Comment by bktan8** [comment]
My bad.  Thanks!
