### ISSUE TITLE
Mixer init bundles information for downstream

### ISSUE THREAD

**Issue by clefrks** [clearlinux/mixer-tools#614]
Currently when we run "mixer init",  it will pull bundles information from "https://github.com/clearlinux/clr-bundles/archive/" + ver + ".tar.gz"

Instead of modifying "${MIXER_DIR}/upstream-bundles/clr-bundles-<version>" manually, is there a way for downstream users to provide their own bundles information?

Example "mixer init --bundles-info=<downstream_bundles_info_URL>"

**Comment by clefrks** [comment]
Hi @rchiossi 
When is the estimated next release?

**Comment by rchiossi** [comment]
I'm holding it until rpm2cpio PR is good to go. I'm waiting on some testing results.
