### ISSUE TITLE
Mixer delta pack generation warning

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/mixer-tools#628]
Steps to reproduce:
1. Use the RPMs and bundles from 31290 for a minversion build 10.  Only generate manifests for os-core and os-core-update.
2. Use the RPMs and bundles from 31380 to do an update build 20.  Only generate manifests for os-core and os-core-update.
3. Attempt to generate delta packs between build 10 and 20.
4. See the following warning
```
WARNING: open /srv/mixer/gtkramer-clr-mainline/update/www/20/delta/10-20-9e3f14dcff0e825d3cc30482d6c6ecc28925744e09afd0a26a1a139fabeb7789-9e3f14dcff0e825d3cc30482d6c6ecc28925744e09afd0a26a1a139fabeb7789: no such file or directory
```

In the Manifest.full of 10 (31290), we have:
```
F...    9e3f14dcff0e825d3cc30482d6c6ecc28925744e09afd0a26a1a139fabeb7789        10      /usr/share/gdb/auto-load/usr/lib32/libglib-2.0.so.0.6200.1-gdb.py
F...    9e3f14dcff0e825d3cc30482d6c6ecc28925744e09afd0a26a1a139fabeb7789        10      /usr/share/gdb/auto-load/usr/lib64/libglib-2.0.so.0.6200.1-gdb.py
```

And in the Manifest.full of 20 (31380), we have:
```
F...    9e3f14dcff0e825d3cc30482d6c6ecc28925744e09afd0a26a1a139fabeb7789        20      /usr/share/gdb/auto-load/usr/lib32/libglib-2.0.so.0.6200.2-gdb.py
F...    9e3f14dcff0e825d3cc30482d6c6ecc28925744e09afd0a26a1a139fabeb7789        20      /usr/share/gdb/auto-load/usr/lib64/libglib-2.0.so.0.6200.2-gdb.py
```

After discussing with @phmccarty we suspect this is an edge case in rename logic that is triggered during delta pack creation.  It doesn't make much sense to be generating deltas when the file hashes are the same and a rename just needs performed.

**Comment by ashleshaAtrey** [comment]
Did some research and found the below results. 
FindDeltas() finds these files as deltas but delta is not created as createFileDelta() generates an error.
bsdiff returned FULLDL, not using delta /usr/share/gdb/auto-load/usr/lib32/libglib-2.0.so.0.6200.1-gdb.py (10-9e3f14dcff0e825d3cc30482d6c6ecc28925744e09afd0a26a1a139fabeb7789) -> /usr/share/gdb/auto-load/usr/lib32/libglib-2.0.so.0.6200.2-gdb.py (20-9e3f14dcff0e825d3cc30482d6c6ecc28925744e09afd0a26a1a139fabeb7789)

So delta file is not created, but warning is not generated at this point. 
While we create delta packs, findDeltas is called again and it again find those files as delta. When it tries to copyFromDelta, it returns error as the delta is not found. This error is returned as warning. 
As it doesn't find delta, it tries to create pack using fullfiles.

All the warnings are still appended for all deltas which were not found and are printed as warning on stdout. 

What should be the best method to fix this bug? @reaganlo @rchiossi

**Comment by ashleshaAtrey** [comment]
FYI, bsdiff returns 1 that stands for "FULLDL", i.e. it decided that a delta is not worth.

**Comment by reaganlo** [comment]
See if you can use the output of createFileDelta() instead of FindDeltas() while creating delta packs.

**Comment by aaronovz1** [comment]
Is this related to #578 ? I think I was seeing similar issues for renamed/deleted/missing files.
