### ISSUE TITLE
Mixer fails with permission denied when version path is not set

### ISSUE THREAD

**Issue by tmarcu** [clearlinux/mixer-tools#63]
Steps to reproduce: 
- Start with empty workspace
- Set builder conf to not have `VERSIONS_PATH` or misspelled, i.e `VERSIONS_DIR`
- Run:
```
$ mixer init-mix --clear-version 20010 --mix-version 10
Mixer 3.2.1
***Error: open /.clearurl: permission denied
```

Works when run with sudo, but this command should not need sudo privileges.

**Comment by mdhorn** [comment]
@tmarcu I'll look into this, but the same problem existed before my change if VERSIONS_PATH was missing or wrong, but the fail would be on .clearversion

```
mixer init-mix -clearver 20010 -mixver 10
Mixer 3.1.0
***Error: open /.clearversion: permission denied
```

**Comment by mdhorn** [comment]
@tmarcu Of the possible entries in the builder.conf, which entries, besides VERSIONS_PATH, should be considered as required values?
If I'm going to add error checking for VERSIONS_PATH, should probably also check for other required values.
