### ISSUE TITLE
Make it possible to build a minimum mix to be used by swupd 3rd party

### ISSUE THREAD

**Issue by otaviobp** [clearlinux/mixer-tools#632]
Right now it's not possible to build a mix without:
 - os-core
 - os-core-update
 - os-core-update-index

**Comment by gtkramer** [comment]
It would be awesome if we could remove os-core-update-index from this list :)

**Comment by reaganlo** [comment]
os-core is a hard requirement as it is required by swupd-client. But mixer is now able to create a minimal mix even with an empty os-core bundle. This was implemented as part of https://github.com/clearlinux/mixer-tools/issues/704
So closing this one.
