### ISSUE TITLE
Allow users to control the content generated for os-core-update-index

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/mixer-tools#634]
My understanding is that #593 was backed out to prioritize the addition of also-adds in manifests.  While I don't really like doing short-term fixes to bugs, I do like the idea of putting users in control of content.  Would it be an acceptable short-term fix to allow users to define their own content for os-core-update-index and if this bundle exists, mixer skips the code paths that generate it and use what the user supplies?  This would remediate the impact of #541.

To prepare upstream for removing this bundle, we would define a skeleton bundle definition for os-core-update-index to live alongside the other bundles in clr-bundles/bundles.  It would only contain the filesystem package.  We would eventually want to change the status to 'Pending-Delete' so that DevOps can remove this bundle from this distro, but we could only do that once mixer is no longer producing this bundle as well.

**Comment by rchiossi** [comment]
@gtkramer What do you think about using the new flag @otaviobp proposed in #633?

**Comment by gtkramer** [comment]
This might work actually.  If the work is already done and we have a way to control whether this bundle is generated on our end without 3rd party content, I'm open to using the new option.  I think we'd still want this option to be removed in the future in response to removal of os-core-update-index generation since it is a little hacky.  But I'll take hacky if it works and keeps us going.

**Comment by gtkramer** [comment]
Closing since this will be resolved in a different manner
