### ISSUE TITLE
Change default compression to xz for full files

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/mixer-tools#635]
@ashleshaAtrey has analyzed the gains from testing a number of different compression schemes and picking the file with the lowest size and found that the gain is very marginal over just using the xz compression scheme for everything.  This reduces the amount of time to create full files by at least 50%.  Mixer should offer a way for the user to customize how compression works, letting users pick a single compression scheme.

**Comment by ashleshaAtrey** [comment]
fixed by #637
