### ISSUE TITLE
os-packages file are empty

### ISSUE THREAD

**Issue by clefrks** [clearlinux/mixer-tools#661]
After mixer build bundles, the information packages mapped to their srpm names are populated into {mixer_dir}/update/image/{version}/os-package

Is this feature removed in the latest mixer version?
Can i know where this information is being stored in the latest mixer version?

**Comment by clefrks** [comment]
Sample files of previous generated os-packages when using mixer v5.9.1

gzip-bin        gzip-1.10-29.src.rpm
p11-kit-license p11-kit-0.23.15-55.src.rpm
icu4c-lib       icu4c-64.2-22.src.rpm
systemd-data    systemd-243-267.src.rpm
mlocate mlocate-0.26-2.src.rpm
pacrunner-data  pacrunner-0.16-53.src.rpm
netbase netbase-5.6-19.src.rpm
libcap-license  libcap-2.27-36.src.rpm
btrfs-progs     btrfs-progs-5.3.1-98.src.rpm
dbus-license    dbus-1.12.16-72.src.rpm
clr-find-bundle clr-find-bundle-1.0.2-1.src.rpm
bzip2-license   bzip2-1.0.8-54.src.rpm
gcc-libs-math   gcc-9.2.1-740.src.rpm
e2fsprogs-libexec       e2fsprogs-1.45.4-73.src.rpm
glibc-lib-avx2  glibc-2.30-298.src.rpm
util-linux-license      util-linux-2.34-146.src.rpm
ca-certs-static ca-certs-static-0.1-11.src.rpm
systemd-services        systemd-243-267.src.rpm
tzdata-minimal  tzdata-2019c-28.src.rpm
swupd-overdue-services  swupd-overdue-6-13.src.rpm

**Comment by ashleshaAtrey** [comment]
@clefrks In the latest mixer version, to improve performance we are not using dnf install to extract the packages. Hence the database used to create os-packages file is not being populated. 

What use case does this feature provides you? 
We can come up with a different solution if required.

**Comment by yewwayne** [comment]
We're looking for a record of all packages (and versions) consumed by mixer to produce the mix. Or put another way, all packages available in that OS release. Similar if not identical to the [package-sources](https://cdn.download.clearlinux.org/current/source/package-sources) file.

**Comment by ashleshaAtrey** [comment]
we can provide the package name, version info and architecture of the rpm without impacting performance. Will this work? 
for example:
nss-altfiles-lib-2.23.0-24.x86_64.rpm
mlocate-data-0.26-2.x86_64.rpm
mlocate-services-0.26-2.x86_64.rpm
findutils-license-4.7.0-25.x86_64.rpm

**Comment by yewwayne** [comment]
Yes with an amendment: could the dash-separators between package, version, and release fields be replaced with tabs for easier parsing? Should be possible with something like `rpm -qp --queryformat "${NAME}\t%{VERSION}\t%{RELEASE}\n" rpms...`.

FYI the entries used to be source rpms, not binary rpms which includes `*-lib`, `*-bin`, `*-data`, etc items. But this is acceptable as we can still use dnf to query the source rpms outside of mixer.

**Comment by gtkramer** [comment]
@yewwayne I guess in an ideal world, I would like to see mixer be able to make changes to its internal workspace as needed to support its development.  Having a DevOps process on anything from mixer besides the artifacts in update/www is risky because of this.

From our previous offline conversation, we discussed not filtering packages that DevOps publishes for external repos.  Is there some other reason why this file is needed?  It does not support mixer's internal operation, which is why it was removed.

**Comment by yewwayne** [comment]
@gtkramer actually there isn't, I had the mistaken impression that the scope of packages to publish should be limited to those consumed by mixer, hence the intent to filter from a larger set. It seems a different strategy would be needed that probably won't rely on this bug/feature anymore. Thanks for the correction and sorry for the noise.

**Comment by gtkramer** [comment]
@yewwayne no worries :)

**Comment by jwakre** [comment]
This request is no longer needed, closing.
