### ISSUE TITLE
Mixer build validate fails for local packages

### ISSUE THREAD

**Issue by reaganlo** [clearlinux/mixer-tools#665]
**Describe the bug:**
If a mix is built containing local packages, `mixer build validate` errors out. E.g.
```
WARNING: Local RPMs will override upstream RPMs for both the from and to versions.
2019/12/06 18:17:33 ERROR: 2019/12/06 18:17:33 failed to execute rpm -qp --qf=[%{filenames}%{filesizes}%{filedigests}%{filemodes:perms}%{filelinktos}%{fileusername}%{filegroupname}
] /home/reaganlo/mixer/update/validation/10/packages/google-chrome-stable-78.0.3904.108-1.x86_64.rpm
2019/12/06 18:17:33 
STDERR:
error: open of /home/reaganlo/mixer/update/validation/10/packages/google-chrome-stable-78.0.3904.108-1.x86_64.rpm failed: No such file or directory
2019/12/06 18:17:33 failed to execute
: exit status 1
```
**To Reproduce:**
Download and run the attached `mca-test.txt` file from a clean mixer workspace. This script builds two mix versions both containing a local chrome package.
[mca-test.txt](https://github.com/clearlinux/mixer-tools/files/3934658/mca-test.txt)

**Comment by jwakre** [comment]
@reaganlo The signature of `google-chrome-stable-78.0.3904.108-1.x86_64.rpm` cannot be verified which is the root cause of this failure. I can handle this case by adding the `--nosignature` flag to the MCA rpm command. MCA should still be working with local packages in general.

**Comment by jwakre** [comment]
Additionally, this package breaks an assumption that the rpm will be structured as: `pkg.name + "-" + pkg.version + "." + pkg.arch + ".rpm"`

package name: `google-chrome-stable_current_x86_64.rpm`
MCA name: `google-chrome-stable-79.0.3945.79-1.x86_64.rpm`
