### ISSUE TITLE
Consolidate logging

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/mixer-tools#666]
When debugging or verifying mixer's correct operation, or when bsdiff errors are encountered, or when dnf output should be retained, it would be helpful if all of this logging could be consolidated.

Whether we want a log file or a log folder is up for debate.  Having a log file might make sense to make it easy to go through everything in one file, but it might make it hard to target find something in the log since it would always be somewhat huge due to the volume of bsdiff errors.

Alternatively, having a log folder may make more sense so that we can let the tools that mixer is shelling out to determine how to log, and we just set their configuration.

At a minimum, this needs to first be a global option that can be on every mixer command.  Only having this in builder.conf poses challenges because this doesn't exist until `mixer init` is run.

**Comment by reaganlo** [comment]
Collating the discussions over IRC:

- By default, logging will be turned off. Logging can be turned on by specifying the log file using `--log`
- Logging levels can be set using `--logLevel` (ERR, WRN, INF, DBG, VRB). 
  Default log level is VRB.
- stdout will contain INF level information (basic messages + ERR + WRN). This cannot be changed.

**Comment by gtkramer** [comment]
We should also annotate each line if it's something from mixer, or one of the programs it calls (e.g. bsdiff, dnf) so we can easily differentiate which program is producing which output.

**Comment by gtkramer** [comment]
Timestamps should be included in all output to the logfile

**Comment by gtkramer** [comment]
Allowing the CLI to override what is set in the conf is a nice touch.  This lets us create special logging for certain commands.

Just repeating what we discussed online...

If we don't specify a log file, let's mimic clr-installer and not log to a log file.

Mixer should append to an existing log file if it exists, and put the user in control if managing this file however they want.
