### ISSUE TITLE
Respond better to signals sent to interrupt

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/mixer-tools#668]
When running mixer in a Jenkins context, and the Jenkins job is aborted, mixer does not respond to interrupt signals.  The process and all of its sub processes end up continuing even though the Jenkins job has been hard stopped.  In some cases, the mixer process will still linger long after this happens.

**Comment by ashleshaAtrey** [comment]
@gtkramer It seems like interrupt signal are not reaching mixer process. The script which is calling mixer commands is not able to propagate the interrupt signal to the mixer.

**Comment by gtkramer** [comment]
Hmm, if mixer responds with ctrl+c as expected, then I think we can close this and blame it on Jenkins :)
