### ISSUE TITLE
mixer hangs after several unable to resolve package(s) messages

### ISSUE THREAD

**Issue by mpurzynski** [clearlinux/mixer-tools#703]
Hey,

my mixer started throwing errors out of the blue, about missing packages (I'm pretty sure rpms are in the local-rpms and I updated the local-yum repo)

sudo mixer build all

Directory walk started
Directory walk done - 75 packages
Temporary output repo path: ./.repodata/
Preparing sqlite DBs
Pool started (with 5 workers)
Pool finished
Building bundles...
=> BUILD BUNDLES
Bundle "libstdcpp" already in mix; skipping
Bundle "perl-basic" already in mix; skipping
Bundle "aspell-es" already in mix; skipping
Bundle "aspell-fr" already in mix; skipping
Bundle "aspell-de" already in mix; skipping
Bundle "libstdcpp" already in mix; skipping
Bundle "lib-openssl" already in mix; skipping
Bundle "python3-basic" already in mix; skipping
Bundle "perl-basic" already in mix; skipping
Bundle "libstdcpp" already in mix; skipping
Bundle "libstdcpp" already in mix; skipping
Bundle "aspell" already in mix; skipping
Bundle "curl" already in mix; skipping
Bundle "lib-openssl" already in mix; skipping
Bundle "less" already in mix; skipping
Bundle "p11-kit" already in mix; skipping
Bundle "libstdcpp" already in mix; skipping
Bundle "os-core" already in mix; skipping
Bundle "libglib" already in mix; skipping
Bundle "p11-kit" already in mix; skipping
Bundle "python3-basic" already in mix; skipping
Bundle "libglib" already in mix; skipping
Bundle "c-basic" already in mix; skipping
Bundle "python3-basic" already in mix; skipping
Bundle "perl-basic" already in mix; skipping
Bundle "libstdcpp" already in mix; skipping
Bundle "lib-openssl" already in mix; skipping
Bundle "perl-basic" already in mix; skipping
Bundle "python3-basic" already in mix; skipping
Bundle "clr-network-troubleshooter" already in mix; skipping
Bundle "curl" already in mix; skipping
Bundle "dpdk" already in mix; skipping
Bundle "ethtool" already in mix; skipping
Bundle "iproute2" already in mix; skipping
Bundle "iptables" already in mix; skipping
Bundle "net-tools" already in mix; skipping
Bundle "openssh-client" already in mix; skipping
Bundle "openssl" already in mix; skipping
Bundle "openvswitch" already in mix; skipping
Bundle "rsync" already in mix; skipping
Bundle "wget" already in mix; skipping
Bundle "wpa_supplicant" already in mix; skipping
Bundle "znc" already in mix; skipping
Bundle "p11-kit" already in mix; skipping
Bundle "libstdcpp" already in mix; skipping
Bundle "perl-basic" already in mix; skipping
Bundle "nasm" already in mix; skipping
Bundle "binutils" already in mix; skipping
Bundle "bison" already in mix; skipping
Bundle "flex" already in mix; skipping
Bundle "glibc-locale" already in mix; skipping
Bundle "intltool" already in mix; skipping
Bundle "llvm" already in mix; skipping
Bundle "make" already in mix; skipping
Bundle "nasm" already in mix; skipping
Bundle "libglib" already in mix; skipping
Bundle "lib-openssl" already in mix; skipping
Bundle "openssh-client" already in mix; skipping
Bundle "perl-basic" already in mix; skipping
Bundle "binutils" already in mix; skipping
Bundle "libglib" already in mix; skipping
Bundle "python3-basic" already in mix; skipping
Bundle "os-core" already in mix; skipping
Bundle "os-core-plus" already in mix; skipping
Bundle "os-core-webproxy" already in mix; skipping
Bundle "aspell" already in mix; skipping
Bundle "findutils" already in mix; skipping
Bundle "lib-openssl" already in mix; skipping
Bundle "curl" already in mix; skipping
Bundle "perl-basic" already in mix; skipping
Bundle "python3-basic" already in mix; skipping
Bundle "libstdcpp" already in mix; skipping
Bundle "python3-basic" already in mix; skipping
Bundle "libstdcpp" already in mix; skipping
Bundle "libstdcpp" already in mix; skipping
Bundle "lib-openssl" already in mix; skipping
Bundle "iproute2" already in mix; skipping
Bundle "p11-kit" already in mix; skipping
Bundle "sudo" already in mix; skipping
Bundle "which" already in mix; skipping
Bundle "acpica-unix2" already in mix; skipping
Bundle "libglib" already in mix; skipping
Bundle "diffutils" already in mix; skipping
Bundle "file" already in mix; skipping
Bundle "findutils" already in mix; skipping
Bundle "glibc-locale" already in mix; skipping
Bundle "gzip" already in mix; skipping
Bundle "htop" already in mix; skipping
Bundle "iperf" already in mix; skipping
Bundle "kbd" already in mix; skipping
Bundle "kernel-install" already in mix; skipping
Bundle "less" already in mix; skipping
Bundle "man-pages" already in mix; skipping
Bundle "minicom" already in mix; skipping
Bundle "parallel" already in mix; skipping
Bundle "patch" already in mix; skipping
Bundle "powertop" already in mix; skipping
Bundle "procps-ng" already in mix; skipping
Bundle "strace" already in mix; skipping
Bundle "tmux" already in mix; skipping
Bundle "tzdata" already in mix; skipping
Bundle "unzip" already in mix; skipping
Bundle "xz" already in mix; skipping
Bundle "zstd" already in mix; skipping
Bundle "aspell" already in mix; skipping
Bundle "python3-basic" already in mix; skipping
Bundle "perl-basic" already in mix; skipping
Bundle "python3-basic" already in mix; skipping
Bundle "perl-basic" already in mix; skipping
Bundle "python3-basic" already in mix; skipping
Bundle "openldap" already in mix; skipping
Bundle "libstdcpp" already in mix; skipping
Bundle "openldap" already in mix; skipping
Bundle "lib-samba" already in mix; skipping
Bundle "aspell" already in mix; skipping
Bundle "hardware-uefi" already in mix; skipping
Bundle "bootloader" already in mix; skipping
Bundle "linux-firmware" already in mix; skipping
Bundle "linux-firmware-extras" already in mix; skipping
Bundle "qemu-guest-additions" already in mix; skipping
Bundle "perl-basic" already in mix; skipping
Bundle "lib-openssl" already in mix; skipping
Bundle "findutils" already in mix; skipping
Bundle "openssl" already in mix; skipping
Bundle "libstdcpp" already in mix; skipping
Bundle "lib-openssl" already in mix; skipping
Bundle "os-core" already in mix; skipping
Bundle "libglib" already in mix; skipping
Bundle "bootloader" already in mix; skipping
Bundle "linux-firmware" already in mix; skipping
Bundle "linux-firmware-extras" already in mix; skipping
Bundle "lib-openssl" already in mix; skipping
Bundle "libstdcpp" already in mix; skipping
Bundle "lib-openssl" already in mix; skipping
Bundle "p11-kit" already in mix; skipping
Bundle "git" already in mix; skipping
Bundle "openssl" already in mix; skipping
Bundle "perl-basic" already in mix; skipping
Bundle "python3-basic" already in mix; skipping
Bundle "bc" already in mix; skipping
Bundle "cloc" already in mix; skipping
Bundle "cpio" already in mix; skipping
Bundle "diffutils" already in mix; skipping
Bundle "docutils" already in mix; skipping
Bundle "gdb" already in mix; skipping
Bundle "icdiff" already in mix; skipping
Bundle "inotify-tools" already in mix; skipping
Bundle "linux-tools" already in mix; skipping
Bundle "llvm" already in mix; skipping
Bundle "devpkg-llvm" already in mix; skipping
Bundle "man-pages" already in mix; skipping
Bundle "patch" already in mix; skipping
Bundle "rsync" already in mix; skipping
Bundle "strace" already in mix; skipping
Bundle "valgrind" already in mix; skipping
Bundle "the_silver_searcher" already in mix; skipping
Bundle "libstdcpp" already in mix; skipping
Bundle "lib-openssl" already in mix; skipping
Bundle "python3-basic" already in mix; skipping
Bundle "findutils" already in mix; skipping
Bundle "libstdcpp" already in mix; skipping
Bundle "lib-openssl" already in mix; skipping
Bundle "syslinux" already in mix; skipping
Bundle "lib-openssl" already in mix; skipping
Bundle "linux-firmware-wifi" already in mix; skipping
Bundle "openldap" already in mix; skipping
Bundle "lib-openssl" already in mix; skipping
Bundle "smartmontools" already in mix; skipping
Bundle "libglib" already in mix; skipping
Bundle "samba" already in mix; skipping
Bundle "dosfstools" already in mix; skipping
Bundle "nfs-utils" already in mix; skipping
Bundle "parted" already in mix; skipping
Bundle "pmdk" already in mix; skipping
Bundle "smartmontools" already in mix; skipping
Bundle "xfsprogs" already in mix; skipping
Bundle "sshfs" already in mix; skipping
Bundle "libstdcpp" already in mix; skipping
Bundle "devpkg-base" already in mix; skipping
Creating bundles for version 1820 based on Clear Linux 32100
Preparing new /home/clr/mix/update/image/1820
  and dnf config: /home/clr/mix/.yum-mix.conf
Packager command-line: dnf --config=/home/clr/mix/.yum-mix.conf -y --releasever=32100
Resolving packages using 2 workers
processing linux-firmware-extras
processing parallel
... done with parallel
processing cloc
... done with cloc
processing qemu-guest-additions
... done with qemu-guest-additions
processing cpio
... done with cpio
processing python3-basic
... done with python3-basic
processing c-basic
... done with linux-firmware-extras
processing linux-tools
... done with c-basic
processing which
... done with linux-tools
processing os-core-update
... done with which
processing the_silver_searcher
... done with the_silver_searcher
processing openssh-server
... done with openssh-server
processing aspell-de
... done with aspell-de
processing telemetrics
... done with telemetrics
processing powertop
... done with powertop
processing gdb
... done with os-core-update
processing pmdk
... done with pmdk
processing clr-network-troubleshooter
... done with clr-network-troubleshooter
processing logrotate
... done with logrotate
processing tmux
... done with tmux
processing sysadmin-basic
... done with gdb
processing valgrind
... done with sysadmin-basic
processing strace
... done with valgrind
processing docutils
... done with strace
processing dosfstools
... done with docutils
processing auditd
... done with dosfstools
processing vim
... done with auditd
processing samba
... done with vim
processing suricata
... done with samba
processing make
... done with suricata
processing net-tools
... done with make
processing aspell-fr
... done with net-tools
processing intltool
... done with intltool
processing os-core
... done with os-core
processing kernel-native
... done with kernel-native
processing linux-firmware-wifi
... done with linux-firmware-wifi
processing iptables
... done with iptables
processing wget
... done with aspell-fr
processing rsync
... done with rsync
processing zstd
... done with zstd
processing hardware-uefi
... done with hardware-uefi
processing linux-firmware
... done with linux-firmware
processing acpica-unix2
... done with acpica-unix2
processing legacy
... done with wget
processing binutils
... done with binutils
processing perl-basic
... done with perl-basic
processing znc
... done with znc
processing inotify-tools
... done with inotify-tools
processing openldap
... done with openldap
processing htop
... done with legacy
processing gzip
... done with gzip
processing iproute2
... done with iproute2
processing diffutils
... done with diffutils
processing lib-openssl
... done with lib-openssl
processing dev-utils
... done with htop
processing parted
... done with dev-utils
processing openvswitch
... done with parted
processing kernel-install
... done with kernel-install
processing xz
... done with xz
processing libstdcpp
... done with libstdcpp
processing os-core-plus
... done with os-core-plus
processing zeek
... done with zeek
processing p11-kit
... done with p11-kit
processing xfsprogs
... done with openvswitch
processing bootloader
... done with xfsprogs
processing tzdata
... done with bootloader
processing wpa_supplicant
... done with tzdata
processing nfs-utils
... done with wpa_supplicant
processing nagios
... done with nfs-utils
processing openssl
nagios: unable to resolve package(s):
... done with openssl
processing essentials
... done with essentials
processing ethtool
... done with ethtool
processing patch
... done with patch
processing syslog-ng
syslog-ng: unable to resolve package(s):

^^ and it just stays there, no error message, no nothing. Top doesn't show any system activity.

**Comment by reaganlo** [comment]
We have a fix for the mixer hanging issue in the master branch which will be part of a release tomorrow. 

But in-order to trouble shoot why certain bundles cannot be resolved, can you please try again by deleting the contents of `local-yum` and recreating the repo from the contents of `local-rpms`.
E.g.
`rm -rf local-yum/*`
`mixer add-rpms` : This creates a repo in `local-yum` from the rpms in `local-rpms`

Also, assuming all the rpms required to build the bundles are present in the repos listed by
 `mixer repo list`

**Comment by reaganlo** [comment]
Please let us know if you were able to try out the above suggestion.

**Comment by mpurzynski** [comment]
Cleaning rpms helped and I was able to build a working update. That's interesting and smells like there's a bug somewhere (but since that was blocking our production update, I could not easily preserve anything for investigation).
