### ISSUE TITLE
Build bundles fail for custom os-release file

### ISSUE THREAD

**Issue by reaganlo** [clearlinux/mixer-tools#711]
If the os-core bundle is empty and user specifies an os-release file using Mixer.OS_RELEASE_PATH,
build bundles errors out as follows:
ERROR: Error building bundles: couldn't update os-release file: open <mixer-ws>/update/image/10/full/usr/lib/os-release: no such file or directory

**Comment by reaganlo** [comment]
This could be because https://github.com/clearlinux/mixer-tools/blob/master/builder/bundles.go#L1176 is trying to write to a file to a directory that does not exist.

**Comment by ashleshaAtrey** [comment]
fixed by #712
