### ISSUE TITLE
Provide an option to create a local bundle without copying from upstream

### ISSUE THREAD

**Issue by reaganlo** [clearlinux/mixer-tools#713]
Currently, during bundle create, Mixer copies the bundle definition from upstream if it exists. This can remain as the default behavior. But users should be able to explicitly create a new local bundle even if the name exists upstream. This can be done by introducing a `--local `flag for `mixer bundle create`.
E.g. `mixer bundle create os-core --local`
This should create an empty `os-core` definition file in the \<local-bundles> directory with only the header information. If the file already exists in the directory, do not overwrite it. Inform the user with a message `Bundle "os-core" already exists in local-bundles; skipping`

**Comment by ashleshaAtrey** [comment]
@reaganlo should we overwrite the file if it already exists? 
as bundle create is alias to bundle edit as well. And current default for upstream is to overwrite the destination file if it exists.

**Comment by reaganlo** [comment]
I intentionally wanted to change the current behavior even for default case (`mixer bundle create/edit bundlename`). If bundle name already exists in local-bundles, then do not overwrite. Instead inform the user with a message` Bundle "os-core" already exists in local-bundles; skipping`

**Comment by ashleshaAtrey** [comment]
as per offline discussion, it makes sense to inform user that bundle definition file already exist and skip checking further

**Comment by ashleshaAtrey** [comment]
This change wont affect anything for devops.
if local file exists, we just skip checking upstream. 
if local doesn't exists, we check if bundle exists upstream . If it does, download and overwrite with latest and copy to local dir. 
This is the current flow and this flow will remain the same.

**Comment by reaganlo** [comment]
Sounds good. Thanks for following up.

**Comment by reaganlo** [comment]
@ashleshaAtrey Let the message indicate the full path of the local-bundles dir..
`Bundle "os-core" already exists in /<local-bundles>; skipping`
