### ISSUE TITLE
Content chroots do not maintain file ownership

### ISSUE THREAD

**Issue by jwakre** [clearlinux/mixer-tools#727]
When using content chroots, files copied to the full chroot are owned by root which is not desirable. Files copied to the full chroot should maintain their original file ownership.

**Comment by aaronovz1** [comment]
Was this a recent regression or been broken for a long time?

**Comment by jwakre** [comment]
> Was this a recent regression or been broken for a long time?

Content chroots is a new feature that hasn't been released yet.
