### ISSUE TITLE
MCA incompatible with mixes generated with --no-publish

### ISSUE THREAD

**Issue by jwakre** [clearlinux/mixer-tools#735]
Mixes built with the --no-publish flag do not produce files for the latest version in each format (update/www/version/format1/latest) which is currently required by MCA. This file is used by MCA to determine whether the version in the comparison is a +10.

Mixer needs to deprecate the --no-publish flag or add support to MCA to handle mixes built with the --no-publish flag.

**Comment by reaganlo** [comment]
@gtkramer From what I understood, DevOps is ok with depreciating the --no-publish flag right?

**Comment by gtkramer** [comment]
@reaganlo yes, we can remove this.  Our process no longer depends on this flag, and we want to move to a case where we always publish, but sync out version pointers to a different URL for testing.

**Comment by reaganlo** [comment]
@gtkramer Perfect. Thank you.
