### ISSUE TITLE
Directory permission mismatch without filesystem package

### ISSUE THREAD

**Issue by jwakre** [clearlinux/mixer-tools#738]
When the os-core bundle does not include the filesystem package, it can create directories with potentially undesirable permissions.

1. Create mix that only uses content chroot bundles (no packages).
2. In one of the content chroots, create the "usr/lib" directory with 0755 which are the permissions used by the filesystem package.

Mixer will create the usr/lib directory in the full chroot with 0655 permissions which will conflict with the content chroot.

**Comment by gtkramer** [comment]
My understanding was that filesystem was always a required package?  There's a bit more backstory on this one.  Maybe ask around a bit.

**Comment by jwakre** [comment]
@gtkramer Recently, we dropped the requirement for the filesystem package to support 3rd party repos.

https://github.com/clearlinux/mixer-tools/commit/af3ac917d7de5482fb5d291c37c7eafa8affc4ad

**Comment by gtkramer** [comment]
Interesting, thank you for the background!
