### ISSUE TITLE
Allow users to modify certain values of the os-release file

### ISSUE THREAD

**Issue by castulo** [clearlinux/mixer-tools#744]
When a user uses mixer to create a mix or a 3rd-party repository it would be useful if the user was able to modify the `NAME` and `PRETTY_NAME` from the `os-release` file through mixer.

Swupd reads this file to show information to the user as part of the `swupd info` and `swupd 3rd-party info` commands. Right now it always shows "Clear Linux OS", but users may want to modify that in custom mixes and 3rd-party repos.

**Comment by reaganlo** [comment]
@castulo This has been discussed before but didnt make much sense without the `swupd 3rd-party info`. But now that swupd is planning to have the info feature for 3rd-party, we can implement this in Mixer. What say @bryteise ?

**Comment by reaganlo** [comment]
@castulo Just realized that Mixer has a config parameter `Mixer.OS_RELEASE_PATH` where the user can specify a custom os-release file. Hence closing.

**Comment by reaganlo** [comment]
You can create a custom os-release file (e.g with any NAME,  PRETTY_NAME etc) and provide the path to mixer using the Mixer.OS_RELEASE_PATH. 
E.g. `mixer config set Mixer.OS_RELEASE_PATH <filepath>`
