### ISSUE TITLE
Mixer don't show the upstream-format option as an option.

### ISSUE THREAD

**Issue by postmannen** [clearlinux/mixer-tools#751]
Mixer tool does not seem to show the `upstream-format` option by using the `--help` flag or by using tab completion.

Did some checking and the problem seems to be the `cobra.Command` type for the `upstream-format` got the value for the struct field `hidden` set to `true` in the <https://github.com/clearlinux/mixer-tools/blob/master/mixer/cmd/build.go> file.

Snippet of the code.

```text
var buildUpstreamFormatCmd = &cobra.Command{
	Use:    "upstream-format",
	Short:  "Use to create the necessary builds to cross an upstream format",
	Long:   `Use to create the necessary builds to cross an upstream format`,
	Hidden: true,
...
```

**Comment by reaganlo** [comment]
@jwakre I'm not sure if you know this, but is there a reason this is hidden? I remember there are few commands that we don't recommend people using often and hence keep them hidden in the help.

**Comment by jwakre** [comment]
@reaganlo I think it makes sense to expose this command because downstream mixes need to call it to pass upstream format bumps. I'm not sure why all of the format bump related commands were hidden. Maybe they aren't complete enough to replace afb.sh.
