### ISSUE TITLE
Invalid Keyboard 'us' - mixer issue in create new image

### ISSUE THREAD

**Issue by ionutnechita** [clearlinux/mixer-tools#766]
Hi ClearLinux Team,

Invalid Keyboard 'us' - mixer issue in create new image

sudo mixer build image  --template release-image-config.yaml
Invalid Keyboard 'us'
ERROR: Couldn't build image: exit status 1

sudo mixer versions
Current mix:               33010
Current upstream:          33010 (format: 30)

First upstream in format:  32480
Latest upstream in format: 33010
sudo mixer --version
Mixer 6.2.2

> release-image-config.yaml

block-devices: [
   {name: "installer", file: "installer.img"}
]

targetMedia:
- name: ${installer}
  type: disk
  children:
  - name: ${installer}1
    fstype: ext4
    mountpoint: /
    size: "5.6G"
    type: part

bundles: [os-core, os-core-update, package-utils]
autoUpdate: false
postArchive: false
postReboot: false
telemetry: false

keyboard: us
language: en_US.UTF-8

kernel: kernel-iot-lts2018

post-install: [
   {cmd: "scripts/installer-post.sh ${chrootDir}"},
]

**Comment by reaganlo** [comment]
@ionutnechita I wasn't able to reproduce it. Can you run the following command and see if "us" keyboard is in the list. `localectl list-keymaps --no-pager`

**Comment by reaganlo** [comment]
Closing this because its not reproducible and no response.

**Comment by ionutnechita** [comment]
It's ok for close this ticket.

Maybe in the future, I'll redo the setup so I can test again.

**Comment by mk-rl** [comment]
Hi!

I was just running into possibly the same / similar issue.  In my scenario I was trying to run clr-installer in a chroot environment (long story).

```
# clr-installer --config  pxe.yaml 
Invalid Keyboard 'us'
```

```
# localectl list-keymaps --no-pager
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
```

It might be handy to not require systemd / keymaps for a scripted install process.
