### ISSUE TITLE
Usability: Implement basic autocomplete using Cobra

### ISSUE THREAD

**Issue by kevincwells** [clearlinux/mixer-tools#77]
# Proposal
Cobra has built-in functionality to generate both bash and zsh autocomplete configuration for mixer, including all commands and flags. Using this functionality will significantly improve mixer's usability.

There are a number of ways to do this, so design details will likely be filled in when the issue is taken up.

**Note** Cobra also supports advanced, contextual auto-complete for specific functions (e.g. typing `mixer bundle add edi[tab][tab]` autocompletes to `editors`), but those will need to be implemented on a command-by-command basis.

**Comment by kevincwells** [comment]
# Implementation Options
I looked into how some other Cobra apps do this, so I wrote this up mostly as a way to organize my thoughts and pass my learnings on to whoever picks this up (in case it's not me).

## Background
Autocompletion for commandline tools works by sourcing a configuration file that describes the autocomplete options available for a command. Bash and zsh each have their own format for how and where to put these configuration files.

Cobra's autocomplete generation works via the [GenBashCompletion](https://godoc.org/github.com/spf13/cobra#Command.GenBashCompletion) and [GenBashCompletionFile](https://godoc.org/github.com/spf13/cobra#Command.GenBashCompletionFile) commands (and their zsh counterparts). Essentially you create another runnable command, and the business logic of that command calls one of these functions on your apps RootCmd.

## Generating the autocomplete file
### Command in Mixer
This option would involve adding a new command to mixer itself to generate the autocomplete. This is the option taken by [Hugo](https://gohugo.io/commands/hugo_gen_autocomplete/) and [Kubernetes](https://kubernetes.io/docs/tasks/tools/install-kubectl/#enabling-shell-autocompletion).
### Standalone Util
Alternatively, a separate executable could be made in the same package as mixer -- say, `mixer_autocomplete` -- that's sole purpose is to import the root command and generate its autocomplete file. The pros to this is there isn't a command hanging off mixer for autocomplete. The con to this is you have a separate executable that gets built (though obviously doesn't have to be installed)

## What we do with the autocomplete file
### "Installing" it
Hugo takes the approach of writing directly to `/etc/bash_completion.d` (though they let you specify a different path for the completion file). This isn't done automatically (i.e., at hugo install time); you need to manually run `sudo hugo gen completion`, and you must run it with `sudo` due to writing to `/etc`

Docker (which also uses Cobra, but does not appear to use it for autocompletion) takes the approach of installing their autocomplete file to `/etc/bash_completion.d/` at package install time.
### Generating it on the fly
Kubernetes takes the approach of outputing its autocomplete file to stdout, and tells you to add `source <(kubectl completion bash)` to your .bashrc (or .zshrc). 

## Proposal
My gut says that this should be something that gets done automatically at install time, not something you have to run/configure manually (i.e. hugo/kubernetes).

I'm leaning toward running the generation command (whether its a command off `mixer` itself or a separate application built via `make autocomplete` or something) at install time to put the file in `/etc/bash_complete.d/` and/or `~/.zsh/completion/`.

**Comment by mdhorn** [comment]
🥇 Please enable this!
I agree with your proposal that the autocompletion data should be generated at build time and add as part of the installation. I'd lean towards having the separate executable for generating the autocomplete data to keep the list of root commands clean.

**Comment by kevincwells** [comment]
@mdhorn this got merged to Master yesterday. Enjoy!

I'm working on the contextual completion (`mixer bundle add edi[TAB]` --> `mixer bundle add editors`) right now.
