### ISSUE TITLE
proposal: add command to create delta-packs in mixer tool

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/mixer-tools#83]
Currently the mixer tool only creates the zero packs, and a separate shell script pack-maker.sh (installed as mixer-pack-maker.sh) is used to create the packs.

In the new swupd implementation (and its test programs) we already have code to do most of what mixer-pack-maker.sh does. The interface will include the proposed "--back" flag in #12, with its new semantics of going back MoM versions.

    # build all deltas from K previous versions to the current one
    mixer build delta-packs --back K

    # build all deltas from K previous versions to version N
    mixer build delta-packs --back K --to N

    # build all deltas from version M to version N
    mixer build delta-packs --from M --to N

I'm also inclined to include:

    # build delta pack for os-core bundle only from M to N
    mixer build delta-packs --bundle os-core --from M --to N

The new command would only work with "--new-swupd", mixer-pack.sh would only be removed when we stop to use swupd-server C implementation.

**Comment by matthewrsj** [comment]
What does the combination of `--back K` and `--to N` produce? Is it `K` back from `N` or `K` back from current and up to `N`? The first one seems more logical.

+1 for the proposal, I see this as necessary for the rewrite.

**Comment by cmarcelo** [comment]
Thanks for the review. Yes, it is the first one. I see how the original description is ambiguous, I'll improve that on the command help message.

**Comment by cmarcelo** [comment]
@tmarcu @kevincwells could one of you take a look at this before I proceed with it? :-)

**Comment by kevincwells** [comment]
The overall idea makes sense to me -- +1 for obsoleting pack-maker.sh with mixer functionality.

As far as CLI, the meaning of `--back` -- and how it differs from `--from` -- definitely feels unclear at first. Maybe it could be named something a little more self-explanatory? 

`--back K` means to build packs "for the previous K versions", and `--back K --to N` means "for the K versions leading up to N".... so maybe even something like `--num-versions`?

**Comment by phmccarty** [comment]
I don't really like the `--back` option name anymore since it does not describe the option meaning clearly.

`--num-versions` seems okay, but if you don't mind the verbosity, `--previous-versions` or `--previous-version-count` would be more clear to me.

**Comment by cmarcelo** [comment]
OK! I was just reusing the name "back" from a previous PR. I'll incorporate one of those names instead.

**Comment by kevincwells** [comment]
+1 I think `--previous-versions` is pretty good! Probably can infer the "count" from the fact it's an integer.
