### ISSUE TITLE
CreateManifests should support non-numeric format

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/mixer-tools#87]
E.g. of usage is "formatstaging"

**Comment by matthewrsj** [comment]
"staging" is a string that can be passed to the client to look in `version/formatstaging` for the relevant maxversion information. It actually isn't needed by the swupd code in mixer I believe. If you look at the current swupd-server the code that used to write that file is removed with `#if 0 ... #endif`

Or am I missing the point @cmarcelo

**Comment by cmarcelo** [comment]
For some reason I thought that we could call server with a string, but that is not the case. Sorry for the noise on this one. I'll handle the validation of this together with the validation of Mixver (that also must be numeric).
