### ISSUE TITLE
CreateManifests (or some other part) should create the tarred version of the manifests

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/mixer-tools#88]
At least "swupd verify -i" (how I was testing) seems to depend on those and not fallback to the plain versions.

**Comment by matthewrsj** [comment]
This seems like more of a task for the fullfile creation to me. Fullfile creation is creating the downloadable full-files for an update using the output from CreateManifests. The manifest tar is essentially a specific-case fullfile.

**Comment by cmarcelo** [comment]
I'll take a look then.
