### ISSUE TITLE
mixer init-mix flag error message incorrect

### ISSUE THREAD

**Issue by matthewrsj** [clearlinux/mixer-tools#97]
```
$ mixer init-mix
ERROR: Please supply -clearver and -mixver
```
Ok, I'll try that
```
$ mixer init-mix -clearver 20000 -mixver 10
Error: unknown shorthand flag: 'c' in -clearver
Usage:
<usage text is correct>
```
Same with -mixver
```
$ mixer init-mix --clear-version 20000 -mixver 10
Error: unknown shorthand flag: 'm' in -mixver
Usage:
<usage text is correct>
```
Obviously this works
```
$ mixer init-mix --clear-version 20000 --mix-version 10
< success >
```

**Comment by kevincwells** [comment]
I noticed the same thing and have it as a clean-up commit in the patch I'm working on right now.

**Comment by kevincwells** [comment]
I also moved the flag checking up to the `Run` command where it belongs, and made it a `RunE` to pass this usage error back up to Cobra, so usage data is spat out.

**Comment by kevincwells** [comment]
Annnnnnnd now I see you already did it. :P
